// GENERATED by scripts/course-from-spec.mjs from specs/course/course.t27 and apps/website/i18n/course.ru.json
// spec sha256 cf32591949f69f749952f2512653a8096e048caff9cb1817a199979136e1a7a3
// Do not edit: change the .t27 source (or the Russian bundle) and regenerate.

export const COURSE = {
  "source": {
    "spec": "specs/course/course.t27",
    "publicSpec": "public/learn/course.t27",
    "ruContract": "specs/course/course-ru.t27",
    "ruBundle": "apps/website/i18n/course.ru.json",
    "sha256": "cf32591949f69f749952f2512653a8096e048caff9cb1817a199979136e1a7a3",
    "schemaVersion": 1,
    "gallery": "specs/widgets/gallery.t27"
  },
  "route": "course",
  "cohortRoute": "fpga-training",
  "progressKey": "t27-course-done",
  "sendsNothing": true,
  "locales": [
    "en",
    "ru"
  ],
  "say": {
    "en": {
      "TITLE": "From zero to a chip: FPGA programming with t27",
      "DESCRIPTION": "27 lessons, one working widget each: what an FPGA is, how numbers become bits, your own t27 spec, how t27c compiles it, and how it becomes a bitstream on a real board. Then a lab of 3 on our own research, 3 lessons on the MX number formats AI chips use, and 6 on ternary weights and the Ternary Network Float.",
      "ALL": "All lessons",
      "ALSO": "Also try",
      "ALSO_HINT": "Each one swaps the widget above.",
      "BACK_TO_MAIN": "Back to this lesson's widget",
      "COHORT": "Looking for the paid FPGA training? It moved to its own page.",
      "CONTINUE": "Continue",
      "GOAL": "You will learn",
      "KICKER": "Course",
      "LEAD": "No hardware background needed. Every lesson opens a real tool built from real runs on our bench: read a little, then try it yourself.",
      "LESSON": "Lesson {0} of {1}",
      "MARK": "Mark as done",
      "MARKED": "Done",
      "MODULE": "Module {0}",
      "NEXT": "Next",
      "NOT_FOUND": "No lesson has this address.",
      "OPEN_COURSE": "Open the interactive course",
      "OPEN_LESSON": "Open the interactive lesson",
      "OPEN_PAGE": "Open the widget on its own page",
      "PREV": "Previous",
      "PRIVATE": "Progress stays in this browser; nothing is sent.",
      "PROGRESS": "{0} of {1} done",
      "SEO_TITLE": "{0}: FPGA course, lesson {1} of {2}",
      "SHAPE": "9 modules of 3 lessons, 27 cells, then a lab of 3, an AI numbers module of 3 and two ternary modules of 3. A filled cell is a lesson you marked done.",
      "SHARE": "Link to share, with a preview card",
      "SOURCE": "This course is itself a t27 spec: read it",
      "SPEC": "Open the lesson's spec in the player",
      "START": "Start lesson 1",
      "TRY": "Try it",
      "WIDGET_LANG": "Widgets keep their own English words: each one lives in its own t27 spec."
    },
    "ru": {
      "TITLE": "С нуля до чипа: программирование FPGA на t27",
      "DESCRIPTION": "27 уроков, в каждом рабочий виджет: что такое FPGA, как числа становятся битами, ваша спека на t27, как её компилирует t27c и как она превращается в битстрим на настоящей плате. Затем лаборатория из 3 уроков о наших собственных исследованиях, 3 урока о форматах чисел MX, которыми пользуются ИИ-чипы, и 6 — о тернарных весах и формате Ternary Network Float.",
      "ALL": "Все уроки",
      "ALSO": "Ещё попробуйте",
      "ALSO_HINT": "Каждая кнопка меняет виджет выше.",
      "BACK_TO_MAIN": "Вернуть виджет этого урока",
      "COHORT": "Ищете платное обучение FPGA? Оно переехало на свою страницу.",
      "CONTINUE": "Продолжить",
      "GOAL": "Вы узнаете",
      "KICKER": "Курс",
      "LEAD": "Опыт с железом не нужен. Каждый урок открывает настоящий инструмент, собранный из реальных запусков на нашем стенде: прочитайте немного и попробуйте сами.",
      "LESSON": "Урок {0} из {1}",
      "MARK": "Отметить пройденным",
      "MARKED": "Пройден",
      "MODULE": "Модуль {0}",
      "NEXT": "Дальше",
      "NOT_FOUND": "Урока с таким адресом нет.",
      "OPEN_COURSE": "Открыть интерактивный курс",
      "OPEN_LESSON": "Открыть интерактивный урок",
      "OPEN_PAGE": "Открыть виджет на отдельной странице",
      "PREV": "Назад",
      "PRIVATE": "Прогресс хранится только в этом браузере; ничего не отправляется.",
      "PROGRESS": "Пройдено {0} из {1}",
      "SEO_TITLE": "{0}: курс по FPGA, урок {1} из {2}",
      "SHAPE": "9 модулей по 3 урока, 27 клеток, затем лаборатория из 3, модуль ИИ-чисел из 3 и два тернарных модуля по 3. Закрашенная клетка — урок, который вы отметили пройденным.",
      "SHARE": "Ссылка, чтобы поделиться, с карточкой превью",
      "SOURCE": "Этот курс сам является спекой t27: прочитайте её",
      "SPEC": "Открыть спеку урока в плеере",
      "START": "Начать урок 1",
      "TRY": "Попробуйте",
      "WIDGET_LANG": "Виджеты говорят по-английски: их слова живут в их собственных спеках t27."
    }
  },
  "modules": [
    {
      "id": "chip",
      "n": 1,
      "lessons": [
        "fpga-is-a-grid",
        "which-chip",
        "pins-and-package"
      ],
      "en": {
        "title": "The chip",
        "line": "What an FPGA is, which chip we use, and how its pins meet the board."
      },
      "ru": {
        "title": "Чип",
        "line": "Что такое FPGA, какой чип у нас и как его выводы встречаются с платой."
      }
    },
    {
      "id": "numbers",
      "n": 2,
      "lessons": [
        "bits-and-trits",
        "what-arithmetic-costs",
        "how-much-fits"
      ],
      "en": {
        "title": "Numbers in hardware",
        "line": "Bits, trits and number formats, and what arithmetic costs in logic."
      },
      "ru": {
        "title": "Числа в железе",
        "line": "Биты, триты и форматы чисел, и сколько стоит арифметика в логике."
      }
    },
    {
      "id": "program",
      "n": 3,
      "lessons": [
        "hello-t27",
        "tests-are-the-spec",
        "compiles-is-not-correct"
      ],
      "en": {
        "title": "Your t27 program",
        "line": "Write a spec, test it, and see why compiling is not the same as being right."
      },
      "ru": {
        "title": "Ваша программа на t27",
        "line": "Напишите спеку, проверьте её и увидьте, почему «компилируется» не значит «верно»."
      }
    },
    {
      "id": "compiler",
      "n": 4,
      "lessons": [
        "compiler-stages",
        "t27c-on-a-real-machine",
        "seven-backends-and-t27b"
      ],
      "en": {
        "title": "Inside t27c",
        "line": "How the compiler reads a spec and what it writes, including the native t27b."
      },
      "ru": {
        "title": "Внутри t27c",
        "line": "Как компилятор читает спеку и что он пишет, включая нативный t27b."
      }
    },
    {
      "id": "hardware",
      "n": 5,
      "lessons": [
        "spec-to-verilog",
        "count-the-cells",
        "one-lut-up-close"
      ],
      "en": {
        "title": "From spec to hardware",
        "line": "The Verilog t27c writes, the cells it becomes, and what one LUT does."
      },
      "ru": {
        "title": "От спеки к железу",
        "line": "Verilog, который пишет t27c, ячейки, в которые он превращается, и что делает одна LUT."
      }
    },
    {
      "id": "synthesis",
      "n": 6,
      "lessons": [
        "synthesis-warnings",
        "state-machines",
        "where-the-luts-go"
      ],
      "en": {
        "title": "Reading synthesis",
        "line": "What yosys reports about your design, and which warnings matter."
      },
      "ru": {
        "title": "Читаем синтез",
        "line": "Что yosys сообщает о вашем дизайне и какие предупреждения важны."
      }
    },
    {
      "id": "timing",
      "n": 7,
      "lessons": [
        "placement",
        "logic-depth",
        "timing-slack"
      ],
      "en": {
        "title": "Place, route, timing",
        "line": "Where the cells land on the die, and whether the clock is met."
      },
      "ru": {
        "title": "Размещение, трассировка, тайминг",
        "line": "Где ячейки оказываются на кристалле и успевает ли тактовая частота."
      }
    },
    {
      "id": "bitstream",
      "n": 8,
      "lessons": [
        "fasm-to-frames",
        "a-build-receipt",
        "read-a-bitstream"
      ],
      "en": {
        "title": "The bitstream",
        "line": "How a routed design becomes the bits the chip loads, with no Vivado."
      },
      "ru": {
        "title": "Битстрим",
        "line": "Как оттрассированный дизайн становится битами, которые загружает чип, без Vivado."
      }
    },
    {
      "id": "board",
      "n": 9,
      "lessons": [
        "jtag-asks-the-chip",
        "same-bits-on-the-board",
        "capstone"
      ],
      "en": {
        "title": "On the board",
        "line": "Ask the chip who it is, load the bits, and check them."
      },
      "ru": {
        "title": "На плате",
        "line": "Спросите чип, кто он, загрузите биты и проверьте их."
      }
    },
    {
      "id": "lab",
      "n": 10,
      "lessons": [
        "t27-number-format",
        "an-honest-scoreboard",
        "a-model-on-the-board"
      ],
      "en": {
        "title": "Lab: our own research",
        "line": "A number format of our own, an honest scoreboard, and a model's tables multiplied on the board."
      },
      "ru": {
        "title": "Лаборатория: наши исследования",
        "line": "Свой формат чисел, честная таблица результатов и таблицы модели, перемноженные на плате."
      }
    },
    {
      "id": "mx",
      "n": 11,
      "lessons": [
        "one-scale-per-block",
        "scale-byte-native",
        "one-outlier"
      ],
      "en": {
        "title": "AI numbers: the MX block",
        "line": "How AI chips keep weights in a few bits: one shared scale per block, the scale byte itself, and what one outlier does to its neighbours."
      },
      "ru": {
        "title": "ИИ-числа: блок MX",
        "line": "Как ИИ-чипы хранят веса в нескольких битах: один общий масштаб на блок, сам байт масштаба и что один выброс делает с соседями."
      }
    },
    {
      "id": "ternary",
      "n": 12,
      "lessons": [
        "phi-scaled-ternary",
        "a-pass-that-checked-nothing",
        "five-rules-for-weights"
      ],
      "en": {
        "title": "Ternary weights",
        "line": "Weights that are only minus, zero or plus a scale, the five rules a ternary alphabet must pass, and a test pass that checked nothing."
      },
      "ru": {
        "title": "Тернарные веса",
        "line": "Веса, которые бывают только минус масштаб, ноль или плюс масштаб, пять правил, которые должен пройти тернарный алфавит, и прогон тестов, который ничего не проверил."
      }
    },
    {
      "id": "tnf",
      "n": 13,
      "lessons": [
        "blocked-is-not-failed",
        "four-trit-exponent",
        "negate-twice"
      ],
      "en": {
        "title": "The Ternary Network Float",
        "line": "A rule the compiler enforces before any test runs, and a 17-bit float whose exponent is four balanced trits."
      },
      "ru": {
        "title": "Тернарный формат Ternary Network Float",
        "line": "Правило, которое компилятор проверяет до запуска любого теста, и 17-битное число с плавающей точкой, порядок которого — четыре сбалансированных трита."
      }
    }
  ],
  "lessons": [
    {
      "id": "fpga-is-a-grid",
      "n": 1,
      "module": "chip",
      "widget": {
        "id": "fasm-skyline",
        "kind": "tool",
        "title": "FASM skyline: a routed 7-series design as a city on the XC7A200T die",
        "url": "https://t27.ai/widgets/fasm-skyline/",
        "preview": "widgets/fasm-skyline/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "placement-map",
          "kind": "tool",
          "title": "Placement map: where nextpnr put every cell on the XC7A200T",
          "url": "https://t27.ai/widgets/placement-map/",
          "preview": "widgets/placement-map/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "An FPGA is a grid you configure",
        "goal": "What an FPGA is made of, and why a design uses only part of the chip.",
        "text": "A CPU runs instructions one after another. An FPGA has no program at all: it is a grid of small blocks -- lookup tables (LUTs), flip-flops, carry chains, block RAM and DSP multipliers -- joined by wires you can switch. Configuring the grid builds a circuit. Our bench chip is an AMD Artix-7 XC7A200T. The skyline draws one routed design on that die: every tile it configures stands up as a column, and most of the chip stays dark.",
        "task": "Rotate the die and tap the tallest column: which kind of tile sets the most features?"
      },
      "ru": {
        "title": "FPGA — это сетка, которую вы настраиваете",
        "goal": "Из чего состоит FPGA и почему дизайн занимает только часть чипа.",
        "text": "Процессор выполняет инструкции одну за другой. У FPGA программы нет вовсе: это сетка маленьких блоков — таблиц истинности (LUT), триггеров, цепочек переноса, блочной памяти и DSP-умножителей, — соединённых проводами, которые можно переключать. Настроив сетку, вы строите схему. Чип нашего стенда — AMD Artix-7 XC7A200T. Skyline рисует один оттрассированный дизайн на этом кристалле: каждый настроенный тайл встаёт столбиком, а большая часть чипа остаётся тёмной.",
        "task": "Поверните кристалл и нажмите на самый высокий столбик: какой тип тайла задаёт больше всего фич?"
      }
    },
    {
      "id": "which-chip",
      "n": 2,
      "module": "chip",
      "widget": {
        "id": "idcode",
        "kind": "tool",
        "title": "JTAG IDCODE decoder: 32 bits, four fields, one device",
        "url": "https://t27.ai/widgets/idcode/",
        "preview": "widgets/idcode/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "tri-fpga-jtag",
          "kind": "cast",
          "title": "tri fpga-jtag · which chip answered the cable",
          "url": "https://t27.ai/term/tri-fpga-jtag/",
          "preview": "term/tri-fpga-jtag/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Which chip is this?",
        "goal": "How a chip names itself in 32 bits, and how to read those bits.",
        "text": "Before you load anything, you ask the board which chip it has. Over JTAG every chip answers with a 32-bit IDCODE: a version, a part number, the manufacturer and a fixed 1 in bit 0. A bitstream built for the wrong part is refused by the chip, so this is the check that saves you an afternoon. The decoder splits the bits into those four fields and looks the part up in openFPGALoader's own table.",
        "task": "Click the bench preset, then flip one bit of the part number and see which device it would be."
      },
      "ru": {
        "title": "Какой это чип?",
        "goal": "Как чип называет себя в 32 битах и как эти биты читать.",
        "text": "Прежде чем что-то загружать, спросите плату, какой на ней чип. По JTAG каждый чип отвечает 32-битным IDCODE: версия, номер детали, производитель и постоянная 1 в бите 0. Битстрим, собранный для другой детали, чип отвергнет, так что эта проверка экономит вам полдня. Декодер делит биты на эти четыре поля и ищет деталь в таблице самого openFPGALoader.",
        "task": "Нажмите пресет стенда, затем переверните один бит номера детали и посмотрите, какое это было бы устройство."
      }
    },
    {
      "id": "pins-and-package",
      "n": 3,
      "module": "chip",
      "widget": {
        "id": "pin-map",
        "kind": "tool",
        "title": "Pin map: the XC7A200T FGG676 package ball by ball, with an XDC lint",
        "url": "https://t27.ai/widgets/pin-map/",
        "preview": "widgets/pin-map/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "tri-fpga-pins",
          "kind": "cast",
          "title": "tri fpga-pins · the blast radius of an edit, before the edit",
          "url": "https://t27.ai/term/tri-fpga-pins/",
          "preview": "term/tri-fpga-pins/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Pins, balls and the package",
        "goal": "How the signals of your design reach the outside world.",
        "text": "A chip sits in a package: the XC7A200T on our board has 676 solder balls under it. Some carry power or configuration and only some are user IO, grouped into banks with their own voltage. A constraints file (XDC) says which ball each signal of your design uses. Put a signal on a ball that is not user IO and the build fails, or worse, the board does not do what you think.",
        "task": "Search for a ball name like E3, then colour by pin type and find a ball that is not user IO."
      },
      "ru": {
        "title": "Выводы, шарики и корпус",
        "goal": "Как сигналы вашего дизайна попадают во внешний мир.",
        "text": "Чип сидит в корпусе: у XC7A200T на нашей плате под ним 676 шариков припоя. Часть несёт питание или конфигурацию, и только часть — пользовательский ввод-вывод, сгруппированный в банки со своим напряжением. Файл ограничений (XDC) говорит, какой шарик использует каждый сигнал дизайна. Поставьте сигнал на шарик, который не является пользовательским IO, и сборка упадёт или, хуже, плата будет делать не то, что вы думаете.",
        "task": "Найдите шарик по имени, например E3, затем раскрасьте по типу вывода и найдите шарик, который не является пользовательским IO."
      }
    },
    {
      "id": "bits-and-trits",
      "n": 4,
      "module": "numbers",
      "widget": {
        "id": "gf16-calc",
        "kind": "tool",
        "title": "GF16 calculator: a number as 16 GoldenFloat bits and as ternary",
        "url": "https://t27.ai/widgets/gf16-calc/",
        "preview": "widgets/gf16-calc/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": {
        "path": "specs/tutorial/01_values_and_types.t27",
        "source": "t27/files/specs/tutorial/01_values_and_types.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F01_values_and_types.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Bits, trits and GF16",
        "goal": "How a number is stored in bits, and how balanced ternary stores it in trits.",
        "text": "Hardware stores numbers as fixed groups of bits, and t27 makes you write the width: u8 is 8 unsigned bits, i16 is 16 signed bits. t27 also speaks balanced ternary, where a trit is -1, 0 or +1. For fractions it has GF16, a 16-bit float with 1 sign bit, 6 exponent bits and 9 mantissa bits. Type a number into the calculator and watch how it is rounded, field by field, and how big the error is.",
        "task": "Type 1.618 and read the exponent and mantissa bits; then type 0.1 and look at the error."
      },
      "ru": {
        "title": "Биты, триты и GF16",
        "goal": "Как число хранится в битах и как сбалансированная троичная система хранит его в тритах.",
        "text": "Железо хранит числа как группы битов фиксированной длины, и t27 заставляет писать ширину: u8 — это 8 беззнаковых битов, i16 — 16 битов со знаком. t27 также говорит на сбалансированной троичной системе, где трит равен -1, 0 или +1. Для дробей есть GF16, 16-битное число с плавающей точкой: 1 бит знака, 6 битов экспоненты и 9 битов мантиссы. Введите число в калькулятор и посмотрите, как оно округляется, поле за полем, и насколько велика ошибка.",
        "task": "Введите 1.618 и прочитайте биты экспоненты и мантиссы; затем введите 0.1 и посмотрите на ошибку."
      }
    },
    {
      "id": "what-arithmetic-costs",
      "n": 5,
      "module": "numbers",
      "widget": {
        "id": "cost-curves",
        "kind": "tool",
        "title": "Cost curves: adders, multipliers and MACs on a Xilinx 7-series",
        "url": "https://t27.ai/widgets/cost-curves/",
        "preview": "widgets/cost-curves/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "resource-bars",
          "kind": "tool",
          "title": "Resource bars: LUT, FF, BRAM and DSP used on the XC7A200T",
          "url": "https://t27.ai/widgets/resource-bars/",
          "preview": "widgets/resource-bars/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/tutorial/05_widths_and_casts.t27",
        "source": "t27/files/specs/tutorial/05_widths_and_casts.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F05_widths_and_casts.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "What arithmetic costs",
        "goal": "Why a multiplier is expensive and an adder is cheap, measured on a real chip.",
        "text": "In logic, every operation has a price paid in chip resources. An adder is a carry chain, cheap and fast. A multiplier built from LUTs is large; the chip has DSP blocks made for multiplying, and a synthesizer uses them when it may. These curves are real yosys counts from 4 to 64 bits. Switch DSPs off and on, and see why hardware people care so much about the width of every number.",
        "task": "Pick Multiply, switch DSP48E1 to -nodsp, and compare the LUTs at 32 bits with and without DSPs."
      },
      "ru": {
        "title": "Сколько стоит арифметика",
        "goal": "Почему умножитель дорогой, а сумматор дешёвый, — по измерениям на настоящем чипе.",
        "text": "В логике у каждой операции есть цена, которую платят ресурсами чипа. Сумматор — это цепочка переноса, дешёвая и быстрая. Умножитель из LUT огромен; на чипе есть DSP-блоки, сделанные для умножения, и синтезатор использует их, когда ему можно. Эти кривые — настоящие подсчёты yosys от 4 до 64 битов. Выключите и включите DSP и увидите, почему в железе так заботятся о ширине каждого числа.",
        "task": "Выберите Multiply, переключите DSP48E1 на -nodsp и сравните LUT на 32 битах с DSP и без них."
      }
    },
    {
      "id": "how-much-fits",
      "n": 6,
      "module": "numbers",
      "widget": {
        "id": "fits-on",
        "kind": "tool",
        "title": "Fits on a 200T: how many copies of your design an XC7A200T holds",
        "url": "https://t27.ai/widgets/fits-on/",
        "preview": "widgets/fits-on/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "How much fits on the chip",
        "goal": "How to read a resource count and find which resource runs out first.",
        "text": "A synthesis report says how many LUTs, flip-flops, DSPs and block RAMs your design takes. The question that matters is which of them runs out first. A design can use few LUTs and still not fit because it needs more DSPs than the chip has. Type a LUT count, or pick one of our real designs, and see how many copies fit on an XC7A200T.",
        "task": "Pick a real design, then raise the DSP count until something other than LUTs runs out first."
      },
      "ru": {
        "title": "Сколько помещается на чип",
        "goal": "Как читать подсчёт ресурсов и находить, какой ресурс кончится раньше.",
        "text": "Отчёт синтеза говорит, сколько LUT, триггеров, DSP и блоков памяти занимает дизайн. Важный вопрос — какой из них кончится раньше. Дизайн может занимать мало LUT и всё равно не влезть, потому что ему нужно больше DSP, чем есть на чипе. Введите число LUT или выберите один из наших настоящих дизайнов и посмотрите, сколько копий влезет в XC7A200T.",
        "task": "Выберите настоящий дизайн, затем увеличивайте число DSP, пока раньше LUT не кончится что-то другое."
      }
    },
    {
      "id": "hello-t27",
      "n": 7,
      "module": "program",
      "widget": {
        "id": "play-hello-world",
        "kind": "player",
        "title": "hello_world.t27, compiled inside the post",
        "url": "https://t27.ai/play/hello-world/",
        "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&v=7cbe9ab0c960",
        "height": 480
      },
      "also": [
        {
          "id": "play-js",
          "kind": "player",
          "title": "hello_world.t27 to JavaScript, in a terminal inside the post",
          "url": "https://t27.ai/play/hello-world/js/",
          "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=js&v=7cbe9ab0c960",
          "height": 480
        }
      ],
      "spec": {
        "path": "specs/tutorial/02_functions.t27",
        "source": "t27/files/specs/tutorial/02_functions.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F02_functions.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Hello, t27",
        "goal": "What a t27 spec looks like, and what the compiler does with it in your browser.",
        "text": "A t27 program is a spec: a module with typed constants, functions and tests. Prose lines start with a semicolon at the start of a line. The player below runs the real t27 compiler, built to WebAssembly, inside your browser: it reads hello_world.t27, runs its tests and writes code for seven backends. Nothing is installed and nothing is sent anywhere. Open the tutorial spec under the widget and read it next to the output.",
        "task": "Run the tests in the player, then switch the backend and find the same function in two languages."
      },
      "ru": {
        "title": "Привет, t27",
        "goal": "Как выглядит спека t27 и что с ней делает компилятор прямо в вашем браузере.",
        "text": "Программа на t27 — это спека: модуль с типизированными константами, функциями и тестами. Строки прозы начинаются с точки с запятой в начале строки. Плеер ниже запускает настоящий компилятор t27, собранный в WebAssembly, внутри вашего браузера: он читает hello_world.t27, прогоняет его тесты и пишет код для семи бэкендов. Ничего не устанавливается и ничего никуда не отправляется. Откройте учебную спеку под виджетом и читайте её рядом с выводом.",
        "task": "Запустите тесты в плеере, затем переключите бэкенд и найдите одну и ту же функцию на двух языках."
      }
    },
    {
      "id": "tests-are-the-spec",
      "n": 8,
      "module": "program",
      "widget": {
        "id": "test-waves",
        "kind": "tool",
        "title": "Test waves: a t27 spec's tests, simulated and drawn as waves",
        "url": "https://t27.ai/widgets/test-waves/",
        "preview": "widgets/test-waves/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "vcd-wrapped",
          "kind": "tool",
          "title": "VCD wrapped: your simulation, summed up on one card",
          "url": "https://t27.ai/widgets/vcd-wrapped/",
          "preview": "widgets/vcd-wrapped/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/tutorial/07_tests_invariants_benches.t27",
        "source": "t27/files/specs/tutorial/07_tests_invariants_benches.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F07_tests_invariants_benches.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Tests are part of the spec",
        "goal": "Why every t27 spec carries its own tests, and what a waveform shows.",
        "text": "In t27 a spec is not finished without its claims: test blocks, invariants and benches live in the same file as the code they check, and the compiler refuses a spec with none. A test can also be run as gates in a simulator. The waves below are a real simulation of Verilog generated from a ternary multiply-accumulate spec, driven by that spec's own test vectors.",
        "task": "Zoom into one clock cycle and read the values on the buses at a pass mark."
      },
      "ru": {
        "title": "Тесты — часть спеки",
        "goal": "Почему каждая спека t27 несёт свои тесты и что показывает временная диаграмма.",
        "text": "В t27 спека не закончена без своих утверждений: блоки test, инварианты и бенчи живут в том же файле, что и проверяемый ими код, а спеку без них компилятор отвергает. Тест можно запустить и как вентили в симуляторе. Диаграммы ниже — настоящая симуляция Verilog, сгенерированного из спеки троичного умножения с накоплением, на тестовых векторах этой же спеки.",
        "task": "Приблизьте один такт и прочитайте значения на шинах в отметке pass."
      }
    },
    {
      "id": "compiles-is-not-correct",
      "n": 9,
      "module": "program",
      "widget": {
        "id": "t27-tri-misread",
        "kind": "cast",
        "title": "tri misread: code that compiles and is wrong",
        "url": "https://t27.ai/term/t27-tri-misread/",
        "preview": "term/t27-tri-misread/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "tri-x7-mutate",
          "kind": "cast",
          "title": "tri x7-mutate · plant a bug, the tests must catch it",
          "url": "https://t27.ai/term/tri-x7-mutate/",
          "preview": "term/tri-x7-mutate/index.html",
          "height": 640
        },
        {
          "id": "test-touch",
          "kind": "tool",
          "title": "Did the agent touch its own tests? Every PR merged on t27, checked",
          "url": "https://t27.ai/widgets/test-touch/",
          "preview": "widgets/test-touch/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/tutorial/03_operators.t27",
        "source": "t27/files/specs/tutorial/03_operators.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F03_operators.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Compiles is not the same as correct",
        "goal": "Why green checks are not proof, and how to catch code that compiles and is wrong.",
        "text": "A compiler that accepts your code only tells you the code is well formed. It does not tell you the code means what you meant. This recording shows a tool that found specs which compile, pass every gate and are still read wrongly. The lesson for hardware is sharper still: a bug in silicon cannot be patched. Plant a bug yourself in the mutation recording and watch the tests catch it.",
        "task": "Open the mutation recording under Also try and count how many planted bugs the tests caught."
      },
      "ru": {
        "title": "Компилируется — не значит верно",
        "goal": "Почему зелёные галочки — не доказательство и как поймать код, который компилируется и неверен.",
        "text": "Компилятор, принявший ваш код, говорит только, что код правильно оформлен. Он не говорит, что код значит то, что вы имели в виду. Эта запись показывает инструмент, нашедший спеки, которые компилируются, проходят все проверки и всё равно прочитаны неправильно. Для железа урок ещё жёстче: ошибку в кремнии не исправить патчем. Внесите ошибку сами в записи с мутациями и посмотрите, как тесты её ловят.",
        "task": "Откройте запись с мутациями в «Ещё попробуйте» и посчитайте, сколько подложенных ошибок поймали тесты."
      }
    },
    {
      "id": "compiler-stages",
      "n": 10,
      "module": "compiler",
      "widget": {
        "id": "t27c-stages",
        "kind": "tool",
        "title": "Inside t27c: watch a compiler read your code, stage by stage",
        "url": "https://t27.ai/widgets/t27c-stages/",
        "preview": "widgets/t27c-stages/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": {
        "path": "specs/tutorial/06_structs_enums_switch.t27",
        "source": "t27/files/specs/tutorial/06_structs_enums_switch.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F06_structs_enums_switch.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "The stages of t27c",
        "goal": "The path a spec takes inside t27c: tokens, syntax tree, types, HIR, code.",
        "text": "t27c reads a spec in stages. The lexer cuts the text into tokens. The parser builds a syntax tree. The type checker checks every width and every call. The tree is lowered to HIR, a simpler form, and each backend writes code from it. This widget runs those stages on a spec in your browser and shows what each one produced, so an error has a stage you can point at.",
        "task": "Pick an example and step through the stages; find the stage where a type error would stop."
      },
      "ru": {
        "title": "Стадии t27c",
        "goal": "Путь спеки внутри t27c: токены, синтаксическое дерево, типы, HIR, код.",
        "text": "t27c читает спеку по стадиям. Лексер режет текст на токены. Парсер строит синтаксическое дерево. Проверка типов проверяет каждую ширину и каждый вызов. Дерево опускается в HIR, более простую форму, и каждый бэкенд пишет код из неё. Этот виджет прогоняет стадии на спеке в вашем браузере и показывает, что выдала каждая, так что у ошибки есть стадия, на которую можно указать.",
        "task": "Выберите пример и пройдите по стадиям; найдите стадию, на которой остановилась бы ошибка типов."
      }
    },
    {
      "id": "t27c-on-a-real-machine",
      "n": 11,
      "module": "compiler",
      "widget": {
        "id": "t27c-hello-world",
        "kind": "cast",
        "title": "t27c on hello_world.t27",
        "url": "https://t27.ai/term/t27c-hello-world/",
        "preview": "term/t27c-hello-world/index.html",
        "height": 640
      },
      "also": [],
      "spec": {
        "path": "specs/demos/hello_world.t27",
        "source": "t27/files/specs/demos/hello_world.t27",
        "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "t27c on a real machine",
        "goal": "The same compiler on a real machine, printing what it really prints.",
        "text": "The player in lesson 7 runs the compiler in your browser. This recording is the native t27c, written in Rust, run on a real machine on the same hello_world.t27: it reports the spec's status, the tests and invariants it emits, and the Verilog module with its parameters. Every byte in the recording was printed by the command; only the typing is staged.",
        "task": "Find the line where t27c prints the Verilog module's parameters."
      },
      "ru": {
        "title": "t27c на настоящей машине",
        "goal": "Тот же компилятор на настоящей машине, печатающий то, что он действительно печатает.",
        "text": "Плеер в уроке 7 запускает компилятор в вашем браузере. Эта запись — нативный t27c, написанный на Rust, запущенный на настоящей машине на том же hello_world.t27: он сообщает статус спеки, тесты и инварианты, которые выпускает, и модуль Verilog с параметрами. Каждый байт записи напечатала команда; инсценирован только набор текста.",
        "task": "Найдите строку, где t27c печатает параметры модуля Verilog."
      }
    },
    {
      "id": "seven-backends-and-t27b",
      "n": 12,
      "module": "compiler",
      "widget": {
        "id": "play-rust",
        "kind": "player",
        "title": "hello_world.t27 to Rust, in a terminal inside the post",
        "url": "https://t27.ai/play/hello-world/rust/",
        "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=rust&v=7cbe9ab0c960",
        "height": 480
      },
      "also": [
        {
          "id": "play-js",
          "kind": "player",
          "title": "hello_world.t27 to JavaScript, in a terminal inside the post",
          "url": "https://t27.ai/play/hello-world/js/",
          "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=js&v=7cbe9ab0c960",
          "height": 480
        }
      ],
      "spec": {
        "path": "specs/tutorial/08_modules_and_arrays.t27",
        "source": "t27/files/specs/tutorial/08_modules_and_arrays.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F08_modules_and_arrays.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Seven backends, and t27b",
        "goal": "One spec, many target languages, and a native compiler with no LLVM.",
        "text": "One t27 spec can become Zig, C, Rust, JavaScript, TypeScript or Verilog; Verilog comes two ways, straight from the spec and through the HIR, which makes seven backends. The player shows the Rust t27c writes for hello_world. t27b is a second compiler: native AArch64 machine code, no LLVM, a JIT for tests and Mach-O object files. It is not finished, and we say how far it is: in run 26c447ad8 it passed 307 of the 449 specs that the reference compiler passes with tests, 68.4%.",
        "task": "Switch the player to JavaScript under Also try, generate the module, and run it."
      },
      "ru": {
        "title": "Семь бэкендов и t27b",
        "goal": "Одна спека, много целевых языков и нативный компилятор без LLVM.",
        "text": "Одна спека t27 может стать Zig, C, Rust, JavaScript, TypeScript или Verilog; Verilog получается двумя путями, прямо из спеки и через HIR, — вот и семь бэкендов. Плеер показывает Rust, который t27c пишет для hello_world. t27b — второй компилятор: нативный машинный код AArch64, без LLVM, JIT для тестов и объектные файлы Mach-O. Он не закончен, и мы говорим, насколько: в запуске 26c447ad8 он прошёл 307 из 449 спек, которые эталонный компилятор проходит с тестами, 68.4%.",
        "task": "Переключите плеер на JavaScript в «Ещё попробуйте», сгенерируйте модуль и запустите его."
      }
    },
    {
      "id": "spec-to-verilog",
      "n": 13,
      "module": "hardware",
      "widget": {
        "id": "play-verilog",
        "kind": "player",
        "title": "hello_world.t27 to Verilog, in a terminal inside the post",
        "url": "https://t27.ai/play/hello-world/verilog/",
        "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=verilog&v=7cbe9ab0c960",
        "height": 480
      },
      "also": [],
      "spec": {
        "path": "specs/ternary/clocked_counter.t27",
        "source": "t27/files/specs/ternary/clocked_counter.t27",
        "preview": "play/embed.html?spec=specs%2Fternary%2Fclocked_counter.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "From a spec to Verilog",
        "goal": "How a t27 function becomes logic, and how a clocked function becomes registers.",
        "text": "Verilog is the text a synthesizer reads to build a circuit. t27c writes it from the spec. A function named on_clock becomes an always block on the clock edge, and every module var becomes a register with a reset. Open clocked_counter.t27 in the player: an 8-bit counter in a few lines, and the Verilog it turns into. Its header records what yosys built from it.",
        "task": "Open clocked_counter.t27 in the player and find the always block in its Verilog tab."
      },
      "ru": {
        "title": "От спеки к Verilog",
        "goal": "Как функция t27 становится логикой, а тактируемая функция — регистрами.",
        "text": "Verilog — это текст, по которому синтезатор строит схему. t27c пишет его из спеки. Функция с именем on_clock становится блоком always по фронту такта, а каждая переменная модуля — регистром со сбросом. Откройте clocked_counter.t27 в плеере: 8-битный счётчик в несколько строк и Verilog, в который он превращается. В его заголовке записано, что из него построил yosys.",
        "task": "Откройте clocked_counter.t27 в плеере и найдите блок always на вкладке Verilog."
      }
    },
    {
      "id": "count-the-cells",
      "n": 14,
      "module": "hardware",
      "widget": {
        "id": "stat-card",
        "kind": "tool",
        "title": "Stat card: your yosys stat -json as a card and a README badge",
        "url": "https://t27.ai/widgets/stat-card/",
        "preview": "widgets/stat-card/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "resource-bars",
          "kind": "tool",
          "title": "Resource bars: LUT, FF, BRAM and DSP used on the XC7A200T",
          "url": "https://t27.ai/widgets/resource-bars/",
          "preview": "widgets/resource-bars/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/tutorial/04_control_flow.t27",
        "source": "t27/files/specs/tutorial/04_control_flow.t27",
        "preview": "play/embed.html?spec=specs%2Ftutorial%2F04_control_flow.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "Count the cells",
        "goal": "How to count what a synthesizer built: LUTs, flip-flops, DSPs, block RAM.",
        "text": "After synthesis, yosys can print what it built as JSON: how many LUTs, flip-flops, DSPs and block RAMs. Those counts are an honest measure of a design before place and route. Paste a stat -json from yosys into the stat card, or open the real sample, and get a card and a README badge that say plainly that they are a synthesis count.",
        "task": "Open the real sample, then read the LUT and FF counts on the card."
      },
      "ru": {
        "title": "Посчитайте ячейки",
        "goal": "Как посчитать, что построил синтезатор: LUT, триггеры, DSP, блочную память.",
        "text": "После синтеза yosys может напечатать построенное в JSON: сколько LUT, триггеров, DSP и блоков памяти. Эти числа — честная мера дизайна до размещения и трассировки. Вставьте stat -json из yosys в карточку или откройте настоящий пример и получите карточку и бейдж для README, которые прямо говорят, что это подсчёт синтеза.",
        "task": "Откройте настоящий пример и прочитайте на карточке число LUT и FF."
      }
    },
    {
      "id": "one-lut-up-close",
      "n": 15,
      "module": "hardware",
      "widget": {
        "id": "lut-explain",
        "kind": "tool",
        "title": "LUT explain: a 7-series LUT6 INIT and its FASM line, read as logic",
        "url": "https://t27.ai/widgets/lut-explain/",
        "preview": "widgets/lut-explain/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "One LUT, up close",
        "goal": "What a 6-input lookup table is, and how 64 bits describe any gate.",
        "text": "A LUT6 is a tiny memory with 6 address inputs and 64 one-bit entries. Any logic function of 6 inputs is just its truth table written into those 64 bits, the INIT value. Paste an INIT and the widget reads it back as a truth table and an expression. Then play the guessing game on LUTs taken from a real routed design: XOR, AND, a multiplexer, or something with no short name.",
        "task": "Try the XOR6 and majority examples, then play five rounds of Guess the gate."
      },
      "ru": {
        "title": "Одна LUT вблизи",
        "goal": "Что такое таблица истинности на 6 входов и как 64 бита описывают любой вентиль.",
        "text": "LUT6 — это крошечная память с 6 адресными входами и 64 однобитными ячейками. Любая логическая функция от 6 входов — это просто её таблица истинности, записанная в эти 64 бита, значение INIT. Вставьте INIT, и виджет прочитает его обратно как таблицу истинности и выражение. Потом сыграйте в угадайку на LUT из настоящего оттрассированного дизайна: XOR, AND, мультиплексор или что-то без короткого имени.",
        "task": "Попробуйте примеры XOR6 и majority, затем сыграйте пять раундов Guess the gate."
      }
    },
    {
      "id": "synthesis-warnings",
      "n": 16,
      "module": "synthesis",
      "widget": {
        "id": "synth-smells",
        "kind": "tool",
        "title": "Synth smells: a lint card for your yosys log",
        "url": "https://t27.ai/widgets/synth-smells/",
        "preview": "widgets/synth-smells/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "Synthesis warnings that matter",
        "goal": "How to read a yosys log, and the warnings that become bugs on silicon.",
        "text": "yosys tells you a lot, and most of it is fine. A few lines are not: a latch you did not mean, a wire nothing drives, two drivers on one net, a memory that became flip-flops. Each of those works in simulation and fails on the chip. Open one of the real logs from t27 specs, then paste a log of your own.",
        "task": "Open each real log and find the one that yosys refused, and why."
      },
      "ru": {
        "title": "Важные предупреждения синтеза",
        "goal": "Как читать лог yosys и какие предупреждения становятся ошибками на кремнии.",
        "text": "yosys сообщает много, и почти всё это нормально. Несколько строк — нет: защёлка, которую вы не задумывали, провод, который никто не ведёт, два драйвера на одной цепи, память, ставшая триггерами. Всё это работает в симуляции и ломается на чипе. Откройте один из настоящих логов спек t27, затем вставьте свой.",
        "task": "Откройте каждый настоящий лог и найдите тот, который yosys отверг, и почему."
      }
    },
    {
      "id": "state-machines",
      "n": 17,
      "module": "synthesis",
      "widget": {
        "id": "fsm-sketch",
        "kind": "tool",
        "title": "FSM sketch: the state machine yosys found in your RTL",
        "url": "https://t27.ai/widgets/fsm-sketch/",
        "preview": "widgets/fsm-sketch/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "State machines",
        "goal": "How a synthesizer finds a state machine in your design, or refuses to.",
        "text": "Many designs are state machines: a register that holds the current state and logic that picks the next one. yosys looks for them and, when it finds one, can re-encode it. When it refuses, it says why. The widget draws the graph yosys extracted from real designs, a UART receiver and a SPI flash master, and shows a case it refused.",
        "task": "Open the uart_rx sample and count its states and transitions."
      },
      "ru": {
        "title": "Конечные автоматы",
        "goal": "Как синтезатор находит в дизайне конечный автомат — или отказывается.",
        "text": "Многие дизайны — конечные автоматы: регистр хранит текущее состояние, а логика выбирает следующее. yosys ищет их и, найдя, может перекодировать. Когда он отказывается, он говорит почему. Виджет рисует граф, который yosys извлёк из настоящих дизайнов, приёмника UART и мастера SPI flash, и показывает случай, где он отказался.",
        "task": "Откройте пример uart_rx и посчитайте его состояния и переходы."
      }
    },
    {
      "id": "where-the-luts-go",
      "n": 18,
      "module": "synthesis",
      "widget": {
        "id": "lut-treemap",
        "kind": "tool",
        "title": "LUT treemap: which submodule eats your LUTs, from yosys stat -json",
        "url": "https://t27.ai/widgets/lut-treemap/",
        "preview": "widgets/lut-treemap/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "Where the LUTs go",
        "goal": "Which part of a design spends the LUTs, and why hierarchy matters.",
        "text": "A design is built from modules that contain modules. When yosys keeps the hierarchy, it counts each submodule once, and the instance counts tell you how many copies there are. The treemap multiplies them out and shows which submodule eats the LUTs. One adder used many times can cost more than everything else together.",
        "task": "Switch between the hierarchical and flattened totals and find the largest tile."
      },
      "ru": {
        "title": "Куда уходят LUT",
        "goal": "Какая часть дизайна тратит LUT и почему важна иерархия.",
        "text": "Дизайн собран из модулей, внутри которых модули. Когда yosys сохраняет иерархию, он считает каждый подмодуль один раз, а число экземпляров говорит, сколько копий. Treemap перемножает их и показывает, какой подмодуль съедает LUT. Один сумматор, использованный много раз, может стоить больше всего остального вместе.",
        "task": "Переключайтесь между иерархическим и плоским итогом и найдите самый большой прямоугольник."
      }
    },
    {
      "id": "placement",
      "n": 19,
      "module": "timing",
      "widget": {
        "id": "placement-map",
        "kind": "tool",
        "title": "Placement map: where nextpnr put every cell on the XC7A200T",
        "url": "https://t27.ai/widgets/placement-map/",
        "preview": "widgets/placement-map/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "resource-bars",
          "kind": "tool",
          "title": "Resource bars: LUT, FF, BRAM and DSP used on the XC7A200T",
          "url": "https://t27.ai/widgets/resource-bars/",
          "preview": "widgets/resource-bars/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Placement: where the cells land",
        "goal": "What place and route does, and where it put a real design.",
        "text": "Synthesis says which cells you need. Place and route decides where each one sits on the die and which wires connect them. nextpnr-xilinx does both in the open flow. The map draws every placed cell of a real run on the XC7A200T: a small design is a small cluster in a huge chip.",
        "task": "Fit the design, then tap cells of different types and read their BEL names."
      },
      "ru": {
        "title": "Размещение: где оказываются ячейки",
        "goal": "Что делают размещение и трассировка и куда они поставили настоящий дизайн.",
        "text": "Синтез говорит, какие ячейки нужны. Размещение и трассировка решают, где каждая сидит на кристалле и какие провода их соединяют. В открытом маршруте обе задачи решает nextpnr-xilinx. Карта рисует каждую размещённую ячейку настоящего запуска на XC7A200T: маленький дизайн — маленькое скопление на огромном чипе.",
        "task": "Подгоните дизайн по размеру, затем нажимайте на ячейки разных типов и читайте их имена BEL."
      }
    },
    {
      "id": "logic-depth",
      "n": 20,
      "module": "timing",
      "widget": {
        "id": "lut-depth",
        "kind": "tool",
        "title": "LUT depth: your longest yosys path, drawn as a staircase",
        "url": "https://t27.ai/widgets/lut-depth/",
        "preview": "widgets/lut-depth/index.html?embed=1",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "Logic depth",
        "goal": "Why the longest chain of logic sets how fast a design can run.",
        "text": "A signal needs time to pass through each LUT and each wire. The longest chain of logic between two registers sets how fast the clock can tick. yosys can show that chain as a count of cells, before any routing. The staircase draws it for a real GF16 adder, step by step.",
        "task": "Open the real sample and count how many steps of the path are LUTs."
      },
      "ru": {
        "title": "Глубина логики",
        "goal": "Почему самая длинная цепочка логики задаёт, насколько быстро может работать дизайн.",
        "text": "Сигналу нужно время, чтобы пройти каждую LUT и каждый провод. Самая длинная цепочка логики между двумя регистрами задаёт, как часто может тикать такт. yosys может показать эту цепочку как число ячеек ещё до трассировки. Лестница рисует её для настоящего сумматора GF16, шаг за шагом.",
        "task": "Откройте настоящий пример и посчитайте, сколько шагов пути — это LUT."
      }
    },
    {
      "id": "timing-slack",
      "n": 21,
      "module": "timing",
      "widget": {
        "id": "slack-waterfall",
        "kind": "tool",
        "title": "Slack waterfall: every timing path of a routed design, worst first",
        "url": "https://t27.ai/widgets/slack-waterfall/",
        "preview": "widgets/slack-waterfall/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "tri-fpga-rgmii",
          "kind": "cast",
          "title": "tri fpga-txhold · RGMII margins from nextpnr's own SDF",
          "url": "https://t27.ai/term/tri-fpga-rgmii/",
          "preview": "term/tri-fpga-rgmii/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Timing and slack",
        "goal": "What slack is, and how to read a timing report path by path.",
        "text": "Slack is how much time is left on a path when the clock period ends. Positive slack: the path is fast enough. Negative: the design fails at that clock. Each bar here is a real path from a routed design at 50 MHz, split into logic and routing, worst first. Find where the time goes on the worst path.",
        "task": "Click the worst path and compare its logic time with its routing time."
      },
      "ru": {
        "title": "Тайминг и запас",
        "goal": "Что такое slack и как читать отчёт о тайминге путь за путём.",
        "text": "Slack — сколько времени остаётся на пути, когда кончается период такта. Положительный запас: путь достаточно быстрый. Отрицательный: на этой частоте дизайн не работает. Каждая полоса здесь — настоящий путь оттрассированного дизайна на 50 МГц, разбитый на логику и трассировку, худшие сверху. Найдите, куда уходит время на худшем пути.",
        "task": "Нажмите на худший путь и сравните время логики со временем трассировки."
      }
    },
    {
      "id": "fasm-to-frames",
      "n": 22,
      "module": "bitstream",
      "widget": {
        "id": "tri-x7-fasm",
        "kind": "cast",
        "title": "tri x7-fasm · a bitstream assembled without Vivado",
        "url": "https://t27.ai/term/tri-x7-fasm/",
        "preview": "term/tri-x7-fasm/index.html",
        "height": 640
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "From FASM to frames",
        "goal": "What FASM is, and how features become configuration frames.",
        "text": "After routing, the design is a list of features to switch on, in a text format called FASM: this LUT has this INIT, this wire connects to that one. Tools from prjxray turn features into configuration frames, blocks of bits the chip loads. This recording does that step with t27's own tool and compares every frame with the reference tool: they are byte-identical.",
        "task": "Find where the recording says how many frames matched, out of how many."
      },
      "ru": {
        "title": "От FASM к фреймам",
        "goal": "Что такое FASM и как фичи становятся конфигурационными фреймами.",
        "text": "После трассировки дизайн — это список фич, которые надо включить, в текстовом формате FASM: у этой LUT такой INIT, этот провод соединён с тем. Инструменты prjxray превращают фичи в конфигурационные фреймы, блоки битов, которые загружает чип. Эта запись делает этот шаг собственным инструментом t27 и сравнивает каждый фрейм с эталонным инструментом: они совпадают байт в байт.",
        "task": "Найдите место, где запись говорит, сколько фреймов совпало и из скольких."
      }
    },
    {
      "id": "a-build-receipt",
      "n": 23,
      "module": "bitstream",
      "widget": {
        "id": "build-receipt",
        "kind": "tool",
        "title": "Build receipt: t27 spec to XC7A200T bitstream, no Vivado",
        "url": "https://t27.ai/widgets/build-receipt/",
        "preview": "widgets/build-receipt/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "perf2-loop",
          "kind": "cast",
          "title": "Place and route to a loaded bitstream, timed",
          "url": "https://t27.ai/term/perf2-loop/",
          "preview": "term/perf2-loop/index.html",
          "height": 640
        },
        {
          "id": "devkit-flow",
          "kind": "cast",
          "title": "tri devkit · the FPGA flow, layer by layer",
          "url": "https://t27.ai/term/devkit-flow/",
          "preview": "term/devkit-flow/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "A build, itemised",
        "goal": "Every stage from a spec to a bitstream, with its time, tool and hash.",
        "text": "A whole build from a t27 spec to an Artix-7 bitstream, written out like a shop receipt: each stage, the tool and its version, the time it took, and the sha256 of what it wrote. No Vivado anywhere. When a number on a receipt can be checked, anyone can rebuild it and compare the hash.",
        "task": "Read the receipt: which stage took the longest, and which tool ran it?"
      },
      "ru": {
        "title": "Сборка по пунктам",
        "goal": "Каждая стадия от спеки до битстрима — с временем, инструментом и хешем.",
        "text": "Целая сборка от спеки t27 до битстрима Artix-7, расписанная как чек из магазина: каждая стадия, инструмент и его версия, затраченное время и sha256 того, что она записала. Нигде нет Vivado. Когда число в чеке можно проверить, любой может пересобрать и сравнить хеш.",
        "task": "Прочитайте чек: какая стадия шла дольше всех и какой инструмент её выполнял?"
      }
    },
    {
      "id": "read-a-bitstream",
      "n": 24,
      "module": "bitstream",
      "widget": {
        "id": "bit-autopsy",
        "kind": "tool",
        "title": "Bitstream autopsy: which FPGA a 7-series .bit really targets",
        "url": "https://t27.ai/widgets/bit-autopsy/",
        "preview": "widgets/bit-autopsy/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "perf2-knockouts",
          "kind": "cast",
          "title": "Three PERF2 bits, and one knockout bitstream per bit",
          "url": "https://t27.ai/term/perf2-knockouts/",
          "preview": "term/perf2-knockouts/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Read a bitstream",
        "goal": "What is inside a .bit file, and which chip it was built for.",
        "text": "A .bit file is a header followed by packets: commands to the chip's configuration logic and the frames themselves. One of those commands writes the IDCODE of the chip the file was built for. Drop a .bit into the autopsy and see which chip it asks for. Five bitstreams committed to t27 turn out to target a different part than our bench.",
        "task": "Open the blink_j26 sample and compare the part in its header with the IDCODE it writes."
      },
      "ru": {
        "title": "Читаем битстрим",
        "goal": "Что внутри файла .bit и для какого чипа он собран.",
        "text": "Файл .bit — это заголовок, за которым идут пакеты: команды логике конфигурации чипа и сами фреймы. Одна из этих команд записывает IDCODE чипа, для которого файл собран. Бросьте .bit во вскрытие и увидите, какой чип он просит. Пять битстримов, закоммиченных в t27, оказываются собраны для другой детали, чем наш стенд.",
        "task": "Откройте пример blink_j26 и сравните деталь в его заголовке с IDCODE, который он записывает."
      }
    },
    {
      "id": "jtag-asks-the-chip",
      "n": 25,
      "module": "board",
      "widget": {
        "id": "tri-fpga-jtag",
        "kind": "cast",
        "title": "tri fpga-jtag · which chip answered the cable",
        "url": "https://t27.ai/term/tri-fpga-jtag/",
        "preview": "term/tri-fpga-jtag/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "idcode",
          "kind": "tool",
          "title": "JTAG IDCODE decoder: 32 bits, four fields, one device",
          "url": "https://t27.ai/widgets/idcode/",
          "preview": "widgets/idcode/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "JTAG asks the chip",
        "goal": "How a cable finds the chip on a board and reads its IDCODE.",
        "text": "JTAG is the cable protocol for talking to the chip on a board. Before programming, the tool shifts out the IDCODE of every device on the chain. This recording decodes the codes our bench answers with, and shows what an even code means: no IDCODE at all. Compare it with the decoder from lesson 2.",
        "task": "Find which IDCODE belongs to an XC7A200T and which to an XC7A100T."
      },
      "ru": {
        "title": "JTAG спрашивает чип",
        "goal": "Как кабель находит чип на плате и читает его IDCODE.",
        "text": "JTAG — это протокол кабеля для разговора с чипом на плате. Перед прошивкой инструмент выдвигает IDCODE каждого устройства в цепочке. Эта запись декодирует коды, которыми отвечает наш стенд, и показывает, что значит чётный код: IDCODE нет вовсе. Сравните с декодером из урока 2.",
        "task": "Найдите, какой IDCODE принадлежит XC7A200T, а какой XC7A100T."
      }
    },
    {
      "id": "same-bits-on-the-board",
      "n": 26,
      "module": "board",
      "widget": {
        "id": "x7-board",
        "kind": "cast",
        "title": "A bitstream from t27 specs, run on the AX7203",
        "url": "https://t27.ai/term/x7-board/",
        "preview": "term/x7-board/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "bit-diff",
          "kind": "tool",
          "title": "Bitstream diff: two 7-series .bit files, frame by frame",
          "url": "https://t27.ai/widgets/bit-diff/",
          "preview": "widgets/bit-diff/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "The same bits, on the board",
        "goal": "How to show that a bitstream is byte-identical and that it runs.",
        "text": "The claim most FPGA people doubt: a bitstream built by an open flow from t27 specs, byte-identical to the reference toolchain, and working on a real board. This recording compares the files, loads the bits into the chip's SRAM and counts the receipts the board sends back. Drop two .bit files into bit-diff to check the byte-identical part yourself.",
        "task": "Wait for the receipts count at the end, then try bit-diff under Also try."
      },
      "ru": {
        "title": "Те же биты — на плате",
        "goal": "Как показать, что битстрим совпадает байт в байт и что он работает.",
        "text": "Утверждение, в котором сомневается большинство людей из FPGA: битстрим, собранный открытым маршрутом из спек t27, совпадает байт в байт с эталонным тулчейном и работает на настоящей плате. Эта запись сравнивает файлы, загружает биты в SRAM чипа и считает квитанции, которые присылает плата. Бросьте два файла .bit в bit-diff, чтобы проверить совпадение сами.",
        "task": "Дождитесь счёта квитанций в конце, затем попробуйте bit-diff в «Ещё попробуйте»."
      }
    },
    {
      "id": "capstone",
      "n": 27,
      "module": "board",
      "widget": {
        "id": "gatle",
        "kind": "tool",
        "title": "Gatle: guess how many LUTs yosys spends on today's t27 module",
        "url": "https://t27.ai/widgets/gatle/",
        "preview": "widgets/gatle/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "race-the-bee",
          "kind": "tool",
          "title": "Race the bee: who lands patches on t27, a person or a bee",
          "url": "https://t27.ai/widgets/race-the-bee/",
          "preview": "widgets/race-the-bee/index.html?embed=1",
          "height": 640
        },
        {
          "id": "wars",
          "kind": "tab",
          "title": "WARS: agent configurations compared on real GitHub issues",
          "url": "https://t27.ai/#/queen?tab=wars",
          "preview": null,
          "height": 640
        },
        {
          "id": "tri-game-tick",
          "kind": "cast",
          "title": "tri game-tick: one anomaly scan, only what changed",
          "url": "https://t27.ai/term/tri-game-tick/",
          "preview": "term/tri-game-tick/index.html",
          "height": 640
        },
        {
          "id": "tri-game-vault",
          "kind": "cast",
          "title": "tri game-vault: the loop's skills checked against snapshots",
          "url": "https://t27.ai/term/tri-game-vault/",
          "preview": "term/tri-game-vault/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Capstone: out-guess yosys",
        "goal": "Put it together: guess what a real t27 module costs in LUTs.",
        "text": "Everything from this course in one game. Each day Gatle shows one real t27 module and the Verilog your browser compiles from it; you have six guesses at how many LUTs yosys spent on it. Use what you know: widths, multipliers, hierarchy, state. Then look at the other ways people and agents compete on t27.",
        "task": "Play today's puzzle. Then read the module's Verilog and say why it cost what it did."
      },
      "ru": {
        "title": "Итог: переугадайте yosys",
        "goal": "Соберите всё вместе: угадайте, сколько LUT стоит настоящий модуль t27.",
        "text": "Всё из этого курса в одной игре. Каждый день Gatle показывает один настоящий модуль t27 и Verilog, который ваш браузер из него компилирует; у вас шесть попыток угадать, сколько LUT на него потратил yosys. Используйте то, что знаете: ширины, умножители, иерархию, состояние. Потом посмотрите, как ещё люди и агенты соревнуются на t27.",
        "task": "Сыграйте сегодняшнюю задачу. Затем прочитайте Verilog модуля и объясните, почему он стоил столько, сколько стоил."
      }
    },
    {
      "id": "t27-number-format",
      "n": 28,
      "module": "lab",
      "widget": {
        "id": "t27-cell",
        "kind": "tool",
        "title": "T27 cell: 27 seats in 3 trits against FP4's 16 codes in 4 bits",
        "url": "https://t27.ai/widgets/t27-cell/",
        "preview": "widgets/t27-cell/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "gf16-calc",
          "kind": "tool",
          "title": "GF16 calculator: a number as 16 GoldenFloat bits and as ternary",
          "url": "https://t27.ai/widgets/gf16-calc/",
          "preview": "widgets/gf16-calc/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "T27: a number format of our own",
        "goal": "How three trits give more levels than a 4-bit float, and what that costs in plain bits.",
        "text": "A 4-bit float such as E2M1, the element of NVFP4 and MXFP4, has 16 codes, and two of them are zero. Three balanced trits have 3 x 3 x 3 = 27 states. T27 is our format that uses all of them: 27 levels placed where a trained network's weights actually fall, and one shared scale per block of weights. On ternary storage that is more levels in the same room. Packed into plain binary bits it is larger, not smaller, and the widget shows both counts.",
        "task": "Move the weight across the range and find where E2M1 rounds worse than T27; then read the storage table in bits."
      },
      "ru": {
        "title": "T27: наш собственный формат чисел",
        "goal": "Как три трита дают больше уровней, чем 4-битное число с плавающей точкой, и чего это стоит в обычных битах.",
        "text": "У 4-битного числа с плавающей точкой вроде E2M1 — элемента форматов NVFP4 и MXFP4 — 16 кодов, и два из них означают ноль. У трёх сбалансированных тритов 3 x 3 x 3 = 27 состояний. T27 — наш формат, который использует их все: 27 уровней стоят там, где на самом деле лежат веса обученной сети, и один общий масштаб на блок весов. На троичной памяти это больше уровней в том же объёме. Упакованный в обычные двоичные биты, он получается больше, а не меньше, и виджет показывает оба счёта.",
        "task": "Проведите вес по всему диапазону и найдите, где E2M1 округляет хуже, чем T27; затем прочитайте таблицу хранения в битах."
      }
    },
    {
      "id": "an-honest-scoreboard",
      "n": 29,
      "module": "lab",
      "widget": {
        "id": "t27-vs-nvfp4",
        "kind": "tool",
        "title": "T27 vs NVFP4: six weight formats on one small language model",
        "url": "https://t27.ai/widgets/t27-vs-nvfp4/",
        "preview": "widgets/t27-vs-nvfp4/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "t27-cell",
          "kind": "tool",
          "title": "T27 cell: 27 seats in 3 trits against FP4's 16 codes in 4 bits",
          "url": "https://t27.ai/widgets/t27-cell/",
          "preview": "widgets/t27-cell/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "An honest scoreboard",
        "goal": "How T27 was compared with NVFP4, MX+ and MXFP4 on a real language model, and what the result does not show.",
        "text": "A format is judged by what it does to a model. We stored the weights of one small language model in each format and measured perplexity on text it had not seen: lower is better. The rule was written before the run: T27 beats a rival when its perplexity is below 990 thousandths of the rival's. It beat NVFP4, MX+ and MXFP4, and it lost to E2M2, a wider format. The panel under the bars lists what this test cannot claim. The one claim that holds: T27 beats NVFP4 on a ternary substrate.",
        "task": "Find the NVFP4 ratio and the threshold line; then name the format T27 loses to and what it pays for that."
      },
      "ru": {
        "title": "Честная таблица результатов",
        "goal": "Как T27 сравнивали с NVFP4, MX+ и MXFP4 на настоящей языковой модели и чего этот результат не показывает.",
        "text": "Формат судят по тому, что он делает с моделью. Мы сохранили веса одной небольшой языковой модели в каждом формате и измерили перплексию на тексте, которого она не видела: чем ниже, тем точнее модель. Правило записали до запуска: T27 побеждает соперника, если его перплексия ниже 990 тысячных от перплексии соперника. Он победил NVFP4, MX+ и MXFP4 и проиграл E2M2, более широкому формату. Под столбцами — список того, чего этот тест утверждать не может. Утверждение, которое выдерживает проверку, одно: T27 выигрывает у NVFP4 на троичной подложке.",
        "task": "Найдите отношение для NVFP4 и линию порога; затем назовите формат, которому T27 проигрывает, и чем тот платит за это."
      }
    },
    {
      "id": "a-model-on-the-board",
      "n": 30,
      "module": "lab",
      "widget": {
        "id": "uart-bucket",
        "kind": "tool",
        "title": "The bucket under the tap: a 512-byte UART buffer and 19-byte answers",
        "url": "https://t27.ai/widgets/uart-bucket/",
        "preview": "widgets/uart-bucket/index.html?embed=1",
        "height": 640
      },
      "also": [
        {
          "id": "x7-board",
          "kind": "cast",
          "title": "A bitstream from t27 specs, run on the AX7203",
          "url": "https://t27.ai/term/x7-board/",
          "preview": "term/x7-board/index.html",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "A model's tables on the board",
        "goal": "How the host feeds the board over a serial bridge, why the window size matters, and what the board computed.",
        "text": "The board does the arithmetic; the host sends it work over a USB serial bridge. The board's answers wait in the bridge chip's small receive buffer, and when the host keeps more requests in flight than their answers fit, answers are lost. A smaller window removed the loss and did not slow the run. Over that link the board multiplied every ternary weight matrix of a small language model, and every row matched the reference bit for bit. The text itself is generated on the Mac, which does everything except the ternary dot products: the board is the calculator, not the whole model.",
        "task": "Drag the window until the bucket overflows and note the largest window that fits; then compare the two real runs."
      },
      "ru": {
        "title": "Таблицы модели на плате",
        "goal": "Как компьютер кормит плату работой через последовательный мост, почему важен размер окна и что плата посчитала.",
        "text": "Арифметику делает плата; компьютер отправляет ей работу через последовательный USB-мост. Ответы платы ждут в маленьком приёмном буфере микросхемы моста, и если держать в полёте больше запросов, чем помещается их ответов, ответы теряются. Окно поменьше убрало потери и не замедлило прогон. По этой линии плата перемножила все троичные матрицы весов небольшой языковой модели, и каждая строка совпала с эталоном бит в бит. Сам текст генерирует Mac, который делает всё, кроме троичных скалярных произведений: плата — это калькулятор, а не вся модель.",
        "task": "Тяните окно, пока ведро не переполнится, и запомните самое большое окно, которое помещается; затем сравните два настоящих прогона."
      }
    },
    {
      "id": "one-scale-per-block",
      "n": 31,
      "module": "mx",
      "widget": {
        "id": "play-e8m0",
        "kind": "player",
        "title": "e8m0.t27, the OCP MX scale byte, compiled inside the post",
        "url": "https://t27.ai/play/e8m0/",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fe8m0.t27&cast=t27c-e8m0&v=7cbe9ab0c960",
        "height": 480
      },
      "also": [],
      "spec": null,
      "en": {
        "title": "One scale for a block of weights",
        "goal": "Why AI formats share one scale across a block of weights, and how the scale byte of OCP MX is read.",
        "text": "A language model has millions of weights, and a full float for each is expensive to store and to move. The Microscaling (MX) formats of the Open Compute Project keep each weight in 4, 6 or 8 bits and give every block of 32 weights one shared scale. That scale is a single byte called E8M0: no sign and no mantissa, only an exponent, so code e means 2 to the power e minus 127, and code 255 means NaN. The player compiles e8m0.t27, the spec of that byte, in your browser and runs its tests. Where the browser cannot run a check, it skips it and says why.",
        "task": "Run the tests and count the skips; then open the Verilog and find the function that checks for code 255."
      },
      "ru": {
        "title": "Один масштаб на блок весов",
        "goal": "Почему ИИ-форматы делят один масштаб на блок весов и как читается байт масштаба OCP MX.",
        "text": "У языковой модели миллионы весов, и хранить и пересылать полное число с плавающей точкой для каждого дорого. Форматы Microscaling (MX) консорциума Open Compute Project хранят каждый вес в 4, 6 или 8 битах и дают каждому блоку из 32 весов один общий масштаб. Этот масштаб — один байт, E8M0: без знака и без мантиссы, только порядок, так что код e означает 2 в степени e минус 127, а код 255 означает NaN. Плеер компилирует e8m0.t27, спеку этого байта, прямо в вашем браузере и запускает её тесты. Проверку, которую браузер выполнить не может, он пропускает и объясняет почему.",
        "task": "Запустите тесты и посчитайте пропуски; затем откройте Verilog и найдите функцию, которая проверяет код 255."
      }
    },
    {
      "id": "scale-byte-native",
      "n": 32,
      "module": "mx",
      "widget": {
        "id": "t27c-e8m0",
        "kind": "cast",
        "title": "t27c on e8m0.t27 -- the MX shared scale byte, native",
        "url": "https://t27.ai/term/t27c-e8m0/",
        "preview": "term/t27c-e8m0/index.html",
        "height": 640
      },
      "also": [],
      "spec": {
        "path": "specs/numeric/e8m0.t27",
        "source": "t27/files/specs/numeric/e8m0.t27",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fe8m0.t27&tab=term&v=7cbe9ab0c960",
        "height": 480
      },
      "en": {
        "title": "The scale byte on a real machine",
        "goal": "What the native compiler checks in the same spec, including what the browser skipped.",
        "text": "The player in the last lesson could not run every check in e8m0.t27, and it said so. This recording runs the native t27c and Zig on a real machine on the same spec: its constants, the test report, the Zig tests, and the Verilog for the NaN check. Some checks are invariants the compiler proves while it compiles, so compiling is the check. Every byte in the recording was printed by the command; only the typing is staged.",
        "task": "Find how many invariants the test report proved at compile time, and compare its pass count with the player's."
      },
      "ru": {
        "title": "Байт масштаба на настоящей машине",
        "goal": "Что нативный компилятор проверяет в той же спеке, включая то, что браузер пропустил.",
        "text": "Плеер в прошлом уроке не смог выполнить все проверки в e8m0.t27 и прямо об этом сказал. Эта запись запускает нативный t27c и Zig на настоящей машине на той же спеке: её константы, отчёт о тестах, тесты Zig и Verilog для проверки на NaN. Часть проверок — инварианты, которые компилятор доказывает во время компиляции, так что компиляция и есть проверка. Каждый байт в записи напечатала команда; инсценирован только набор текста.",
        "task": "Найдите, сколько инвариантов отчёт доказал во время компиляции, и сравните число пройденных тестов с числом у плеера."
      }
    },
    {
      "id": "one-outlier",
      "n": 33,
      "module": "mx",
      "widget": {
        "id": "t27c-ocp-mx",
        "kind": "cast",
        "title": "t27c on ocp_mx.t27 -- OCP MX v1.0, native",
        "url": "https://t27.ai/term/t27c-ocp-mx/",
        "preview": "term/t27c-ocp-mx/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "t27-vs-nvfp4",
          "kind": "tool",
          "title": "T27 vs NVFP4: six weight formats on one small language model",
          "url": "https://t27.ai/widgets/t27-vs-nvfp4/",
          "preview": "widgets/t27-vs-nvfp4/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "One outlier, many zeros",
        "goal": "What a shared scale costs: how one large weight pushes the small weights of its block to zero, format by format.",
        "text": "A shared scale is set by the largest value in its block, so one outlier sets it for all 32 weights. Weights much smaller than the outlier then fall below the smallest step the element can show and are stored as zero. This recording runs ocp_mx.t27, our spec of OCP MX v1.0, natively on a block of 31 small weights and one outlier, and counts how many each element format flushes to zero. Then it plants a bug, one changed exponent bias, and exactly one test fails: a spec that carries its tests catches its own mistakes.",
        "task": "Read which element format flushes the most small weights to zero and which two flush none; then find the test the planted bug breaks."
      },
      "ru": {
        "title": "Один выброс, много нулей",
        "goal": "Чего стоит общий масштаб: как один крупный вес обнуляет мелкие веса своего блока, формат за форматом.",
        "text": "Общий масштаб задаёт самое большое значение в блоке, поэтому один выброс задаёт его для всех 32 весов. Веса, намного меньшие выброса, падают ниже самого мелкого шага, который может показать элемент, и записываются нулём. Эта запись нативно запускает ocp_mx.t27, нашу спеку OCP MX v1.0, на блоке из 31 мелкого веса и одного выброса и считает, сколько весов обнуляет каждый формат элемента. Затем она подкладывает ошибку, одно изменённое смещение порядка, и падает ровно один тест: спека, которая несёт свои тесты, ловит собственные ошибки.",
        "task": "Найдите, какой формат элемента обнуляет больше всего мелких весов, а какие два — ни одного; затем найдите тест, который ломает подложенная ошибка."
      }
    },
    {
      "id": "phi-scaled-ternary",
      "n": 34,
      "module": "ternary",
      "widget": {
        "id": "play-gfternary",
        "kind": "player",
        "title": "gfternary.t27, phi-scaled ternary weights, compiled inside the post",
        "url": "https://t27.ai/play/gfternary/",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fgfternary.t27&cast=t27c-gfternary&v=ded547ceeb2f",
        "height": 480
      },
      "also": [
        {
          "id": "t27-cell",
          "kind": "tool",
          "title": "T27 cell: 27 seats in 3 trits against FP4's 16 codes in 4 bits",
          "url": "https://t27.ai/widgets/t27-cell/",
          "preview": "widgets/t27-cell/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Weights of minus phi, zero and plus phi",
        "goal": "How a ternary weight is stored in 2 bits, what the fourth code is for, and what the spec does not claim about phi.",
        "text": "Ternary networks such as BitNet keep each weight as minus one, zero or plus one times a scale, so a multiply becomes an add, a subtract or nothing. gfternary.t27 fixes that scale at phi, about 1.618, and stores the three values in 2 bits: 00 is zero, 01 is plus phi, 10 is minus phi. Two bits have a fourth code, 11, and the spec folds it to zero instead of leaving it undefined. The spec also says what it does not claim: that a phi scale beats plain integer ternary weights is an open conjecture, and it names the measured gap that would falsify it. The player compiles it in your browser; most checks it cannot run here, and each skip says why.",
        "task": "Run the tests and read why the skips were skipped; then find the code that folds to zero and the line that folds it."
      },
      "ru": {
        "title": "Веса минус фи, ноль и плюс фи",
        "goal": "Как тернарный вес хранится в 2 битах, зачем нужен четвёртый код и чего спека не утверждает о фи.",
        "text": "Тернарные сети вроде BitNet хранят каждый вес как минус единицу, ноль или плюс единицу, умноженные на масштаб, так что умножение превращается в сложение, вычитание или ничего. gfternary.t27 фиксирует этот масштаб равным фи, примерно 1,618, и хранит три значения в 2 битах: 00 — ноль, 01 — плюс фи, 10 — минус фи. У двух битов есть четвёртый код, 11, и спека сворачивает его в ноль, а не оставляет неопределённым. Спека говорит и о том, чего не утверждает: что масштаб фи выигрывает у обычных целых тернарных весов — открытая гипотеза, и она называет измеренный разрыв, который её опроверг бы. Плеер компилирует спеку в вашем браузере; большинство проверок здесь выполнить нельзя, и каждый пропуск объясняет почему.",
        "task": "Запустите тесты и прочитайте, почему пропущенные проверки пропущены; затем найдите код, который сворачивается в ноль, и строку, которая это делает."
      }
    },
    {
      "id": "a-pass-that-checked-nothing",
      "n": 35,
      "module": "ternary",
      "widget": {
        "id": "t27c-gfternary",
        "kind": "cast",
        "title": "t27c on gfternary.t27 -- phi-scaled ternary weights, native",
        "url": "https://t27.ai/term/t27c-gfternary/",
        "preview": "term/t27c-gfternary/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "tri-x7-mutate",
          "kind": "cast",
          "title": "tri x7-mutate · plant a bug, the tests must catch it",
          "url": "https://t27.ai/term/tri-x7-mutate/",
          "preview": "term/tri-x7-mutate/index.html",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/numeric/gfternary.t27",
        "source": "t27/files/specs/numeric/gfternary.t27",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fgfternary.t27&tab=term&v=ded547ceeb2f",
        "height": 480
      },
      "en": {
        "title": "A pass that checked nothing",
        "goal": "What a vacuous pass is, why a green report can hide one, and how a planted bug tells real checks from empty ones.",
        "text": "The native t27c runs all 13 tests of gfternary.t27, and all 13 pass. The same report prints a line most tools never do: 8 of the 13 passed with no runtime assert executed. A vacuous pass is not a lie, but it is not evidence either. The 5 invariants are proved while the spec compiles, and one of them asserts only true, a placeholder. So the recording plants a bug: the reserved code 11 is no longer folded to zero. Exactly one test fails, the one written for that rule. Every byte in the recording was printed by the command; only the typing is staged.",
        "task": "Find the vacuous-pass line and the test the planted bug breaks; then open the spec and find the invariant that asserts only true."
      },
      "ru": {
        "title": "Прогон, который ничего не проверил",
        "goal": "Что такое пустой проход, почему зелёный отчёт может его скрыть и как подложенная ошибка отличает настоящие проверки от пустых.",
        "text": "Нативный t27c запускает все 13 тестов gfternary.t27, и все 13 проходят. Тот же отчёт печатает строку, которой нет у большинства инструментов: 8 из 13 прошли, не выполнив ни одного assert во время работы. Пустой проход — не ложь, но и не доказательство. 5 инвариантов доказываются, пока спека компилируется, и один из них утверждает только true — это заглушка. Поэтому запись подкладывает ошибку: зарезервированный код 11 больше не сворачивается в ноль. Падает ровно один тест — тот, что написан для этого правила. Каждый байт в записи напечатала команда; инсценирован только набор текста.",
        "task": "Найдите строку о пустых проходах и тест, который ломает подложенная ошибка; затем откройте спеку и найдите инвариант, который утверждает только true."
      }
    },
    {
      "id": "five-rules-for-weights",
      "n": 36,
      "module": "ternary",
      "widget": {
        "id": "play-golden-sieve",
        "kind": "player",
        "title": "golden_sieve.t27, the ternary sieve, compiled inside the post",
        "url": "https://t27.ai/play/golden-sieve/",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fgolden_sieve.t27&cast=t27c-golden-sieve&v=ded547ceeb2f",
        "height": 480
      },
      "also": [
        {
          "id": "lut-explain",
          "kind": "tool",
          "title": "LUT explain: a 7-series LUT6 INIT and its FASM line, read as logic",
          "url": "https://t27.ai/widgets/lut-explain/",
          "preview": "widgets/lut-explain/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "Five rules for a weight alphabet",
        "goal": "Which values a ternary weight may take, and how five measured rules leave a single formula.",
        "text": "Which values may a ternary weight take? golden_sieve.t27 answers with five rules, each citing the measurement behind it. The number of values must be a power of three, so no trit is wasted. At most two trits, because a third measured no significant gain. Integers only. Few enough input bits per neuron to fit one 6-input LUT, which the spec calls a trade, not a law. And no DSP or shift-register cells, for which the openXC7 flow wrote a wrong bitstream while every tool said OK. What passes all five is one formula: 3 levels with one trit, or 9 with two. The browser runs all 3 tests and all 8 invariants.",
        "task": "Run the tests; then change MAX_TRITS to 3 in the source and see which two checks fail."
      },
      "ru": {
        "title": "Пять правил для алфавита весов",
        "goal": "Какие значения может принимать тернарный вес и как пять измеренных правил оставляют одну формулу.",
        "text": "Какие значения может принимать тернарный вес? golden_sieve.t27 отвечает пятью правилами, и каждое ссылается на измерение, на котором стоит. Число значений должно быть степенью тройки, чтобы ни один трит не пропадал зря. Не больше двух тритов, потому что третий в измерениях не дал значимого выигрыша. Только целые числа. Входных битов на нейрон столько, чтобы он поместился в одну LUT на 6 входов, — спека называет это компромиссом, а не законом. И никаких ячеек DSP и сдвиговых регистров: для них поток openXC7 записывал неверный битстрим, хотя каждый инструмент говорил OK. Все пять проходит одна формула: 3 уровня с одним тритом или 9 с двумя. Браузер выполняет все 3 теста и все 8 инвариантов.",
        "task": "Запустите тесты; затем поменяйте в исходнике MAX_TRITS на 3 и посмотрите, какие две проверки упадут."
      }
    },
    {
      "id": "blocked-is-not-failed",
      "n": 37,
      "module": "tnf",
      "widget": {
        "id": "t27c-golden-sieve",
        "kind": "cast",
        "title": "t27c on golden_sieve.t27 -- the ternary sieve, native",
        "url": "https://t27.ai/term/t27c-golden-sieve/",
        "preview": "term/t27c-golden-sieve/index.html",
        "height": 640
      },
      "also": [],
      "spec": {
        "path": "specs/numeric/golden_sieve.t27",
        "source": "t27/files/specs/numeric/golden_sieve.t27",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Fgolden_sieve.t27&tab=term&v=ded547ceeb2f",
        "height": 480
      },
      "en": {
        "title": "Blocked is not failed",
        "goal": "Why a rule checked while compiling stops a spec before any test runs, and how that differs from a failing test.",
        "text": "In the browser, setting MAX_TRITS to 3 made two checks fail. The native t27c is stricter: the 8 invariants of golden_sieve.t27 are proved while it compiles, so with a third trit the spec does not compile at all. The report says BLOCKED, and explains that a blocked spec never produced a binary, so it has no test results to count. A rule checked while compiling cannot ship broken. Then the recording plants a different bug: the rule against shift-register cells now always says yes, and exactly one test fails, the one that checks the formula. Every byte in the recording was printed by the command; only the typing is staged.",
        "task": "Find the line that says why a blocked spec has no test results, and the test the second bug breaks."
      },
      "ru": {
        "title": "Заблокирован — не значит провален",
        "goal": "Почему правило, проверяемое при компиляции, останавливает спеку до запуска любого теста и чем это отличается от упавшего теста.",
        "text": "В браузере MAX_TRITS, равный 3, уронил две проверки. Нативный t27c строже: 8 инвариантов golden_sieve.t27 доказываются во время компиляции, поэтому с третьим тритом спека не компилируется вовсе. Отчёт пишет BLOCKED и объясняет, что заблокированная спека так и не дала бинарника, а значит, у неё нет результатов тестов. Правило, проверяемое при компиляции, не может уйти в сборку сломанным. Затем запись подкладывает другую ошибку: правило против ячеек сдвиговых регистров теперь всегда отвечает «да», и падает ровно один тест — тот, что проверяет формулу. Каждый байт в записи напечатала команда; инсценирован только набор текста.",
        "task": "Найдите строку, которая объясняет, почему у заблокированной спеки нет результатов тестов, и тест, который ломает вторая ошибка."
      }
    },
    {
      "id": "four-trit-exponent",
      "n": 38,
      "module": "tnf",
      "widget": {
        "id": "play-tnf17",
        "kind": "player",
        "title": "tnf17.t27, a 17-bit ternary-exponent float, compiled inside the post",
        "url": "https://t27.ai/play/tnf17/",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Ftnf17.t27&cast=t27c-tnf17&v=ded547ceeb2f",
        "height": 480
      },
      "also": [
        {
          "id": "gf16-calc",
          "kind": "tool",
          "title": "GF16 calculator: a number as 16 GoldenFloat bits and as ternary",
          "url": "https://t27.ai/widgets/gf16-calc/",
          "preview": "widgets/gf16-calc/index.html?embed=1",
          "height": 640
        }
      ],
      "spec": null,
      "en": {
        "title": "A float whose exponent is four trits",
        "goal": "How TNF17e packs a sign, a ternary exponent and a mantissa into 17 bits, and why 17 and not 16.",
        "text": "The formula the sieve leaves has a name: TNF, the Ternary Network Float, the subject of our paper under review at Microprocessors and Microsystems. tnf17.t27 implements it: a sign bit, a 7-bit offset and a 9-bit mantissa, worth (-1)^s x (1 + m/512) x 2^(offset - 40). The offset takes 81 values, exactly 3^4, so the exponent is four balanced trits, from -40 to +40. Four trits cost 7 bits on a binary chip, which is why the rung is 17 bits, not 16; the spec records where its source said otherwise. The browser runs 20 of its 44 checks, all 10 invariants among them, and names the cast behind each skip.",
        "task": "Read the reason on one skipped test; then find the invariant that says four trits span 81 values."
      },
      "ru": {
        "title": "Число, у которого порядок — четыре трита",
        "goal": "Как TNF17e упаковывает знак, тернарный порядок и мантиссу в 17 бит и почему 17, а не 16.",
        "text": "У формулы, которую оставляет решето, есть имя: TNF, Ternary Network Float, — тема нашей статьи, которая на рецензии в Microprocessors and Microsystems. tnf17.t27 её реализует: бит знака, 7-битное смещение и 9-битная мантисса, а значение равно (-1)^s x (1 + m/512) x 2^(offset - 40). Смещение принимает 81 значение, ровно 3^4, так что порядок — это четыре сбалансированных трита, от -40 до +40. Четыре трита стоят 7 бит на двоичном чипе, поэтому ступень занимает 17 бит, а не 16; спека записывает, где её источник говорил иначе. Браузер выполняет 20 из 44 проверок, в том числе все 10 инвариантов, и у каждого пропуска называет приведение типа, которое не смог вычислить.",
        "task": "Прочитайте причину у одного пропущенного теста; затем найдите инвариант, который говорит, что четыре трита дают 81 значение."
      }
    },
    {
      "id": "negate-twice",
      "n": 39,
      "module": "tnf",
      "widget": {
        "id": "t27c-tnf17",
        "kind": "cast",
        "title": "t27c on tnf17.t27 -- a 17-bit ternary-exponent float, native",
        "url": "https://t27.ai/term/t27c-tnf17/",
        "preview": "term/t27c-tnf17/index.html",
        "height": 640
      },
      "also": [
        {
          "id": "t27c-ocp-mx",
          "kind": "cast",
          "title": "t27c on ocp_mx.t27 -- OCP MX v1.0, native",
          "url": "https://t27.ai/term/t27c-ocp-mx/",
          "preview": "term/t27c-ocp-mx/index.html",
          "height": 640
        }
      ],
      "spec": {
        "path": "specs/numeric/tnf17.t27",
        "source": "t27/files/specs/numeric/tnf17.t27",
        "preview": "play/embed.html?spec=specs%2Fnumeric%2Ftnf17.t27&tab=term&v=ded547ceeb2f",
        "height": 480
      },
      "en": {
        "title": "Negate twice, get the number back",
        "goal": "How a test of a property catches a one-character bug that a single example misses.",
        "text": "The browser skipped 24 checks of tnf17.t27; the native t27c runs all 34 tests, all pass, and none is vacuous. Negation flips the sign bit with XOR. The recording swaps XOR for OR, a one-character bug. Negating a positive number still looks right, so the test that negates one still passes. But negating a negative number now leaves it negative, so negating twice no longer gives the number back. Exactly one test fails, negate_is_an_involution, the one that states that property. Every byte in the recording was printed by the command; only the typing is staged.",
        "task": "Find how many passes were vacuous; then go back to the player of the previous lesson, change the XOR to OR yourself, and see whether the browser catches it too."
      },
      "ru": {
        "title": "Дважды сменить знак — получить число обратно",
        "goal": "Как тест свойства ловит ошибку в один символ, которую пропускает единичный пример.",
        "text": "Браузер пропустил 24 проверки tnf17.t27; нативный t27c запускает все 34 теста, все проходят, и ни один не пустой. Смена знака переворачивает бит знака через XOR. Запись меняет XOR на OR — ошибка в один символ. Смена знака у положительного числа по-прежнему выглядит верно, поэтому тест, который меняет знак у единицы, всё ещё проходит. Но отрицательное число теперь остаётся отрицательным, и двойная смена знака больше не возвращает исходное число. Падает ровно один тест, negate_is_an_involution, — тот, что формулирует это свойство. Каждый байт в записи напечатала команда; инсценирован только набор текста.",
        "task": "Найдите, сколько проходов были пустыми; затем вернитесь к плееру прошлого урока, сами замените XOR на OR и посмотрите, поймает ли это и браузер."
      }
    }
  ]
} as const

export type Course = typeof COURSE
export type CourseLesson = Course['lessons'][number]
export type CourseFrame = CourseLesson['widget']
