// Generated by `t27c gen-js` from gHashTag/t27 specs/queen/hive.t27
// (blob ec636503bfee2070a04731b30758220ef9e22c0f, PR gHashTag/t27#7821). Do not edit: change the spec and regenerate.
// The functions of the card run as public/t27/queen/hive.wasm (t27c gen-c
// + zig cc wasm32-wasi).

// Generated by `t27c gen-js` from hive.t27. Do not edit.
//
// Every name and every value here comes from that spec. Change the spec and
// regenerate; an edit made here is lost the next time anyone builds.

export const HIVE_KINDS = 10;
export const CELL_PLACED = 0;
export const CELL_PENDING = 1;
export const CELL_NONE = 2;
export const SM_PARK = 0;
export const SM_ORBIT = 1;
export const SM_HOVER = 2;
export const SM_PORTAL = 3;
export const SM_HOME = 4;
// t27c gen-js: fn ship_mode was not emitted -- this backend lowers declarations, not bodies.
export const DEPART_MS = 2400;
// t27c gen-js: fn ship_kept was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: fn ship_alpha was not emitted -- this backend lowers declarations, not bodies.
export const FX_NONE = 0;
export const FX_START = 1;
export const FX_ACCEPT = 2;
export const FX_SEND_BACK = 3;
export const FX_LOST = 4;
export const FX_CANCEL = 5;
export const FX_OF_KIND = [1, 0, 0, 4, 0, 2, 0, 5, 0, 0];
// t27c gen-js: fn cell_effect was not emitted -- this backend lowers declarations, not bodies.
export const FLASH_MS = 1800;
// t27c gen-js: fn flash_alpha was not emitted -- this backend lowers declarations, not bodies.
export const CELL_BATCH_SECONDS = 300;
// t27c gen-js: fn cells_due was not emitted -- this backend lowers declarations, not bodies.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a TestBlock was not emitted -- it is checked by the compiler, not by the artifact.
// t27c gen-js: a InvariantBlock was not emitted -- it is checked by the compiler, not by the artifact.

// Declaration order, which the spec's own laws depend on.
export const __STRUCT_ORDER__ = [];
export const __DECL_ORDER__ = ["HIVE_KINDS", "CELL_PLACED", "CELL_PENDING", "CELL_NONE", "SM_PARK", "SM_ORBIT", "SM_HOVER", "SM_PORTAL", "SM_HOME", "DEPART_MS", "FX_NONE", "FX_START", "FX_ACCEPT", "FX_SEND_BACK", "FX_LOST", "FX_CANCEL", "FX_OF_KIND", "FLASH_MS", "CELL_BATCH_SECONDS"];

// What this spec holds and this backend did not print. Empty is the whole
// story most of the time; an entry here is a promise the artifact does not
// keep, and reading it is how a tool tells a partial module from a complete
// one without parsing comments.
//
// A LIST, not a map keyed by name. `specs/numeric/formats.t27` declares four
// separate consts called `result`, one per test block, and under an object
// literal three of the four omissions vanished into the fourth -- a record of
// what went missing that itself went missing. A spec is free to reuse a
// name; this file is not free to lose the second one.
export const __NOT_EMITTED__ = Object.freeze([]);
