// GENERATED by scripts/widgets-from-spec.mjs from specs/widgets/gallery.t27
// spec sha256 c2c248baf0149636bbc6aadd0bd29a7a189729771d6ba7eb5e5a0d89aaffd3b2
// Do not edit: change the .t27 source and regenerate.

export const QUEEN_WIDGETS = {
  "source": {
    "spec": "specs/widgets/gallery.t27",
    "publicSpec": "public/widgets/gallery.t27",
    "sha256": "c2c248baf0149636bbc6aadd0bd29a7a189729771d6ba7eb5e5a0d89aaffd3b2",
    "schemaVersion": 1
  },
  "name": "t27 widgets",
  "origin": "https://t27.ai/",
  "handle": "@t27_dev",
  "hashtags": [
    "t27",
    "FPGA",
    "opensource"
  ],
  "postsNothing": true,
  "embed": {
    "width": 640,
    "playerHeight": 360,
    "castHeight": 460
  },
  "categories": [
    {
      "id": "fpga",
      "name": "FPGA bench",
      "line": "Bitstreams, timing, JTAG and pins, recorded on the bench as the commands ran."
    },
    {
      "id": "compiler",
      "name": "Compiler",
      "line": "One spec, seven backends, compiled in the reader's browser by the same WebAssembly compiler."
    },
    {
      "id": "game",
      "name": "Agent game",
      "line": "The Queen's loop and the arena where agent configurations are compared on real issues."
    }
  ],
  "widgets": [
    {
      "id": "x7-board",
      "kind": "cast",
      "category": "fpga",
      "hook": "The bitstream is byte-identical to openXC7's and runs on a real board: the claim most FPGA people doubt, shown.",
      "title": "A bitstream from t27 specs, run on the AX7203",
      "line": "Byte-identical to openXC7's .bit, loaded into SRAM, 51,840 of 51,840 tagged receipts on the board.",
      "url": "https://t27.ai/term/x7-board/",
      "view": null,
      "image": "https://t27.ai/term/x7-board/card.png",
      "gif": "https://t27.ai/term/x7-board/session.gif",
      "preview": "term/x7-board/index.html",
      "commands": [
        "tri x7-board compare --ref",
        "tri x7-board load x7-board-gif3-load --owner-yes 'check it on the board!! this matters!'",
        "tri x7-board receipts x7-board-gif3 --quick"
      ],
      "recorded": "2026-10-02 20:34 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/x7-board/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"A bitstream from t27 specs, run on the AX7203\"></iframe>",
      "markdown": "[![A bitstream from t27 specs, run on the AX7203](https://t27.ai/term/x7-board/session.gif)](https://t27.ai/term/x7-board/)"
    },
    {
      "id": "tri-x7-fasm",
      "kind": "cast",
      "category": "fpga",
      "hook": "A Xilinx 7-series bitstream assembled with no Vivado anywhere in the path.",
      "title": "tri x7-fasm · a bitstream assembled without Vivado",
      "line": "FASM to frames: 22 of 22 byte-identical to fasm2frames, ours 6.31 s in this run (fasm2frames took 150.7 s at corpus build). Frames to .bit: 16 of 16 byte-identical to xc7frames2bit; a wrong-part input is refused.",
      "url": "https://t27.ai/term/tri-x7-fasm/",
      "view": null,
      "image": "https://t27.ai/term/tri-x7-fasm/card.png",
      "gif": "https://t27.ai/term/tri-x7-fasm/session.gif",
      "preview": "term/tri-x7-fasm/index.html",
      "commands": [
        "tri x7-fasm",
        "tri x7-writer"
      ],
      "recorded": "2026-10-03 19:49 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-x7-fasm/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri x7-fasm · a bitstream assembled without Vivado\"></iframe>",
      "markdown": "[![tri x7-fasm · a bitstream assembled without Vivado](https://t27.ai/term/tri-x7-fasm/session.gif)](https://t27.ai/term/tri-x7-fasm/)"
    },
    {
      "id": "tri-x7-mutate",
      "kind": "cast",
      "category": "fpga",
      "hook": "Plant a bug in the bitstream path and watch the tests catch it: mutation testing for hardware.",
      "title": "tri x7-mutate · plant a bug, the tests must catch it",
      "line": "Five planted bugs in packets.t27 (CRC polynomial bit, CRC address width, LFRM no-ops, COR0 bit 0, type-2 word count). Each mutant is rebuilt and re-swept; every one is CAUGHT by its tests and by the sweeps. mutate: all 5 caught.",
      "url": "https://t27.ai/term/tri-x7-mutate/",
      "view": null,
      "image": "https://t27.ai/term/tri-x7-mutate/card.png",
      "gif": "https://t27.ai/term/tri-x7-mutate/session.gif",
      "preview": "term/tri-x7-mutate/index.html",
      "commands": [
        "tri x7-mutate packets.t27"
      ],
      "recorded": "2026-10-04 04:48 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-x7-mutate/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri x7-mutate · plant a bug, the tests must catch it\"></iframe>",
      "markdown": "[![tri x7-mutate · plant a bug, the tests must catch it](https://t27.ai/term/tri-x7-mutate/session.gif)](https://t27.ai/term/tri-x7-mutate/)"
    },
    {
      "id": "perf2-loop",
      "kind": "cast",
      "category": "fpga",
      "hook": "Place and route to a loaded bitstream, with the clock on screen.",
      "title": "Place and route to a loaded bitstream, timed",
      "line": "router1, bitwalk, xc7frames2bit, SRAM load: 19.06 s here, on a laptop at load average ~110.",
      "url": "https://t27.ai/term/perf2-loop/",
      "view": null,
      "image": "https://t27.ai/term/perf2-loop/card.png",
      "gif": "https://t27.ai/term/perf2-loop/session.gif",
      "preview": "term/perf2-loop/index.html",
      "commands": [
        "python3 perf2.py loop --out rec --flash"
      ],
      "recorded": "2026-10-03 19:54 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/perf2-loop/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"Place and route to a loaded bitstream, timed\"></iframe>",
      "markdown": "[![Place and route to a loaded bitstream, timed](https://t27.ai/term/perf2-loop/session.gif)](https://t27.ai/term/perf2-loop/)"
    },
    {
      "id": "tri-fpga-rgmii",
      "kind": "cast",
      "category": "fpga",
      "hook": "RGMII hold margins read from nextpnr's own SDF, not from a datasheet.",
      "title": "tri fpga-txhold · RGMII margins from nextpnr's own SDF",
      "line": "Two recorded model runs (2026-09-27 and 09-28), printed: smallest TX hold 3445 ps on eth_txd[1], smallest RX mid-nibble margin 10900 ps on rxctl_n, both PASS. A model over the routed design's SDF, not a board measurement.",
      "url": "https://t27.ai/term/tri-fpga-rgmii/",
      "view": null,
      "image": "https://t27.ai/term/tri-fpga-rgmii/card.png",
      "gif": "https://t27.ai/term/tri-fpga-rgmii/session.gif",
      "preview": "term/tri-fpga-rgmii/index.html",
      "commands": [
        "tri fpga-txhold",
        "tri fpga-rxcap"
      ],
      "recorded": "2026-10-03 19:49 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-fpga-rgmii/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri fpga-txhold · RGMII margins from nextpnr's own SDF\"></iframe>",
      "markdown": "[![tri fpga-txhold · RGMII margins from nextpnr's own SDF](https://t27.ai/term/tri-fpga-rgmii/session.gif)](https://t27.ai/term/tri-fpga-rgmii/)"
    },
    {
      "id": "tri-fpga-jtag",
      "kind": "cast",
      "category": "fpga",
      "hook": "The cable asks which chip is there and the chip answers with its IDCODE.",
      "title": "tri fpga-jtag · which chip answered the cable",
      "line": "IDCODEs decoded offline: 0x03636093 is an XC7A200T, 0x13631093 an XC7A100T, and an even code is no IDCODE at all (BYPASS or a broken shift). Self-test: 17 of 17 ok.",
      "url": "https://t27.ai/term/tri-fpga-jtag/",
      "view": null,
      "image": "https://t27.ai/term/tri-fpga-jtag/card.png",
      "gif": "https://t27.ai/term/tri-fpga-jtag/session.gif",
      "preview": "term/tri-fpga-jtag/index.html",
      "commands": [
        "tri fpga-jtag --decode 0x03636093",
        "tri fpga-jtag --decode 0x13631093",
        "tri fpga-jtag --decode 0x12345678",
        "tri fpga-jtag --self-test"
      ],
      "recorded": "2026-10-03 19:49 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-fpga-jtag/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri fpga-jtag · which chip answered the cable\"></iframe>",
      "markdown": "[![tri fpga-jtag · which chip answered the cable](https://t27.ai/term/tri-fpga-jtag/session.gif)](https://t27.ai/term/tri-fpga-jtag/)"
    },
    {
      "id": "tri-fpga-pins",
      "kind": "cast",
      "category": "fpga",
      "hook": "Before an edit to a Verilog file: every spec and generator it would touch.",
      "title": "tri fpga-pins · the blast radius of an edit, before the edit",
      "line": "Before editing trinet_node_core.v: 5 specs pin it by sha256 and 5 generators read those specs. radius: 5 specs, 1 level, the exact set fpga-repin walks after the edit.",
      "url": "https://t27.ai/term/tri-fpga-pins/",
      "view": null,
      "image": "https://t27.ai/term/tri-fpga-pins/card.png",
      "gif": "https://t27.ai/term/tri-fpga-pins/session.gif",
      "preview": "term/tri-fpga-pins/index.html",
      "commands": [
        "tri fpga-pins fpga/portable/trinet_node_core.v"
      ],
      "recorded": "2026-10-04 04:52 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-fpga-pins/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri fpga-pins · the blast radius of an edit, before the edit\"></iframe>",
      "markdown": "[![tri fpga-pins · the blast radius of an edit, before the edit](https://t27.ai/term/tri-fpga-pins/session.gif)](https://t27.ai/term/tri-fpga-pins/)"
    },
    {
      "id": "devkit-flow",
      "kind": "cast",
      "category": "fpga",
      "hook": "The whole FPGA flow, one layer per line, from spec to board.",
      "title": "tri devkit · the FPGA flow, layer by layer",
      "line": "One real XC7A200T build: 116.9 s with openXC7, 83.5 s with t27 L3+L4, byte-identical. Place & route is 60%.",
      "url": "https://t27.ai/term/devkit-flow/",
      "view": null,
      "image": "https://t27.ai/term/devkit-flow/card.png",
      "gif": "https://t27.ai/term/devkit-flow/session.gif",
      "preview": "term/devkit-flow/index.html",
      "commands": [
        "tri devkit flow --build --out /tmp/devkit-flow/rec1",
        "tri devkit impact --out /tmp/devkit-flow/rec1 --builds 20"
      ],
      "recorded": "2026-10-03 04:31 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/devkit-flow/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri devkit · the FPGA flow, layer by layer\"></iframe>",
      "markdown": "[![tri devkit · the FPGA flow, layer by layer](https://t27.ai/term/devkit-flow/session.gif)](https://t27.ai/term/devkit-flow/)"
    },
    {
      "id": "play-verilog",
      "kind": "player",
      "category": "fpga",
      "hook": "A spec turned into Verilog inside a post, with the RTL read the way a hardware engineer reads it.",
      "title": "hello_world.t27 to Verilog, in a terminal inside the post",
      "line": "A terminal in your browser running the t27 compiler as WebAssembly: t27c gen verilog prints the Verilog it emits for hello_world.t27, and t27c test runs the spec's tests.",
      "url": "https://t27.ai/play/hello-world/verilog/",
      "view": null,
      "image": "https://t27.ai/play/hello-world/verilog/card.png?v=ac89920ce957",
      "gif": null,
      "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=verilog&v=ded547ceeb2f",
      "commands": [],
      "recorded": null,
      "iframe": "<iframe src=\"https://t27.ai/play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&amp;cast=t27c-hello-world&amp;tab=term&amp;backend=verilog&amp;v=ded547ceeb2f\" width=\"640\" height=\"360\" loading=\"lazy\" style=\"border:0\" allow=\"clipboard-write\" title=\"hello_world.t27 to Verilog, in a terminal inside the post\"></iframe>",
      "markdown": "[![hello_world.t27 to Verilog, in a terminal inside the post](https://t27.ai/play/hello-world/verilog/card.png?v=ac89920ce957)](https://t27.ai/play/hello-world/verilog/)"
    },
    {
      "id": "play-hello-world",
      "kind": "player",
      "category": "compiler",
      "hook": "The t27 compiler running as WebAssembly in a post: compile, test, seven backends.",
      "title": "hello_world.t27, compiled inside the post",
      "line": "The t27 compiler, as WebAssembly, running on one spec in your browser: lexer to seven backends, the spec's own tests, the emitted code, its Verilog read for synthesis, and a terminal.",
      "url": "https://t27.ai/play/hello-world/",
      "view": null,
      "image": "https://t27.ai/play/hello-world/card.png?v=a52d019c491d",
      "gif": null,
      "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&v=ded547ceeb2f",
      "commands": [],
      "recorded": null,
      "iframe": "<iframe src=\"https://t27.ai/play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&amp;cast=t27c-hello-world&amp;v=ded547ceeb2f\" width=\"640\" height=\"360\" loading=\"lazy\" style=\"border:0\" allow=\"clipboard-write\" title=\"hello_world.t27, compiled inside the post\"></iframe>",
      "markdown": "[![hello_world.t27, compiled inside the post](https://t27.ai/play/hello-world/card.png?v=a52d019c491d)](https://t27.ai/play/hello-world/)"
    },
    {
      "id": "play-rust",
      "kind": "player",
      "category": "compiler",
      "hook": "The same spec as Rust, printed by a terminal in the page.",
      "title": "hello_world.t27 to Rust, in a terminal inside the post",
      "line": "A terminal in your browser running the t27 compiler as WebAssembly: t27c gen rust prints the Rust it emits for hello_world.t27, and t27c test runs the spec's tests.",
      "url": "https://t27.ai/play/hello-world/rust/",
      "view": null,
      "image": "https://t27.ai/play/hello-world/rust/card.png?v=a5b20a3b7864",
      "gif": null,
      "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=rust&v=ded547ceeb2f",
      "commands": [],
      "recorded": null,
      "iframe": "<iframe src=\"https://t27.ai/play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&amp;cast=t27c-hello-world&amp;tab=term&amp;backend=rust&amp;v=ded547ceeb2f\" width=\"640\" height=\"360\" loading=\"lazy\" style=\"border:0\" allow=\"clipboard-write\" title=\"hello_world.t27 to Rust, in a terminal inside the post\"></iframe>",
      "markdown": "[![hello_world.t27 to Rust, in a terminal inside the post](https://t27.ai/play/hello-world/rust/card.png?v=a5b20a3b7864)](https://t27.ai/play/hello-world/rust/)"
    },
    {
      "id": "play-js",
      "kind": "player",
      "category": "compiler",
      "hook": "The only backend that runs in the browser: generate the module, then run it.",
      "title": "hello_world.t27 to JavaScript, in a terminal inside the post",
      "line": "A terminal in your browser running the t27 compiler as WebAssembly: t27c gen js prints the JavaScript it emits for hello_world.t27, and t27c test runs the spec's tests.",
      "url": "https://t27.ai/play/hello-world/js/",
      "view": null,
      "image": "https://t27.ai/play/hello-world/js/card.png?v=2c648964eea2",
      "gif": null,
      "preview": "play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&cast=t27c-hello-world&tab=term&backend=js&v=ded547ceeb2f",
      "commands": [],
      "recorded": null,
      "iframe": "<iframe src=\"https://t27.ai/play/embed.html?spec=specs%2Fdemos%2Fhello_world.t27&amp;cast=t27c-hello-world&amp;tab=term&amp;backend=js&amp;v=ded547ceeb2f\" width=\"640\" height=\"360\" loading=\"lazy\" style=\"border:0\" allow=\"clipboard-write\" title=\"hello_world.t27 to JavaScript, in a terminal inside the post\"></iframe>",
      "markdown": "[![hello_world.t27 to JavaScript, in a terminal inside the post](https://t27.ai/play/hello-world/js/card.png?v=2c648964eea2)](https://t27.ai/play/hello-world/js/)"
    },
    {
      "id": "t27c-hello-world",
      "kind": "cast",
      "category": "compiler",
      "hook": "t27c on hello_world.t27, on a real machine, every byte as printed.",
      "title": "t27c on hello_world.t27",
      "line": "t27c 0.4.0 on specs/demos/hello_world.t27: spec-status IMPLEMENTED, the two tests and two invariants the Zig backend emits, and the Verilog module with its parameters.",
      "url": "https://t27.ai/term/t27c-hello-world/",
      "view": null,
      "image": "https://t27.ai/term/t27c-hello-world/card.png",
      "gif": "https://t27.ai/term/t27c-hello-world/session.gif",
      "preview": "term/t27c-hello-world/index.html",
      "commands": [
        "t27c --version",
        "t27c spec-status specs/demos/hello_world.t27",
        "t27c gen specs/demos/hello_world.t27 | sed -n 48,71p",
        "t27c gen-verilog specs/demos/hello_world.t27 | sed -n 10,26p"
      ],
      "recorded": "2026-10-04 06:14 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/t27c-hello-world/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"t27c on hello_world.t27\"></iframe>",
      "markdown": "[![t27c on hello_world.t27](https://t27.ai/term/t27c-hello-world/session.gif)](https://t27.ai/term/t27c-hello-world/)"
    },
    {
      "id": "t27-tri-misread",
      "kind": "cast",
      "category": "compiler",
      "hook": "Code that compiles and is wrong: the tool that finds it.",
      "title": "tri misread: code that compiles and is wrong",
      "line": "1,144 of 1,156 specs generate; 41 spec-shape pairs are read wrongly with every gate green.",
      "url": "https://t27.ai/term/t27-tri-misread/",
      "view": null,
      "image": "https://t27.ai/term/t27-tri-misread/card.png",
      "gif": "https://t27.ai/term/t27-tri-misread/session.gif",
      "preview": "term/t27-tri-misread/index.html",
      "commands": [
        "tri misread"
      ],
      "recorded": "2026-10-03 16:18 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/t27-tri-misread/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri misread: code that compiles and is wrong\"></iframe>",
      "markdown": "[![tri misread: code that compiles and is wrong](https://t27.ai/term/t27-tri-misread/session.gif)](https://t27.ai/term/t27-tri-misread/)"
    },
    {
      "id": "wars",
      "kind": "tab",
      "category": "game",
      "hook": "Pick a lane and see whether the TRI decision layer beats the baseline on the same issue.",
      "title": "WARS: agent configurations compared on real GitHub issues",
      "line": "One issue, one pinned commit, the same tools and gates; only the decision layer changes, and a missing run stays unknown.",
      "url": "https://t27.ai/#/queen?tab=wars",
      "view": "wars",
      "image": null,
      "gif": null,
      "preview": null,
      "commands": [],
      "recorded": null,
      "iframe": "<iframe src=\"https://t27.ai/#/queen?tab=wars&amp;embed=1\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"WARS: agent configurations compared on real GitHub issues\"></iframe>",
      "markdown": "[WARS: agent configurations compared on real GitHub issues](https://t27.ai/#/queen?tab=wars)"
    },
    {
      "id": "tri-game-tick",
      "kind": "cast",
      "category": "game",
      "hook": "One tick of the Queen's loop: an anomaly scan that reports only what changed.",
      "title": "tri game-tick: one anomaly scan, only what changed",
      "line": "25 live checks on t27.ai and its publisher; prints only NEW red or CLEARED rows. This run: 0 red of 25.",
      "url": "https://t27.ai/term/tri-game-tick/",
      "view": null,
      "image": "https://t27.ai/term/tri-game-tick/card.png",
      "gif": "https://t27.ai/term/tri-game-tick/session.gif",
      "preview": "term/tri-game-tick/index.html",
      "commands": [
        "tri game-tick"
      ],
      "recorded": "2026-10-03 13:02 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-game-tick/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri game-tick: one anomaly scan, only what changed\"></iframe>",
      "markdown": "[![tri game-tick: one anomaly scan, only what changed](https://t27.ai/term/tri-game-tick/session.gif)](https://t27.ai/term/tri-game-tick/)"
    },
    {
      "id": "tri-game-vault",
      "kind": "cast",
      "category": "game",
      "hook": "The loop's skills checked against snapshots before an agent may use them.",
      "title": "tri game-vault: the loop's skills checked against snapshots",
      "line": "129 files intact against the newest of 54 content-addressed snapshots.",
      "url": "https://t27.ai/term/tri-game-vault/",
      "view": null,
      "image": "https://t27.ai/term/tri-game-vault/card.png",
      "gif": "https://t27.ai/term/tri-game-vault/session.gif",
      "preview": "term/tri-game-vault/index.html",
      "commands": [
        "tri game-vault --check"
      ],
      "recorded": "2026-10-03 12:59 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/tri-game-vault/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"tri game-vault: the loop's skills checked against snapshots\"></iframe>",
      "markdown": "[![tri game-vault: the loop's skills checked against snapshots](https://t27.ai/term/tri-game-vault/session.gif)](https://t27.ai/term/tri-game-vault/)"
    },
    {
      "id": "perf2-knockouts",
      "kind": "cast",
      "category": "game",
      "hook": "Three performance bits, and one knockout bitstream per bit to prove each one matters.",
      "title": "Three PERF2 bits, and one knockout bitstream per bit",
      "line": "The A/B bitstreams differ in three bits. Each knockout clears one: 3 bytes from the working .bit.",
      "url": "https://t27.ai/term/perf2-knockouts/",
      "view": null,
      "image": "https://t27.ai/term/perf2-knockouts/card.png",
      "gif": "https://t27.ai/term/perf2-knockouts/session.gif",
      "preview": "term/perf2-knockouts/index.html",
      "commands": [
        "python3 perf2.py diff bufr-old.frames bufr-new.frames",
        "python3 perf2.py knockout bufr-new.frames --out rec"
      ],
      "recorded": "2026-10-03 19:53 UTC",
      "iframe": "<iframe src=\"https://t27.ai/term/perf2-knockouts/\" width=\"640\" height=\"460\" loading=\"lazy\" style=\"border:0\" title=\"Three PERF2 bits, and one knockout bitstream per bit\"></iframe>",
      "markdown": "[![Three PERF2 bits, and one knockout bitstream per bit](https://t27.ai/term/perf2-knockouts/session.gif)](https://t27.ai/term/perf2-knockouts/)"
    }
  ],
  "ideas": [
    {
      "id": "placement-map",
      "title": "Placement map",
      "line": "Where nextpnr put each cell of a spec's design on the XC7A200T die, as a picture that can be posted.",
      "source": "nextpnr-xilinx placement output of the bench builds"
    },
    {
      "id": "resource-bars",
      "title": "LUT, FF and BRAM bars",
      "line": "The resources one spec costs, as bars against the part's totals, beside the same design from another language.",
      "source": "synthesis reports of the bench builds"
    },
    {
      "id": "slack-waterfall",
      "title": "Timing slack waterfall",
      "line": "Every path's slack from the SDF, sorted, with the failing ones at the top.",
      "source": "nextpnr SDF, as tri fpga-txhold already reads it"
    },
    {
      "id": "bit-diff",
      "title": "Bitstream diff proof",
      "line": "Two bitstreams compared frame by frame: byte-identical, or the first frame that differs.",
      "source": "tri x7-audit and the x7-board byte-identical comparison"
    },
    {
      "id": "test-waves",
      "title": "Test waveforms",
      "line": "A spec's test block drawn as a timing diagram, the way WaveDrom draws one.",
      "source": "spec test blocks through the in-browser evaluator"
    },
    {
      "id": "gf16-calc",
      "title": "GF16 and ternary calculator",
      "line": "Type a number and see it as GF16 and as balanced ternary, bit by bit, with the format spec it obeys.",
      "source": "FORMAT-SPEC-001.json and gf16.t27"
    },
    {
      "id": "race-the-bee",
      "title": "Race the bee",
      "line": "A real open issue, one human and one bee: whoever lands an accepted patch first takes the lane.",
      "source": "specs/queen/wars.t27 and the bees' run ledger"
    }
  ]
} as const

export type QueenWidgetsGallery = typeof QUEEN_WIDGETS
