// GENERATED by scripts/viewport-from-spec.mjs from public/t27/files/specs/ui/viewport.t27
// spec sha256 91c9235486599fdd18a188c4e191dd6ff7a591a13b01625e766fc70403dd43a4
// Do not edit by hand: change specs/ui/viewport.t27 in gHashTag/t27, re-vendor, re-run the generator.

export type ViewportTier = "phone" | "tablet" | "desktop" | "wide"
/** The tiers, narrowest first. */
export const TIERS_ORDER: readonly ViewportTier[] = ["phone","tablet","desktop","wide"]

/** Inclusive upper bound of the phone tier (CSS px, window.innerWidth). */
export const PHONE_MAX = 600
/** Inclusive upper bound of the tablet tier. */
export const TABLET_MAX = 1024
/** Inclusive upper bound of the desktop tier; wider is "wide". */
export const DESKTOP_MAX = 1600
export const COARSE_POINTER_QUERY = "(pointer: coarse)"
/** Below this width the explorer header drops subtitle and note; inside the desktop tier, not a tier. */
export const HEADER_CHROME_MAX = 1100

/** Smallest interactive box, each side, on phone and tablet. */
export const TOUCH_TARGET_MIN_PX = 44
export const BACK_CONTROL_MIN_PX = 44

export const PHONE_PANES = 1
export const TABLET_PANES = 2
export const DESKTOP_PANES = 2
export const ONE_SCROLLER_PER_PANE = true
export const DOCUMENT_SCROLLS = false

/** The width the desktop layout must stay pixel-identical at across a change. */
export const DESKTOP_REFERENCE_WIDTH = 1280

export interface ViewportSize {
  label: string
  width: number
  height: number
  tier: ViewportTier
  /** Queen rail tiles the one-column rail holds at this height (model, see the spec). */
  railCapacity: number
}

/** The QA matrix every viewport contract iterates. */
export const VIEWPORTS: readonly ViewportSize[] = [
  { label: "390x844", width: 390, height: 844, tier: "phone", railCapacity: 12 },
  { label: "600x900", width: 600, height: 900, tier: "phone", railCapacity: 13 },
  { label: "768x1024", width: 768, height: 1024, tier: "tablet", railCapacity: 16 },
  { label: "1024x768", width: 1024, height: 768, tier: "tablet", railCapacity: 11 },
  { label: "1280x800", width: 1280, height: 800, tier: "desktop", railCapacity: 12 },
  { label: "1920x1080", width: 1920, height: 1080, tier: "wide", railCapacity: 17 },
]

export const RAIL_TILES = 12
export const RAIL_MIN_VISIBLE = 6
export const RAIL_TILE_W_COMPACT = 44
export const RAIL_TILE_H_COMPACT = 74
export const RAIL_TILE_H_COLUMN = 48

/** The tier a CSS viewport width falls into, by the inclusive bounds above. */
export function tierOf(width: number): ViewportTier {
  if (width <= PHONE_MAX) return 'phone'
  if (width <= TABLET_MAX) return 'tablet'
  if (width <= DESKTOP_MAX) return 'desktop'
  return 'wide'
}

/** The media query that is true exactly on the given tier. */
export function tierQuery(tier: ViewportTier): string {
  switch (tier) {
    case 'phone': return `(max-width: ${PHONE_MAX}px)`
    case 'tablet': return `(min-width: ${PHONE_MAX + 1}px) and (max-width: ${TABLET_MAX}px)`
    case 'desktop': return `(min-width: ${TABLET_MAX + 1}px) and (max-width: ${DESKTOP_MAX}px)`
    case 'wide': return `(min-width: ${DESKTOP_MAX + 1}px)`
  }
}
