#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// build-receipt.mjs -- the data of the build-receipt widget (public/widgets/build-receipt/).
//
// One real open-flow build, from a t27 spec to an XC7A200T bitstream, every stage timed:
//   1. gen     t27 -> Verilog: public/t27/files/specs/ternary/stream_ternary_mac.t27 through the
//              vendored compiler public/t27/t27_compiler.wasm in node (the native t27c is not run on
//              this machine: the owner's rule is that t27c runs on the Railway lab);
//   2. synth   yosys synth_xilinx of the generated StreamTernaryMac plus the hand-written board
//              wrapper scripts/widget-data/build-receipt-top.v;
//   3. pnr     nextpnr-xilinx on the xc7a200tfbg676-1 chipdb with scripts/widget-data/build-receipt.xdc;
//   4. frames  prjxray fasm2frames.py (FASM -> .frames), the step tri fpga-build runs;
//   5. bit     prjxray xc7frames2bit (.frames -> .bit), openXC7's bitstream writer;
//   6. sha256  of the .bit, whole file and payload from the sync word.
// Then, outside the total, a cross-check: bitwalk (gHashTag/t27 specs/xilinx7/bitwalk.rs, its
// packets/frames/far modules generated from the .t27 specs by the same wasm compiler's rust target,
// built with rustc) writes a .bit from the same frames; its payload must equal xc7frames2bit's.
//
// Nothing is programmed into a board: no JTAG, no openFPGALoader.
//
// Writes public/widgets/build-receipt/receipt.json and the generated block of
// specs/widgets/build-receipt.t27 (stage times, total, stage count), then re-checks both:
// the stage times must sum to the total within rounding, and the stage count must match the data.
//
//   node scripts/widget-data/build-receipt.mjs run     # build in /tmp/widget-receipt, write data
//   node scripts/widget-data/build-receipt.mjs check   # re-check receipt.json against the spec
import { execFileSync, spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { homedir, loadavg, cpus } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { constsOf, loadCompiler } from '../agents-from-specs.mjs'

const SITE = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const HOME = homedir()
const WORK = '/tmp/widget-receipt/build'
const BW = '/tmp/widget-receipt/bitwalk'
const WASM = 'public/t27/t27_compiler.wasm'
const SPEC = 'public/t27/files/specs/ternary/stream_ternary_mac.t27'
const TOP_V = 'scripts/widget-data/build-receipt-top.v'
const XDC = 'scripts/widget-data/build-receipt.xdc'
const WIDGET_SPEC = 'specs/widgets/build-receipt.t27'
const OUT = 'public/widgets/build-receipt/receipt.json'
const PART = 'xc7a200tfbg676-1'
const TOP = 'build_receipt_top'
const FREQ = '80'
const SEED = '1'
const T27_REPO = process.env.T27_REPO || join(HOME, 't27')
const T27_REF = process.env.T27_REF || 'origin/master'
const TOOLS = {
  yosys: process.env.YOSYS || '/opt/homebrew/bin/yosys',
  nextpnr: process.env.NEXTPNR || join(HOME, '.local/bin/nextpnr-xilinx'),
  python: process.env.PYTHON || '/opt/homebrew/opt/python@3.14/bin/python3.14',
  fasm2frames: process.env.FASM2FRAMES || join(HOME, 'openxc7-src/prjxray/utils/fasm2frames.py'),
  frames2bit: process.env.FRAMES2BIT || join(HOME, 'openxc7-src/prjxray/build/tools/xc7frames2bit'),
  rustc: process.env.RUSTC || 'rustc',
}
const CHIPDB = process.env.CHIPDB || join(HOME, `openxc7-src/chipdb/${PART}.bin`)
const DB_ROOT = process.env.PRJXRAY_DB || join(HOME, '.cache/openxc7/prjxray-db-ab1fc60/artix7')
const STAGE_IDS = ['gen', 'synth', 'pnr', 'frames', 'bit', 'sha256']
const BEGIN = '; --- BEGIN generated by scripts/widget-data/build-receipt.mjs run: do not edit by hand ---'
const END = '; --- END generated ---'

const fail = (m) => { console.error(`build-receipt: ${m}`); process.exit(1) }
const sha256 = (buf) => createHash('sha256').update(buf).digest('hex')
const shaFile = (p) => sha256(readFileSync(p))
const tilde = (s) => s.split(HOME).join('~')
const q = (a) => (/[\s;'"]/.test(a) ? `'${a}'` : a)
const first = (s) => s.split('\n').map((l) => l.trim()).find(Boolean) ?? ''
const out1 = (cmd, args, opts = {}) => { const r = spawnSync(cmd, args, { encoding: 'utf8', ...opts }); return first(`${r.stdout ?? ''}${r.stderr ?? ''}`) }

/** The payload of a .bit: everything from the sync word 0xAA995566 on (the header carries a path and a time). */
export function payloadOf(buf) {
  const at = buf.indexOf(Buffer.from([0xaa, 0x99, 0x55, 0x66]))
  if (at < 0) fail('no sync word in the .bit')
  return { at, bytes: buf.length - at, sha256: sha256(buf.subarray(at)) }
}

/** Run one external stage under /usr/bin/time -l: wall from hrtime, cpu and peak RSS from time(1). */
function external(cmd, args, cwd, logName) {
  const t0 = process.hrtime.bigint()
  const r = spawnSync('/usr/bin/time', ['-l', cmd, ...args], { cwd, encoding: 'utf8', maxBuffer: 1 << 28 })
  const ns = process.hrtime.bigint() - t0
  writeFileSync(join(cwd, logName), `${r.stdout ?? ''}\n--- stderr ---\n${r.stderr ?? ''}`)
  const err = r.stderr ?? ''
  const num = (re) => { const m = re.exec(err); return m ? Number(m[1]) : null }
  return {
    ok: r.status === 0, status: r.status, ns,
    cpu_s: (num(/([\d.]+) user/) ?? 0) + (num(/([\d.]+) sys/) ?? 0),
    rss_mb: (num(/(\d+)\s+maximum resident set size/) ?? 0) / 1048576,
    tail: err.split('\n').filter((l) => /error|ERROR|Error/.test(l)).slice(-3).join(' | '),
  }
}

function inProcess(fn) {
  const c0 = process.cpuUsage()
  const t0 = process.hrtime.bigint()
  let value, ok = true, tail = ''
  try { value = fn() } catch (e) { ok = false; tail = String(e.message ?? e) }
  const ns = process.hrtime.bigint() - t0
  const c = process.cpuUsage(c0)
  return { ok, status: ok ? 0 : 1, ns, cpu_s: (c.user + c.system) / 1e6, rss_mb: process.memoryUsage().rss / 1048576, tail, value }
}

const fileOut = (p) => (existsSync(p) ? { file: p.split('/').pop(), bytes: statSync(p).size, sha256: shaFile(p) } : null)

async function run() {
  for (const [k, p] of Object.entries(TOOLS)) if (k !== 'rustc' && !existsSync(p)) fail(`${k} not found at ${p}`)
  for (const p of [CHIPDB, DB_ROOT, join(SITE, WASM), join(SITE, SPEC)]) if (!existsSync(p)) fail(`missing ${p}`)
  rmSync(WORK, { recursive: true, force: true })
  mkdirSync(WORK, { recursive: true })
  copyFileSync(join(SITE, TOP_V), join(WORK, 'build-receipt-top.v'))
  copyFileSync(join(SITE, XDC), join(WORK, 'build-receipt.xdc'))
  const loadStart = loadavg()
  const started = new Date()
  const wasm = readFileSync(join(SITE, WASM))
  const specSrc = readFileSync(join(SITE, SPEC), 'utf8')

  const vFile = 'stream_ternary_mac.v'
  const synthArgs = ['-q', '-l', 'yosys.log', '-p', `read_verilog ${vFile} build-receipt-top.v; synth_xilinx -flatten -abc9 -arch xc7 -top ${TOP}; write_json synth.json`]
  const pnrArgs = ['--chipdb', CHIPDB, '--xdc', 'build-receipt.xdc', '--json', 'synth.json', '--fasm', 'routed.fasm', '--freq', FREQ, '--seed', SEED, '--log', 'nextpnr.log']
  const framesArgs = [TOOLS.fasm2frames, '--db-root', DB_ROOT, '--part', PART, 'routed.fasm', 'design.frames']
  const bitArgs = ['--part_file', join(DB_ROOT, PART, 'part.yaml'), '--part_name', PART, '--frm_file', 'design.frames', '--output_file', 'build_receipt.bit']

  const plan = [
    { id: 'gen', tool: 't27_compiler.wasm (node)', cmd: `node: t27_analyze(${SPEC.replace(/^public\/t27\/files\//, '')}).targets.verilog > ${vFile}`, out: vFile,
      go: null },
    { id: 'synth', tool: 'yosys', cmd: ['yosys', ...synthArgs].map(q).join(' '), out: 'synth.json', go: () => external(TOOLS.yosys, synthArgs, WORK, 'synth.time') },
    { id: 'pnr', tool: 'nextpnr-xilinx', cmd: ['nextpnr-xilinx', ...pnrArgs].map((a) => q(tilde(a))).join(' '), out: 'routed.fasm', go: () => external(TOOLS.nextpnr, pnrArgs, WORK, 'pnr.time') },
    { id: 'frames', tool: 'fasm2frames.py', cmd: ['python3', ...framesArgs].map((a) => q(tilde(a))).join(' '), out: 'design.frames', go: () => external(TOOLS.python, framesArgs, WORK, 'frames.time') },
    { id: 'bit', tool: 'xc7frames2bit', cmd: ['xc7frames2bit', ...bitArgs].map((a) => q(tilde(a))).join(' '), out: 'build_receipt.bit', go: () => external(TOOLS.frames2bit, bitArgs, WORK, 'bit.time') },
    { id: 'sha256', tool: 'node crypto sha256', cmd: 'shasum -a 256 build_receipt.bit   # and of the bytes from the sync word 0xAA995566 on', out: null, go: null },
  ]
  if (plan.map((s) => s.id).join() !== STAGE_IDS.join()) fail('the stage plan and STAGE_IDS disagree')

  // Stage 1 runs in this process: the compiler is instantiated inside the timed stage (a cold run).
  const stages = []
  let broken = false
  for (const s of plan) {
    if (broken) { stages.push({ id: s.id, tool: s.tool, cmd: s.cmd, status: 'not run' }); continue }
    let r
    if (s.id === 'gen') {
      const c0 = process.cpuUsage()
      const t0 = process.hrtime.bigint()
      let ok = true, tail = ''
      try {
        const analyze = await loadCompiler(wasm)
        const v = analyze(specSrc).targets?.verilog
        if (!v?.ok || !/^module StreamTernaryMac \(/m.test(v.code ?? '')) throw new Error('the verilog target did not generate module StreamTernaryMac')
        writeFileSync(join(WORK, vFile), v.code)
      } catch (e) { ok = false; tail = String(e.message ?? e) }
      const ns = process.hrtime.bigint() - t0
      const c = process.cpuUsage(c0)
      r = { ok, status: ok ? 0 : 1, ns, cpu_s: (c.user + c.system) / 1e6, rss_mb: process.memoryUsage().rss / 1048576, tail }
    } else if (s.id === 'sha256') {
      r = inProcess(() => { const b = readFileSync(join(WORK, 'build_receipt.bit')); return { file: sha256(b), payload: payloadOf(b) } })
    } else {
      r = s.go()
    }
    const o = s.out ? fileOut(join(WORK, s.out)) : null
    const ok = r.ok && (s.out ? Boolean(o) : true)
    stages.push({
      id: s.id, tool: s.tool, cmd: s.cmd, status: ok ? 'ok' : 'failed', exit: r.status,
      ns: Number(r.ns), ms: Math.round(Number(r.ns) / 1e6), cpu_s: Math.round(r.cpu_s * 100) / 100, rss_mb: Math.round(r.rss_mb),
      output: o, error: ok ? undefined : (r.tail || `exit ${r.status}`), value: r.value,
    })
    if (!ok) broken = true
  }
  const finished = new Date()

  // Versions and inputs, read from the tools themselves.
  const nextpnrLog = existsSync(join(WORK, 'nextpnr.log')) ? readFileSync(join(WORK, 'nextpnr.log'), 'utf8') : ''
  const fmax = [...nextpnrLog.matchAll(/Max frequency for clock\s+'([^']+)':\s+([\d.]+) MHz \((PASS|FAIL) at ([\d.]+) MHz\)/g)].pop()
  const util = {}
  for (const m of nextpnrLog.matchAll(/^Info:\s+(SLICE_LUTX|SLICE_FFX|CARRY4|PAD|BUFGCTRL|STARTUPE2):\s+(\d+)\/\s*(\d+)/gm)) util[m[1]] = [Number(m[2]), Number(m[3])]
  const t27Commit = (() => { try { return execFileSync('git', ['-C', T27_REPO, 'rev-parse', T27_REF], { encoding: 'utf8' }).trim() } catch { return null } })()
  const prjxrayCommit = out1('git', ['-C', dirname(dirname(TOOLS.fasm2frames)), 'log', '-1', '--format=%h %cs'])
  // These strings are part of the earlier-runs key: change them and the run history starts over.
  const versions = {
    gen: `t27_compiler.wasm ${wasm.length} B sha256 ${sha256(wasm).slice(0, 16)}`,
    synth: out1(TOOLS.yosys, ['-V']).replace(/^(Yosys \S+) \(git sha1 ([0-9a-f]{10})[0-9a-f]*,.*$/, '$1 $2'),
    pnr: out1(TOOLS.nextpnr, ['--version']).replace(/^"?(nextpnr-xilinx)"?.*\(Version (\S+)\)$/, '$1 $2'),
    frames: `prjxray ${prjxrayCommit}, ${out1(TOOLS.python, ['--version'])}, prjxray-db ab1fc60`,
    bit: `xc7frames2bit, prjxray ${prjxrayCommit}`,
    sha256: `node ${process.version}`,
  }
  for (const s of stages) s.version = versions[s.id]

  // Cross-check outside the total: bitwalk, built from t27 specs, writes the same frames.
  let cross = { status: 'not run' }
  const bitStage = stages.find((s) => s.id === 'bit')
  if (bitStage.status === 'ok' && t27Commit) {
    rmSync(BW, { recursive: true, force: true })
    mkdirSync(BW, { recursive: true })
    const analyze = await loadCompiler(wasm)
    const mods = ['packets', 'frames', 'far', 'flow']
    for (const n of ['bitwalk.rs', ...mods.map((m) => `${m}.t27`)]) writeFileSync(join(BW, n), execFileSync('git', ['-C', T27_REPO, 'show', `${T27_REF}:specs/xilinx7/${n}`]))
    let built = true
    for (const m of mods) {
      const r = analyze(readFileSync(join(BW, `${m}.t27`), 'utf8')).targets?.rust
      if (!r?.ok || !r.code) { built = false; cross = { status: 'failed', error: `${m}.t27: no rust target` }; break }
      writeFileSync(join(BW, `${m}.rs`), r.code)
    }
    if (built) {
      const rc = spawnSync(TOOLS.rustc, ['-O', '--edition', '2021', 'bitwalk.rs', '-o', 'bitwalk'], { cwd: BW, encoding: 'utf8' })
      if (rc.status !== 0) cross = { status: 'failed', error: first(rc.stderr) }
      else {
        const args = ['--write', join(WORK, 'design.frames'), join(WORK, 'bitwalk.bit'), '--part_file', join(DB_ROOT, PART, 'part.yaml'), '--part_name', PART]
        const r = external(join(BW, 'bitwalk'), args, WORK, 'bitwalk.time')
        const ours = r.ok ? payloadOf(readFileSync(join(WORK, 'bitwalk.bit'))) : null
        const theirs = stages.find((s) => s.id === 'sha256').value?.payload
        cross = {
          status: r.ok ? 'ok' : 'failed', ms: Math.round(Number(r.ns) / 1e6),
          tool: `bitwalk (gHashTag/t27 ${t27Commit.slice(0, 9)} specs/xilinx7, rust target of t27_compiler.wasm, ${out1(TOOLS.rustc, ['--version'])})`,
          cmd: ['bitwalk', ...args.map((a) => tilde(a.replace(WORK + '/', '')))].map(q).join(' '),
          payload_sha256: ours?.sha256 ?? null, payload_equal: Boolean(ours && theirs && ours.sha256 === theirs.sha256),
          file_bytes: r.ok ? statSync(join(WORK, 'bitwalk.bit')).size : null,
        }
      }
    }
  }

  const shaStage = stages.find((s) => s.id === 'sha256')
  const digest = shaStage.status === 'ok' ? shaStage.value : null
  for (const s of stages) delete s.value
  // The total is the exact sum of the stage times, rounded once; each stage is rounded on its own.
  const totalMs = Math.round(stages.reduce((a, s) => a + (s.ns ?? 0), 0) / 1e6)
  const receipt = {
    when_utc: started.toISOString().replace(/\.\d+Z$/, 'Z'),
    finished_utc: finished.toISOString().replace(/\.\d+Z$/, 'Z'),
    wall_ms_end_to_end: finished - started,
    machine: { cpu: out1('sysctl', ['-n', 'machdep.cpu.brand_string']), cores: cpus().length, macos: out1('sw_vers', ['-productVersion']), loadavg_1m_at_start: Math.round(loadStart[0] * 10) / 10 },
    design: {
      spec: SPEC.replace(/^public\/t27\/files\//, ''), spec_sha256: sha256(Buffer.from(specSrc, 'utf8')), datapath: 'StreamTernaryMac',
      wrapper: `apps/website/${TOP_V}`, wrapper_sha256: shaFile(join(SITE, TOP_V)), wrapper_lines: readFileSync(join(SITE, TOP_V), 'utf8').trimEnd().split('\n').length,
      xdc: `apps/website/${XDC}`, xdc_sha256: shaFile(join(SITE, XDC)), top: TOP, part: PART, board: 'QMTech Wukong V1 (XC7A200T-FGG676)',
      chipdb: tilde(CHIPDB), chipdb_sha256: shaFile(CHIPDB), freq_mhz: Number(FREQ), seed: Number(SEED),
    },
    stages,
    stage_count: stages.length,
    stages_ok: stages.filter((s) => s.status === 'ok').length,
    total_ms: totalMs,
    complete: stages.every((s) => s.status === 'ok'),
    fmax: fmax ? { clock: fmax[1], mhz: Number(fmax[2]), pass: fmax[3] === 'PASS', target_mhz: Number(fmax[4]) } : null,
    utilisation: util,
    bit: digest ? { file: 'build_receipt.bit', bytes: statSync(join(WORK, 'build_receipt.bit')).size, sha256: digest.file, payload_sha256: digest.payload.sha256, payload_bytes: digest.payload.bytes, sync_at: digest.payload.at } : null,
    cross_check: cross,
    vendor_tools_run: 0,
    programmed: false,
    commands: [
      'cd apps/website && node scripts/widget-data/build-receipt.mjs run',
      `# the stages it runs, in ${WORK}:`,
      ...stages.map((s) => s.cmd),
      ...(cross.cmd ? ['# cross-check, not in the total:', cross.cmd] : []),
    ],
  }
  // Earlier runs of the same inputs with the same tools: does the payload come out the same?
  const prev = existsSync(join(SITE, OUT)) ? JSON.parse(readFileSync(join(SITE, OUT), 'utf8')) : null
  const sameInputs = (o) => o && JSON.stringify(inputsOf(o)) === JSON.stringify(inputsOf(receipt))
  receipt.earlier_runs = sameInputs(prev) ? [...(prev.earlier_runs ?? []), { when_utc: prev.when_utc, total_ms: prev.total_ms, loadavg_1m_at_start: prev.machine.loadavg_1m_at_start, payload_sha256: prev.bit?.payload_sha256 ?? null }].slice(-4) : []
  receipt.payload_same_as_earlier = receipt.earlier_runs.length ? receipt.earlier_runs.every((e) => e.payload_sha256 === receipt.bit?.payload_sha256) : null
  mkdirSync(dirname(join(SITE, OUT)), { recursive: true })
  writeFileSync(join(SITE, OUT), JSON.stringify(receipt, null, 1) + '\n')
  writeSpecBlock(receipt)
  console.log(`build-receipt: ${receipt.stages_ok}/${receipt.stage_count} stages ok, total ${(totalMs / 1000).toFixed(2)} s, end to end ${(receipt.wall_ms_end_to_end / 1000).toFixed(2)} s, load ${receipt.machine.loadavg_1m_at_start}`)
  for (const s of stages) console.log(`  ${s.id.padEnd(7)} ${s.status.padEnd(7)} ${String(s.ms ?? '-').padStart(7)} ms  ${s.version}  ${s.output ? `${s.output.file} ${s.output.bytes} B ${s.output.sha256.slice(0, 12)}` : ''}${s.error ? '  ' + s.error : ''}`)
  console.log(`  cross-check ${cross.status}${cross.payload_equal !== undefined ? ` payload_equal=${cross.payload_equal}` : ''}`)
  await check()
}

/** What a run was given: if two runs agree on this, their payloads may be compared. */
const inputsOf = (r) => ({ d: { ...r.design }, v: r.stages.map((s) => s.version), c: r.stages.map((s) => s.cmd) })

function writeSpecBlock(r) {
  const path = join(SITE, WIDGET_SPEC)
  const src = readFileSync(path, 'utf8')
  const a = src.indexOf(BEGIN), b = src.indexOf(END)
  if (a < 0 || b < a) fail(`${WIDGET_SPEC}: the generated block markers are missing`)
  const ms = r.stages.map((s) => s.ms ?? 0)
  const block = [
    BEGIN,
    `; Run of ${r.when_utc} on ${r.machine.cpu}, ${r.machine.cores} cores, load ${r.machine.loadavg_1m_at_start} at start.`,
    `pub const K_STAGE_COUNT : u8 = ${r.stage_count};`,
    `pub const K_STAGES_OK : u8 = ${r.stages_ok};`,
    `pub const K_STAGE_MS : [${ms.length}]u32 = [${ms.join(', ')}];`,
    `pub const K_TOTAL_MS : u32 = ${r.total_ms};`,
    `pub const K_BIT_BYTES : u32 = ${r.bit?.bytes ?? 0};`,
    `pub const K_VENDOR_TOOLS_RUN : u8 = ${r.vendor_tools_run};`,
    END,
  ].join('\n')
  writeFileSync(path, src.slice(0, a) + block + src.slice(b + END.length))
}

/** Re-check: stage times sum to the total within rounding; the stage count matches the data and the spec. */
export async function check() {
  const r = JSON.parse(readFileSync(join(SITE, OUT), 'utf8'))
  const analyze = await loadCompiler(readFileSync(join(SITE, WASM)))
  const analysis = analyze(readFileSync(join(SITE, WIDGET_SPEC), 'utf8'))
  const k = Object.fromEntries(Object.entries(constsOf(analysis)).map(([n, v]) => [n, v.value]))
  const problems = []
  const ms = r.stages.map((s) => s.ms ?? 0)
  const sum = ms.reduce((a, b) => a + b, 0)
  // Each stage is rounded to the millisecond on its own, the total once: they may differ by half a ms per stage.
  if (Math.abs(sum - r.total_ms) > r.stages.length / 2) problems.push(`stage ms sum ${sum} vs total ${r.total_ms}: more than rounding`)
  const exact = r.stages.reduce((a, s) => a + (s.ns ?? 0), 0)
  if (Math.round(exact / 1e6) !== r.total_ms) problems.push(`total_ms ${r.total_ms} is not the rounded sum of the stage ns ${exact}`)
  if (r.stage_count !== r.stages.length) problems.push(`stage_count ${r.stage_count} vs ${r.stages.length} stages`)
  if (r.stages.map((s) => s.id).join() !== STAGE_IDS.join()) problems.push(`stage ids ${r.stages.map((s) => s.id)} are not ${STAGE_IDS}`)
  if (r.stages_ok !== r.stages.filter((s) => s.status === 'ok').length) problems.push('stages_ok disagrees with the stages')
  if (Number(k.K_STAGE_COUNT) !== r.stages.length) problems.push(`spec K_STAGE_COUNT ${k.K_STAGE_COUNT} vs ${r.stages.length} stages in the data`)
  if (JSON.stringify((k.K_STAGE_MS ?? []).map(Number)) !== JSON.stringify(ms)) problems.push(`spec K_STAGE_MS ${k.K_STAGE_MS} vs data ${ms}`)
  if (Number(k.K_TOTAL_MS) !== r.total_ms) problems.push(`spec K_TOTAL_MS ${k.K_TOTAL_MS} vs data ${r.total_ms}`)
  if ((k.SAY_STAGE_NAMES ?? []).length !== r.stages.length) problems.push(`spec SAY_STAGE_NAMES has ${(k.SAY_STAGE_NAMES ?? []).length} names for ${r.stages.length} stages`)
  // When the build directory is still there, the receipt must describe the files in it.
  for (const s of r.stages) {
    if (!s.output) continue
    const p = join(WORK, s.output.file)
    if (existsSync(p) && shaFile(p) !== s.output.sha256) problems.push(`${s.output.file} in ${WORK} no longer has the receipt's sha256`)
  }
  if (r.complete && r.cross_check?.status === 'ok' && !r.cross_check.payload_equal) problems.push('bitwalk payload differs from xc7frames2bit payload')
  if (problems.length) { for (const p of problems) console.error(`build-receipt check: ${p}`); process.exit(1) }
  console.log(`build-receipt check: ${r.stages.length} stages, sum ${sum} ms, total ${r.total_ms} ms; spec and data agree`)
}

const cmd = process.argv[2]
if (cmd === 'run') await run()
else if (cmd === 'check') await check()
else fail('usage: build-receipt.mjs run | check')
