// Agent Explorer -- the 27 letters of the alphabet, each read from its spec.
//
// Layer four of the ladder: Specs → Skills → Crons → Agents. An agent is a
// letter of docs/agents/AGENTS_ALPHABET.md bound by SOUL.md and AGENTS.md;
// its card is generated by scripts/agents-from-specs.mjs from
// specs/agents/<letter>.t27 through the real compiler, joined to the
// experience snapshot (public/agents/experience.json) by LETTER. Nothing on
// this page is typed twice: the skills an agent holds, the jobs that launch
// them, the counts in the ladder and the episodes it is credited with all come
// from the generated catalog, and an agent with no attributed episode says so.

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useI18n } from '../i18n/context'
import { usePageMeta } from '../hooks/usePageMeta'
import { useHashParams } from '../hooks/useHashParams'
import { ExplorerHeader } from '../components/ExplorerHeader'
import { ExplorerLibrary, type ExplorerItem } from '../components/ExplorerLibrary'
import { AgentSpecPanel } from '../components/AgentSpecPanel'
import { LayerLadder, type LadderStep } from '../components/LayerLadder'
import { loadAgentSpecs, type AgentLayer, type AgentSpecCatalog, type AgentSpecEntry } from '../lib/agentSpecs'
import { skillExplorerHash } from '../lib/skillsCatalog'
import { cronExplorerHash } from '../lib/cronsCatalog'
import { agentExplorerHash, canonicalAgentUrl, resolveAgent } from '../lib/agentsCatalog'
import { C, panelBox, pill, tagChip } from '../lib/explorerTheme'

const UI = {
  en: {
    title: 'Agent Explorer',
    subtitle: 'The 27 letters of the alphabet, each read from its spec',
    metaTitle: 'Agent Explorer',
    metaDescription:
      'The 27 agents of the Trinity alphabet (A…Z and Ti), each generated from a .t27 spec: domain, archetype, the skills it holds, the jobs that launch them, and the experience episodes credited to it.',
    note: 'Generated from specs/agents/*.t27, not typed by hand',
    back: '← Home',
    search: 'Search agents',
    allLayers: 'All layers',
    tags: 'Tags',
    clear: 'Clear',
    agents: 'agents',
    noResults: 'No agent matches',
    noneInGroup: 'None in this group',
    loading: 'loading the catalog…',
    failed: 'Could not load the agent catalog:',
    pickAgent: 'Pick an agent',
    backToLibrary: 'All agents',
    filterAll: 'All',
    filterWithExperience: 'with experience',
    filterSpecOnly: 'spec only',
    ladder: 'ladder',
    ladderSpecs: 'Specs',
    ladderSkills: 'Skills',
    ladderCrons: 'Crons',
    ladderAgents: 'Agents',
    soulLaw: 'SOUL & LAW',
    soulLawHint: 'The three documents that bind every letter, linked at the commit the experience snapshot was taken from.',
    openSoul: 'Open SOUL.md',
    openAgentsDoc: 'Open AGENTS.md',
    openAlphabet: 'Alphabet row',
    pinnedAt: 'pinned at',
    crons: 'CRONS',
    cronsHint: 'Jobs whose RUNS name one of this agent’s skills — derived, not declared.',
    noCrons: 'no job runs this agent’s skills',
    noCronsNoSkills: 'no skills, so no job can run them',
    experience: 'EXPERIENCE',
    episodes: 'episodes',
    firstEpisode: 'first',
    lastEpisode: 'last',
    lastTask: 'last task',
    outcomes: 'outcomes',
    lessons: 'lessons',
    noEpisodes: 'no attributed episodes',
    noEpisodesHint: 'The snapshot names no agent letter in any episode; episodes that name none are counted as unattributed and assigned to nobody.',
    unattributed: 'unattributed in snapshot',
    snapshotFrom: 'snapshot',
    invariants: 'INVARIANTS',
    entry: 'entry',
    exit: 'exit',
    register: 'register',
    archetype: 'archetype',
    layer: 'layer',
    clara: 'CLARA role',
    noClara: 'none',
    keyFiles: 'key files',
    noKeyFiles: 'none listed',
    tools: 'TOOLS',
    noTools: 'none bound yet',
    toolsHint: 'Layer five: the tri CLI and MCP servers an agent should know. Filled by specs/tools; empty until a source binds one.',
    experienceLog: 'Experience log',
    copyLink: 'Copy link',
    copied: 'Copied',
    ordinal: 'ordinal',
    enabledOff: 'reserved',
  },
  ru: {
    title: 'Обозреватель агентов',
    subtitle: '27 букв алфавита, каждая прочитана из своей спеки',
    metaTitle: 'Обозреватель агентов',
    metaDescription:
      '27 агентов алфавита Trinity (A…Z и Ti), каждый сгенерирован из спеки .t27: домен, архетип, скиллы, которые он держит, задания, которые их запускают, и эпизоды опыта, засчитанные ему.',
    note: 'Сгенерировано из specs/agents/*.t27, а не набрано руками',
    back: '← На главную',
    search: 'Поиск агентов',
    allLayers: 'Все слои',
    tags: 'Теги',
    clear: 'Сбросить',
    agents: 'агентов',
    noResults: 'Ни один агент не подходит',
    noneInGroup: 'В этой группе никого',
    loading: 'загружаем каталог…',
    failed: 'Не удалось загрузить каталог агентов:',
    pickAgent: 'Выберите агента',
    backToLibrary: 'Все агенты',
    filterAll: 'Все',
    filterWithExperience: 'с опытом',
    filterSpecOnly: 'только спека',
    ladder: 'лестница',
    ladderSpecs: 'Спеки',
    ladderSkills: 'Скиллы',
    ladderCrons: 'Кроны',
    ladderAgents: 'Агенты',
    soulLaw: 'ДУША И ЗАКОН',
    soulLawHint: 'Три документа, которые связывают каждую букву; ссылки на коммит, с которого снят снимок опыта.',
    openSoul: 'Открыть SOUL.md',
    openAgentsDoc: 'Открыть AGENTS.md',
    openAlphabet: 'Строка алфавита',
    pinnedAt: 'закреплено на',
    crons: 'КРОНЫ',
    cronsHint: 'Задания, чей RUNS называет один из скиллов агента — выводится, а не объявляется.',
    noCrons: 'ни одно задание не запускает скиллы этого агента',
    noCronsNoSkills: 'скиллов нет, значит и запускать заданиям нечего',
    experience: 'ОПЫТ',
    episodes: 'эпизодов',
    firstEpisode: 'первый',
    lastEpisode: 'последний',
    lastTask: 'последняя задача',
    outcomes: 'исходы',
    lessons: 'уроки',
    noEpisodes: 'атрибутированных эпизодов нет',
    noEpisodesHint: 'В снимке ни один эпизод не называет букву агента; эпизоды без буквы считаются неатрибутированными и никому не приписываются.',
    unattributed: 'неатрибутировано в снимке',
    snapshotFrom: 'снимок',
    invariants: 'ИНВАРИАНТЫ',
    entry: 'вход',
    exit: 'выход',
    register: 'регистр',
    archetype: 'архетип',
    layer: 'слой',
    clara: 'роль CLARA',
    noClara: 'нет',
    keyFiles: 'ключевые файлы',
    noKeyFiles: 'не перечислены',
    tools: 'ИНСТРУМЕНТЫ',
    noTools: 'пока ничего не привязано',
    toolsHint: 'Пятый слой: tri CLI и MCP-серверы, которые агент должен знать. Заполняется из specs/tools; пусто, пока источник не привяжет инструмент.',
    experienceLog: 'Журнал опыта',
    copyLink: 'Скопировать ссылку',
    copied: 'Скопировано',
    ordinal: 'номер',
    enabledOff: 'зарезервировано',
  },
} as const

type Ui = Record<keyof typeof UI.en, string>

const TAG_FAMILIES = [
  { prefix: 'layer/', label: 'layer' },
  { prefix: 'witness/', label: 'witness' },
  { prefix: 'skills/', label: 'skills' },
  { prefix: 'clara/', label: 'CLARA' },
  { prefix: 'enabled/', label: 'enabled' },
]

const LAYER_LABEL: Record<AgentLayer, { en: string; ru: string }> = {
  Archetypal: { en: 'Archetypal', ru: 'Архетипический' },
  Spiritual: { en: 'Spiritual', ru: 'Духовный' },
  Physical: { en: 'Physical', ru: 'Физический' },
}

function tagsOf(a: AgentSpecEntry): string[] {
  return [
    `layer/${a.fields.LAYER.toLowerCase()}`,
    `witness/${a.witness}`,
    `skills/${a.skills.length > 0 ? 'bound' : 'none'}`,
    `clara/${a.fields.CLARA_ROLE ? 'yes' : 'no'}`,
    `enabled/${a.fields.ENABLED ? 'true' : 'false'}`,
  ]
}

function shortDate(iso: string | null): string {
  return iso ? iso.replace('T', ' ').slice(0, 16) : '—'
}

export default function AgentExplorer() {
  const { lang } = useI18n()
  const ui: Ui = lang === 'ru' ? UI.ru : UI.en
  const short = lang === 'ru' ? 'ru' : 'en'
  usePageMeta(ui.metaTitle, ui.metaDescription)
  const params = useHashParams()
  const embedded = params.embedded

  const [catalog, setCatalog] = useState<AgentSpecCatalog | null>(null)
  const [selected, setSelected] = useState<AgentSpecEntry | null>(null)
  const [err, setErr] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [layer, setLayer] = useState('')
  const [witnessFilter, setWitnessFilter] = useState<'all' | 'spec+experience' | 'spec-only'>('all')
  const [tagSel, setTagSel] = useState<string[]>([])
  const [copied, setCopied] = useState(false)
  const [phone, setPhone] = useState(() => (typeof window === 'undefined' ? false : window.innerWidth < 760))
  const [narrow, setNarrow] = useState(() => (typeof window === 'undefined' ? false : window.innerWidth < 1100))
  const [pane, setPane] = useState<'list' | 'detail'>('list')

  useEffect(() => {
    const onResize = () => {
      setPhone(window.innerWidth < 760)
      setNarrow(window.innerWidth < 1100)
    }
    onResize()
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [])

  const pick = useCallback(
    (entry: AgentSpecEntry) => {
      setSelected(entry)
      params.set(agentExplorerHash(entry.letter, { embedded }))
    },
    [embedded, params],
  )

  useEffect(() => {
    let alive = true
    loadAgentSpecs()
      .then((c) => {
        if (!alive) return
        setCatalog(c)
        const wanted = params.get('agent')
        try {
          const target = resolveAgent(c, wanted)
          if (wanted) setPane('detail')
          pick(target)
        } catch (e) {
          setErr(String(e instanceof Error ? e.message : e))
          setPane('detail')
        }
      })
      .catch((e) => {
        if (!alive) return
        setErr(String(e instanceof Error ? e.message : e))
        setPane('detail')
      })
    return () => {
      alive = false
    }
    // Mount only: the deep link is read once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const agents = useMemo(() => catalog?.agents ?? [], [catalog])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return agents.filter((a) => {
      if (layer && a.fields.LAYER !== layer) return false
      if (witnessFilter !== 'all' && a.witness !== witnessFilter) return false
      if (tagSel.length) {
        const tags = tagsOf(a)
        if (!tagSel.every((t) => tags.includes(t))) return false
      }
      if (!q) return true
      const f = a.fields
      return (
        a.letter.toLowerCase() === q ||
        a.id.toLowerCase().includes(q) ||
        `${f.LETTER_NAME} ${f.NAME} ${f.DOMAIN} ${f.ARCHETYPE} ${f.REGISTER} ${f.CLARA_ROLE}`.toLowerCase().includes(q) ||
        Object.values(a.summary).join(' ').toLowerCase().includes(q) ||
        Object.values(a.name).join(' ').toLowerCase().includes(q) ||
        a.skills.some((s) => s.id.toLowerCase().includes(q))
      )
    })
  }, [agents, query, layer, witnessFilter, tagSel])

  const tagCounts = useMemo(() => {
    const acc: Record<string, number> = {}
    for (const a of filtered) for (const t of tagsOf(a)) acc[t] = (acc[t] ?? 0) + 1
    return acc
  }, [filtered])

  const items: ExplorerItem[] = useMemo(
    () =>
      filtered.map((a) => ({
        id: a.id,
        // The letter leads, as in the alphabet table; the name follows in the reader's locale.
        title: `${a.letter} · ${a.name[short] ?? a.name.en}`,
        subtitle: a.fields.DOMAIN,
        badge: a.skills.length > 0 ? `◷ ${a.skills.length}` : a.fields.ENABLED ? undefined : ui.enabledOff,
        badgeColor: a.skills.some((s) => !s.ok) ? C.bad : undefined,
        health: a.health,
        tags: tagsOf(a),
        haystack: `${a.letter} ${a.id} ${a.fields.LETTER_NAME} ${a.fields.DOMAIN}`.toLowerCase(),
      })),
    [filtered, short, ui.enabledOff],
  )

  const copy = useCallback(() => {
    if (!selected) return
    navigator.clipboard?.writeText(canonicalAgentUrl(selected.letter)).then(
      () => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1400)
      },
      () => {},
    )
  }, [selected])

  const box = panelBox(embedded)
  const showList = !phone || pane === 'list'
  const showDetail = !phone || pane === 'detail'
  const counts = catalog?.counts
  const withExp = counts?.specPlusExperience ?? 0
  const specOnly = counts?.specOnly ?? 0

  const ladderSteps: LadderStep[] = useMemo(() => {
    const l = catalog?.ladder
    const embed = embedded ? '?embed=1' : ''
    return [
      { key: 'specs', label: ui.ladderSpecs, count: l?.specs ?? null, href: `#/specs${embed}` },
      { key: 'skills', label: ui.ladderSkills, count: l?.skills ?? null, href: `#/skills${embed}` },
      { key: 'crons', label: ui.ladderCrons, count: l?.crons ?? null, href: `#/crons${embed}` },
      { key: 'agents', label: ui.ladderAgents, count: l?.agents ?? null, href: `#/agents${embed}`, current: true },
    ]
  }, [catalog, embedded, ui.ladderSpecs, ui.ladderSkills, ui.ladderCrons, ui.ladderAgents])

  const heading = (text: string) => <div style={{ fontSize: 11, color: C.muted, fontFamily: C.mono }}>{text}</div>
  const row = (label: string, value: React.ReactNode) => (
    <div style={{ display: 'flex', gap: 10, alignItems: 'baseline', flexWrap: 'wrap' }}>
      <span style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono, minWidth: 92 }}>{label}</span>
      <span style={{ fontSize: 12.5, color: '#d8d8d8', minWidth: 0, wordBreak: 'break-word' }}>{value}</span>
    </div>
  )
  const live = (text: string) => <span data-lang-exempt="live">{text}</span>

  const chipLink = (href: string, text: string, glyph: string, ok = true) =>
    ok ? (
      <a key={text} href={href} style={{ ...tagChip(false, false), color: C.accent, borderColor: C.borderBright, textDecoration: 'none' }} data-lang-exempt="live">
        {glyph} {text}
      </a>
    ) : (
      <span key={text} style={{ ...tagChip(false, false), color: C.bad, borderColor: C.bad }} data-lang-exempt="live">
        ✕ {text}
      </span>
    )

  const snapshot = catalog?.experienceSnapshot ?? null

  return (
    <div
      className="spec-x"
      data-embedded={embedded ? '1' : undefined}
      style={{
        height: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        background: C.bg,
        color: C.text,
        fontFamily: "'Outfit', system-ui, sans-serif",
        overflow: 'hidden',
      }}
    >
      {!embedded && (
        <ExplorerHeader
          title={ui.title}
          subtitle={ui.subtitle}
          back={ui.back}
          note={ui.note}
          provenance={
            snapshot
              ? snapshot.sources.map((s) => ({ repo: s.repo === 't27' ? 'gHashTag/t27' : 'gHashTag/trinity', shortCommit: s.commit.slice(0, 7) }))
              : undefined
          }
          provenanceLabel={ui.snapshotFrom}
          narrow={narrow}
          phone={phone}
        />
      )}
      <LayerLadder steps={ladderSteps} caption={ui.ladder} />

      <div style={{ flex: 1, display: 'flex', minHeight: 0, minWidth: 0 }}>
        {showList && (
          <ExplorerLibrary
            items={items}
            selectedId={selected?.id ?? null}
            onPick={(item) => {
              const entry = agents.find((a) => a.id === item.id)
              if (entry) {
                setPane('detail')
                pick(entry)
              }
            }}
            query={query}
            setQuery={setQuery}
            categories={(Object.entries(counts?.byLayer ?? {}) as [AgentLayer, number][]).map(
              ([k, n]) => [k, LAYER_LABEL[k]?.[short] ?? k, n] as [string, string, number],
            )}
            category={layer}
            setCategory={setLayer}
            filters={[
              { key: 'all', label: ui.filterAll, count: agents.length },
              { key: 'spec+experience', label: ui.filterWithExperience, count: withExp, color: C.accent, glyph: '✓' },
              { key: 'spec-only', label: ui.filterSpecOnly, count: specOnly, color: C.warn, glyph: '○' },
            ]}
            filter={witnessFilter}
            setFilter={(v) => setWitnessFilter(v as 'all' | 'spec+experience' | 'spec-only')}
            stack={[
              { key: 'spec+experience', count: withExp, color: C.accent, label: ui.filterWithExperience },
              { key: 'spec-only', count: specOnly, color: C.warn, label: ui.filterSpecOnly },
            ]}
            tagCounts={tagCounts}
            tagFamilies={TAG_FAMILIES}
            tagSel={tagSel}
            toggleTag={(t) => setTagSel((prev) => (prev.includes(t) ? prev.filter((x) => x !== t) : [...prev, t]))}
            clearTags={() => setTagSel([])}
            phone={phone}
            countLabel={`${filtered.length} ${ui.agents}`}
            titlesAreGenerated
            ui={{
              search: ui.search,
              allCategories: `${ui.allLayers} (${agents.length})`,
              tags: ui.tags,
              clear: ui.clear,
              noResults: ui.noResults,
              noneInGroup: ui.noneInGroup,
            }}
          />
        )}

        {showDetail && (
          <main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, minHeight: 0, overflowY: 'auto' }}>
            {err && (
              <div
                className="spec-x-banner"
                style={{
                  margin: '10px 14px 0',
                  padding: '9px 12px',
                  background: 'rgba(248,81,73,0.10)',
                  border: `1px solid ${C.bad}`,
                  borderRadius: 5,
                  fontSize: 12,
                  color: '#d8d8d8',
                }}
              >
                <span style={{ color: C.bad, fontWeight: 700 }}>⚠ {ui.failed}</span> <span data-lang-exempt="live">{err}</span>
              </div>
            )}
            {!selected && !err && <div style={{ padding: 24, color: C.muted, fontSize: 13 }}>{catalog ? ui.pickAgent : ui.loading}</div>}
            {selected && (
              <div style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 12 }}>
                {phone && (
                  <button onClick={() => setPane('list')} style={{ ...pill, alignSelf: 'flex-start' }}>
                    ← {ui.backToLibrary}
                  </button>
                )}
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <span
                    aria-hidden="true"
                    style={{
                      fontFamily: C.mono,
                      fontSize: 28,
                      fontWeight: 700,
                      lineHeight: 1,
                      color: C.golden,
                      minWidth: 36,
                      textAlign: 'center',
                      border: `1px solid ${C.borderBright}`,
                      borderRadius: 6,
                      padding: '4px 6px',
                    }}
                  >
                    {selected.letter}
                  </span>
                  <span style={{ fontSize: 15, fontWeight: 700 }} data-lang-exempt="live">
                    {selected.name[short] ?? selected.name.en}
                  </span>
                  <span style={{ fontFamily: C.mono, fontSize: 11, color: C.muted }} data-lang-exempt="live">
                    {selected.id} · {ui.ordinal} {selected.ordinal}
                  </span>
                  <span style={{ ...tagChip(false, false), cursor: 'default' }} data-lang-exempt="live">
                    {LAYER_LABEL[selected.fields.LAYER]?.[short] ?? selected.fields.LAYER}
                  </span>
                  <button onClick={copy} style={{ ...pill, color: copied ? C.accent : C.muted, marginLeft: 'auto' }}>
                    {copied ? ui.copied : ui.copyLink}
                  </button>
                </div>

                {/* The spec comes first: it is the statement about the letter;
                    the boxes below are what the catalogs and the snapshot saw. */}
                <AgentSpecPanel
                  lang={short}
                  kind="agent"
                  id={selected.id}
                  entry={selected}
                  embedded={embedded}
                  i18n={catalog?.i18n ?? []}
                  links={selected.skills.map((s) => ({ id: s.id, ok: s.ok, href: s.ok ? skillExplorerHash(s.id, { embedded }) : '#' }))}
                  extraControls={
                    <>
                      <a href={selected.links.soul} target="_blank" rel="noopener noreferrer" style={pill}>
                        {ui.openSoul}
                      </a>
                      <a href={selected.links.agentsDoc} target="_blank" rel="noopener noreferrer" style={pill}>
                        {ui.openAgentsDoc}
                      </a>
                      {selected.links.experienceLog && (
                        <a href={selected.links.experienceLog} target="_blank" rel="noopener noreferrer" style={pill}>
                          {ui.experienceLog}
                        </a>
                      )}
                    </>
                  }
                />

                {/* ---- soul & law ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.soulLaw)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.soulLawHint}</div>
                  <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>
                    <a href={selected.links.soul} target="_blank" rel="noopener noreferrer" style={pill} data-lang-exempt="live">
                      {selected.fields.SOUL}
                    </a>
                    <a href={selected.links.agentsDoc} target="_blank" rel="noopener noreferrer" style={pill} data-lang-exempt="live">
                      {selected.fields.AGENTS_DOC}
                    </a>
                    <a href={selected.links.alphabet} target="_blank" rel="noopener noreferrer" style={pill} data-lang-exempt="live">
                      {selected.fields.ALPHABET}
                    </a>
                  </div>
                  <div style={{ fontFamily: C.mono, fontSize: 10.5, color: C.muted }}>
                    {ui.pinnedAt} <span data-lang-exempt="live">{selected.links.pinnedAt.slice(0, 12)}</span>{' '}
                    <span style={{ opacity: 0.7 }} data-lang-exempt="live">
                      ({selected.links.pinSource})
                    </span>
                  </div>
                </div>

                {/* ---- crons (derived) ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.crons)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.cronsHint}</div>
                  {selected.crons.length === 0 ? (
                    <div style={{ fontSize: 12, color: C.muted }}>{selected.skills.length === 0 ? ui.noCronsNoSkills : ui.noCrons}</div>
                  ) : (
                    <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                      {selected.crons.map((id) => chipLink(cronExplorerHash(id, { embedded }), id, '⟲'))}
                    </div>
                  )}
                </div>

                {/* ---- experience ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.experience)}
                    <span style={{ fontFamily: C.mono, fontSize: 11.5, color: selected.experience.episodes > 0 ? C.accent : C.muted }}>
                      <b data-lang-exempt="live">{selected.experience.episodes}</b> {ui.episodes}
                    </span>
                  </div>
                  {selected.experience.episodes === 0 ? (
                    <>
                      <div style={{ fontSize: 12, color: C.warn }}>{ui.noEpisodes}</div>
                      <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.noEpisodesHint}</div>
                    </>
                  ) : (
                    <>
                      {row(ui.firstEpisode, live(shortDate(selected.experience.first)))}
                      {row(ui.lastEpisode, live(shortDate(selected.experience.last)))}
                      {selected.experience.lastTask && row(ui.lastTask, live(selected.experience.lastTask))}
                      {row(
                        ui.outcomes,
                        live(
                          Object.entries(selected.experience.outcomes)
                            .map(([k, n]) => `${k} ${n}`)
                            .join(' · ') || '—',
                        ),
                      )}
                      {selected.experience.lessons.length > 0 && (
                        <div>
                          <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono, marginBottom: 4 }}>{ui.lessons}</div>
                          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 12, lineHeight: 1.5, color: '#d8d8d8' }} data-lang-exempt="live">
                            {selected.experience.lessons.map((l, i) => (
                              <li key={i}>{l}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </>
                  )}
                  {snapshot?.counts && (
                    <div style={{ fontFamily: C.mono, fontSize: 10.5, color: C.muted }}>
                      {ui.unattributed}: <span data-lang-exempt="live">{snapshot.counts.unattributed}</span> · {ui.snapshotFrom}{' '}
                      <span data-lang-exempt="live">
                        {snapshot.sources.map((s) => `${s.repo}@${s.commit.slice(0, 7)} (${s.episodes})`).join(', ')}
                      </span>
                    </div>
                  )}
                </div>

                {/* ---- invariants ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {heading(ui.invariants)}
                  {row(ui.entry, live(selected.fields.ENTRY_INVARIANT))}
                  {row(ui.exit, live(selected.fields.EXIT_INVARIANT))}
                  {row(ui.archetype, live(selected.fields.ARCHETYPE))}
                  {row(ui.register, live(selected.fields.REGISTER))}
                  {row(ui.layer, live(LAYER_LABEL[selected.fields.LAYER]?.[short] ?? selected.fields.LAYER))}
                  {row(ui.clara, selected.fields.CLARA_ROLE ? live(selected.fields.CLARA_ROLE) : ui.noClara)}
                  {row(
                    ui.keyFiles,
                    selected.fields.KEY_FILES.length === 0 ? (
                      ui.noKeyFiles
                    ) : (
                      <span style={{ fontFamily: C.mono, fontSize: 11.5 }} data-lang-exempt="live">
                        {selected.fields.KEY_FILES.join(' · ')}
                      </span>
                    ),
                  )}
                </div>

                {/* ---- tools (layer five) ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.tools)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.toolsHint}</div>
                  {selected.tools.length === 0 ? (
                    <div style={{ fontSize: 12, color: C.muted }}>
                      {ui.noTools}
                      {selected.fields.TOOLS_NOTE ? <span data-lang-exempt="live"> — {selected.fields.TOOLS_NOTE}</span> : null}
                    </div>
                  ) : (
                    <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                      {selected.tools.map((id) => (
                        <span key={id} style={{ ...tagChip(false, false), cursor: 'default' }} data-lang-exempt="live">
                          ⚙ {id}
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </main>
        )}
      </div>
    </div>
  )
}
