// Function Explorer -- the Inngest functions of the bot, each read from its spec.
//
// The sixth step of the site's ladder: Specs → Skills → Crons → Agents → Tools →
// Functions (t27 specs/functions/README.md calls itself "layer 5", as does
// specs/tools/README.md -- a source discrepancy recorded, not resolved here). A
// function is one `createFunction(...)` the bot 999-multibots-telegraf
// registers; its card is generated by scripts/agents-from-specs.mjs from
// specs/functions/<id>.t27 through the real compiler and witnessed by a
// vendored copy of the functions manifest (public/functions/manifest.json).
// Nothing on this page is typed twice: trigger, events, steps, retries,
// side effects, the safe probe and its result all come from the spec; the
// deployed flag comes from the manifest; and where the two disagree the card
// says so instead of picking one.
//
// LIVE STATUS is read from the bot's public status endpoint once a minute and
// never invented: when the endpoint is not there yet (404), refuses the origin
// (CORS) or is unreachable, the page draws an explicit "status source offline"
// state, and a count the endpoint did not send is shown as unknown, not zero.

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useI18n } from '../i18n/context'
import { usePageMeta } from '../hooks/usePageMeta'
import { useHashParams } from '../hooks/useHashParams'
import { useDocumentLock, useViewport } from '../lib/useViewport'
import { HEADER_CHROME_MAX } from '../lib/viewport.generated'
import { ExplorerHeader } from '../components/ExplorerHeader'
import { ExplorerLibrary, type ExplorerItem } from '../components/ExplorerLibrary'
import { AgentSpecPanel } from '../components/AgentSpecPanel'
import { LayerLadder, type LadderStep } from '../components/LayerLadder'
import { StackBar, type StackSegment } from '../components/SpecGraphics'
import { loadFunctionSpecs, type FunctionSideEffect, type FunctionSpecCatalog, type FunctionSpecEntry, type FunctionTrigger } from '../lib/agentSpecs'
import { cronExplorerHash } from '../lib/cronsCatalog'
import { canonicalFunctionUrl, functionExplorerHash, functionSourceUrl, resolveFunction } from '../lib/functionsCatalog'
import { STATUS_POLL_MS, fetchFunctionsStatus, functionsStatusUrl, totalRuns, type FunctionStatus, type StatusState } from '../lib/functionsStatus'
import { C, panelBox, pill, tagChip } from '../lib/explorerTheme'

const UI = {
  en: {
    title: 'Function Explorer',
    subtitle: 'The Inngest functions of the bot, each read from its spec',
    metaTitle: 'Function Explorer',
    metaDescription:
      'The Inngest functions of 999-multibots-telegraf, each generated from a .t27 spec: trigger, events, steps, retries, side effects, the safe probe and its result, the deployed flag from the manifest, and live run counts when the status source answers.',
    note: 'Generated from specs/functions/*.t27, witnessed by the functions manifest',
    back: '← Home',
    search: 'Search functions',
    allDomains: 'All domains',
    tags: 'Tags',
    clear: 'Clear',
    functions: 'functions',
    noResults: 'No function matches',
    noneInGroup: 'No function in this group',
    pickFunction: 'Pick a function from the list to see its trigger, steps, side effects and probe.',
    loading: 'Loading the catalog…',
    failed: 'The catalog could not be read:',
    backToLibrary: 'All functions',
    filters: 'Filters',
    filterAll: 'All',
    filterEvent: 'event',
    filterCron: 'cron',
    ladder: 'Specs → Skills → Crons → Agents → Functions',
    ladderSpecs: 'Specs',
    ladderSkills: 'Skills',
    ladderCrons: 'Crons',
    ladderAgents: 'Agents',
    ladderTools: 'Tools',
    ladderFunctions: 'Functions',
    copyLink: 'Copy link',
    copied: 'Copied',
    notDeployed: 'not deployed',
    deployed: 'deployed',
    deployUnknown: 'deployment unknown',
    trigger: 'TRIGGER',
    event: 'event',
    legacyEvents: 'legacy events',
    noLegacyEvents: 'none',
    cron: 'cron',
    tz: 'time zone',
    cronCard: 'cron card',
    noCronCard: 'no cron card in specs/crons states this schedule',
    steps: 'STEPS',
    stepsHint: 'step.run ids in source order; ${i} marks a step repeated per item.',
    retries: 'retries',
    onFailure: 'on failure',
    guard: 'guard',
    noGuard: 'no guard step named',
    guardUnknown: 'unknown (not on the production build)',
    sideEffects: 'SIDE EFFECTS',
    probe: 'SAFE PROBE',
    probeHint: 'The payload sent with e2e_test=true on 2026-09-09 and what happened. Recorded in the spec, not repeated by this page.',
    noProbe: 'no probe was sent',
    probeResult: 'result',
    source: 'SOURCE',
    file: 'registration',
    openSource: 'Open on GitHub',
    manifestCommit: 'manifest read at',
    witness: 'witness',
    differences: 'spec and manifest differ',
    noDifferences: 'spec and manifest agree on every field the manifest read',
    noteLabel: 'note',
    live: 'LIVE STATUS',
    liveHint: 'Read from the bot once a minute. Nothing here is remembered or invented.',
    liveLoading: 'asking the status source…',
    liveOffline: 'status source offline',
    liveOfflineHint: 'The endpoint is being built in parallel with this page; until it answers, run counts are unknown, not zero.',
    liveOk: 'status source online',
    liveAt: 'read at',
    liveUrl: 'source',
    liveGenerated: 'generated by the bot at',
    liveNotReported: 'the status source did not report this function',
    runs24h: 'runs, last 24 h',
    runs7d: 'runs, last 7 d',
    completed: 'completed',
    failedRuns: 'failed',
    running: 'running',
    unknown: 'unknown',
    lastRun: 'last run',
    lastError: 'last error',
    noRunsYet: 'no run reported',
    healthRing: 'HEALTH, 24 H',
    healthRingHint: 'Completed against failed runs across every reported function, last 24 hours.',
    bars7d: 'RUNS, 7 D',
    bars7dHint: 'Completed (green) and failed (red) runs per function over the last seven days, as the status source reports them.',
    bars7dNoDaily: 'The status source reports 7-day totals, not per-day counts, so each bar is one total.',
    breakdown: 'TRIGGERS AND SIDE EFFECTS',
    breakdownHint: 'From the specs: how the functions are triggered and what a run touches outside the process.',
    byTrigger: 'by trigger',
    bySideEffect: 'by side effect',
    timeline: 'LAST RUNS',
    timelineHint: 'When each reported function last ended, on a seven-day axis; a dot per function, coloured by the status the source reported.',
    timelineEmpty: 'no last run reported by the status source',
    now: 'now',
    daysAgo: 'd',
    all: 'all functions',
    thisFunction: 'this function',
    domain: 'domain',
    legacyId: 'legacy id',
  },
  ru: {
    title: 'Обозреватель функций',
    subtitle: 'Функции Inngest бота, каждая прочитана из своей спеки',
    metaTitle: 'Обозреватель функций',
    metaDescription:
      'Функции Inngest бота 999-multibots-telegraf, каждая сгенерирована из .t27-спеки: триггер, события, шаги, повторы, побочные эффекты, безопасная проба и её результат, флаг развёртывания из манифеста и живые счётчики запусков, когда источник статуса отвечает.',
    note: 'Сгенерировано из specs/functions/*.t27, засвидетельствовано манифестом функций',
    back: '← На главную',
    search: 'Поиск по функциям',
    allDomains: 'Все домены',
    tags: 'Метки',
    clear: 'Сбросить',
    functions: 'функций',
    noResults: 'Ничего не найдено',
    noneInGroup: 'В этой группе пусто',
    pickFunction: 'Выберите функцию слева — покажу триггер, шаги, побочные эффекты и пробу.',
    loading: 'Загружаю каталог…',
    failed: 'Каталог не прочитан:',
    backToLibrary: 'Все функции',
    filters: 'Фильтры',
    filterAll: 'Все',
    filterEvent: 'событие',
    filterCron: 'крон',
    ladder: 'Спеки → Скиллы → Кроны → Агенты → Функции',
    ladderSpecs: 'Спеки',
    ladderSkills: 'Скиллы',
    ladderCrons: 'Кроны',
    ladderAgents: 'Агенты',
    ladderTools: 'Инструменты',
    ladderFunctions: 'Функции',
    copyLink: 'Скопировать ссылку',
    copied: 'Скопировано',
    notDeployed: 'не развёрнута',
    deployed: 'развёрнута',
    deployUnknown: 'развёртывание неизвестно',
    trigger: 'ТРИГГЕР',
    event: 'событие',
    legacyEvents: 'старые события',
    noLegacyEvents: 'нет',
    cron: 'крон',
    tz: 'часовой пояс',
    cronCard: 'крон-карточка',
    noCronCard: 'ни одна крон-карточка в specs/crons не описывает это расписание',
    steps: 'ШАГИ',
    stepsHint: 'id шагов step.run в порядке исходника; ${i} — шаг, повторяемый для каждого элемента.',
    retries: 'повторы',
    onFailure: 'при сбое',
    guard: 'страж',
    noGuard: 'шаг-страж не назван',
    guardUnknown: 'неизвестно (нет в продакшен-сборке)',
    sideEffects: 'ПОБОЧНЫЕ ЭФФЕКТЫ',
    probe: 'БЕЗОПАСНАЯ ПРОБА',
    probeHint: 'Что было отправлено с e2e_test=true 2026-09-09 и что произошло. Записано в спеке; страница пробу не повторяет.',
    noProbe: 'проба не отправлялась',
    probeResult: 'результат',
    source: 'ИСХОДНИК',
    file: 'регистрация',
    openSource: 'Открыть на GitHub',
    manifestCommit: 'манифест прочитан на',
    witness: 'свидетель',
    differences: 'спека и манифест расходятся',
    noDifferences: 'спека и манифест согласны по каждому полю, которое манифест прочитал',
    noteLabel: 'заметка',
    live: 'ЖИВОЙ СТАТУС',
    liveHint: 'Читается с бота раз в минуту. Ничего здесь не запоминается и не придумывается.',
    liveLoading: 'спрашиваю источник статуса…',
    liveOffline: 'источник статуса недоступен',
    liveOfflineHint: 'Эндпоинт строится параллельно с этой страницей; пока он не отвечает, счётчики запусков неизвестны, а не равны нулю.',
    liveOk: 'источник статуса на связи',
    liveAt: 'прочитано',
    liveUrl: 'источник',
    liveGenerated: 'сформировано ботом',
    liveNotReported: 'источник статуса не сообщил об этой функции',
    runs24h: 'запусков за 24 ч',
    runs7d: 'запусков за 7 дн',
    completed: 'завершено',
    failedRuns: 'с ошибкой',
    running: 'выполняется',
    unknown: 'неизвестно',
    lastRun: 'последний запуск',
    lastError: 'последняя ошибка',
    noRunsYet: 'запусков не сообщено',
    healthRing: 'ЗДОРОВЬЕ, 24 Ч',
    healthRingHint: 'Завершённые против упавших запусков по всем сообщённым функциям за последние 24 часа.',
    bars7d: 'ЗАПУСКИ, 7 ДН',
    bars7dHint: 'Завершённые (зелёные) и упавшие (красные) запуски по функциям за последние семь дней, как сообщает источник статуса.',
    bars7dNoDaily: 'Источник статуса сообщает итоги за 7 дней, а не по дням, поэтому каждая полоса — один итог.',
    breakdown: 'ТРИГГЕРЫ И ПОБОЧНЫЕ ЭФФЕКТЫ',
    breakdownHint: 'Из спек: как функции запускаются и что запуск трогает вне процесса.',
    byTrigger: 'по триггеру',
    bySideEffect: 'по побочному эффекту',
    timeline: 'ПОСЛЕДНИЕ ЗАПУСКИ',
    timelineHint: 'Когда каждая сообщённая функция завершалась в последний раз, на оси в семь дней; точка на функцию, цвет — статус от источника.',
    timelineEmpty: 'источник статуса не сообщил ни одного последнего запуска',
    now: 'сейчас',
    daysAgo: 'дн',
    all: 'все функции',
    thisFunction: 'эта функция',
    domain: 'домен',
    legacyId: 'старый id',
  },
} as const

type Ui = Record<keyof typeof UI.en, string>

const TAG_FAMILIES = [
  { prefix: 'se:', label: 'side effect' },
  { prefix: 'fail:', label: 'on failure' },
  { prefix: 'probe:', label: 'probe' },
  { prefix: 'deployed:', label: 'deployed' },
  { prefix: 'witness:', label: 'witness' },
]

const SIDE_EFFECT_LABEL: Record<FunctionSideEffect, { en: string; ru: string }> = {
  'charges-balance': { en: 'charges balance', ru: 'списывает баланс' },
  'paid-api': { en: 'paid API', ru: 'платный API' },
  'messages-user': { en: 'messages user', ru: 'пишет пользователю' },
  'messages-owners': { en: 'messages owners', ru: 'пишет владельцам' },
  'messages-admin': { en: 'messages admin', ru: 'пишет админу' },
  'db-write': { en: 'writes DB', ru: 'пишет в БД' },
  'external-webhook': { en: 'external webhook', ru: 'внешний вебхук' },
  none: { en: 'none', ru: 'нет' },
}

const SIDE_EFFECT_COLOR: Record<FunctionSideEffect, string> = {
  'charges-balance': C.golden,
  'paid-api': C.warn,
  'messages-user': C.blue,
  'messages-owners': '#7bb5ff',
  'messages-admin': '#a78bfa',
  'db-write': C.accent,
  'external-webhook': '#f472b6',
  none: C.muted,
}

const TRIGGER_COLOR: Record<FunctionTrigger, string> = { event: C.blue, cron: C.golden }

function deployedKey(f: FunctionSpecEntry): 'yes' | 'no' | 'unknown' {
  const d = f.code?.deployed
  return d === true ? 'yes' : d === false ? 'no' : 'unknown'
}

function tagsOf(f: FunctionSpecEntry): string[] {
  return [
    ...f.fields.SIDE_EFFECTS.map((s) => `se:${s}`),
    `fail:${f.fields.ON_FAILURE}`,
    `probe:${f.fields.PROBE_RESULT}`,
    `deployed:${deployedKey(f)}`,
    `witness:${f.witness}`,
  ]
}

function shortDate(iso: string | null): string {
  return iso ? iso.replace('T', ' ').slice(0, 16) : '—'
}

const fmt = (n: number | null, unknown: string): string => (n === null ? unknown : String(n))

// ---------------------------------------------------------------------------
// Inline SVG infographics. No dependency; every number drawn is one the page
// received, and a missing number is drawn as "unknown", never as zero.
// ---------------------------------------------------------------------------

function HealthRing({ completed, failed, running, ui, offline }: { completed: number | null; failed: number | null; running: number | null; ui: Ui; offline: boolean }) {
  const r = 34
  const circ = 2 * Math.PI * r
  const total = (completed ?? 0) + (failed ?? 0)
  const known = !offline && (completed !== null || failed !== null)
  const okFrac = known && total > 0 ? (completed ?? 0) / total : 0
  const badFrac = known && total > 0 ? (failed ?? 0) / total : 0
  const pct = known && total > 0 ? Math.round(okFrac * 100) : null
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
      <svg width={92} height={92} viewBox="0 0 92 92" role="img" aria-label={ui.healthRing}>
        <circle cx={46} cy={46} r={r} fill="none" stroke={C.border} strokeWidth={9} />
        {known && total > 0 && (
          <>
            <circle cx={46} cy={46} r={r} fill="none" stroke={C.accent} strokeWidth={9} strokeDasharray={`${okFrac * circ} ${circ}`} transform="rotate(-90 46 46)" strokeLinecap="butt" />
            <circle cx={46} cy={46} r={r} fill="none" stroke={C.bad} strokeWidth={9} strokeDasharray={`${badFrac * circ} ${circ}`} strokeDashoffset={-okFrac * circ} transform="rotate(-90 46 46)" strokeLinecap="butt" />
          </>
        )}
        <text x={46} y={44} textAnchor="middle" fill={known ? C.text : C.muted} fontFamily={C.mono} fontSize={pct === null ? 9 : 16} fontWeight={700} data-lang-exempt="live">
          {pct === null ? '?' : `${pct}%`}
        </text>
        <text x={46} y={58} textAnchor="middle" fill={C.muted} fontFamily={C.mono} fontSize={8}>
          {known && total > 0 ? '24h' : ui.unknown}
        </text>
      </svg>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 4, fontFamily: C.mono, fontSize: 11.5 }}>
        <span style={{ color: C.accent }}>
          ● {ui.completed} <b data-lang-exempt="live">{offline ? ui.unknown : fmt(completed, ui.unknown)}</b>
        </span>
        <span style={{ color: C.bad }}>
          ● {ui.failedRuns} <b data-lang-exempt="live">{offline ? ui.unknown : fmt(failed, ui.unknown)}</b>
        </span>
        <span style={{ color: C.blue }}>
          ● {ui.running} <b data-lang-exempt="live">{offline ? ui.unknown : fmt(running, ui.unknown)}</b>
        </span>
      </div>
    </div>
  )
}

function Bars7d({ rows, ui, selectedId, onPick }: { rows: { id: string; status: FunctionStatus | null }[]; ui: Ui; selectedId: string | null; onPick: (id: string) => void }) {
  const anyDaily = rows.some((r) => r.status?.daily7d && r.status.daily7d.length > 0)
  const max = Math.max(
    1,
    ...rows.map((r) => {
      const s = r.status
      if (!s) return 0
      if (anyDaily && s.daily7d) return Math.max(0, ...s.daily7d.map((d) => (d.completed ?? 0) + (d.failed ?? 0)))
      return (s.runs7d.completed ?? 0) + (s.runs7d.failed ?? 0)
    }),
  )
  const w = 120
  const h = 22
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
      {!anyDaily && rows.some((r) => r.status) && <div style={{ fontSize: 10.5, color: C.muted, lineHeight: 1.4 }}>{ui.bars7dNoDaily}</div>}
      {rows.map((r) => {
        const s = r.status
        const known = s !== null && (s.runs7d.completed !== null || s.runs7d.failed !== null || (s.daily7d?.length ?? 0) > 0)
        const cells = anyDaily && s?.daily7d ? s.daily7d.slice(-7) : known && s ? [{ day: '7d', completed: s.runs7d.completed, failed: s.runs7d.failed }] : []
        const cw = cells.length ? w / cells.length : w
        const sel = r.id === selectedId
        return (
          <button
            key={r.id}
            onClick={() => onPick(r.id)}
            title={r.id}
            style={{ display: 'flex', alignItems: 'center', gap: 8, background: sel ? C.raised : 'transparent', border: 'none', padding: '1px 4px', borderRadius: 3, cursor: 'pointer', color: C.text, textAlign: 'left' }}
          >
            <span style={{ fontFamily: C.mono, fontSize: 10, color: sel ? C.golden : C.muted, width: 150, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} data-lang-exempt="live">
              {r.id}
            </span>
            <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} aria-hidden="true">
              <rect x={0} y={0} width={w} height={h} fill={C.panel} />
              {cells.length === 0 ? (
                <text x={w / 2} y={h / 2 + 3} textAnchor="middle" fill={C.muted} fontFamily={C.mono} fontSize={8}>
                  {ui.unknown}
                </text>
              ) : (
                cells.map((c, i) => {
                  const ok = c.completed ?? 0
                  const bad = c.failed ?? 0
                  const okH = (ok / max) * (h - 2)
                  const badH = (bad / max) * (h - 2)
                  const x = i * cw + 1
                  return (
                    <g key={i}>
                      <rect x={x} y={h - 1 - okH} width={Math.max(1, cw - 2)} height={okH} fill={C.accent} />
                      <rect x={x} y={h - 1 - okH - badH} width={Math.max(1, cw - 2)} height={badH} fill={C.bad} />
                    </g>
                  )
                })
              )}
            </svg>
            <span style={{ fontFamily: C.mono, fontSize: 10, color: C.muted, minWidth: 64 }} data-lang-exempt="live">
              {known && s ? `${fmt(s.runs7d.completed, '?')} / ${fmt(s.runs7d.failed, '?')}` : ui.unknown}
            </span>
          </button>
        )
      })}
    </div>
  )
}

function LastRunTimeline({ rows, ui, now, selectedId, onPick }: { rows: { id: string; status: FunctionStatus | null }[]; ui: Ui; now: number; selectedId: string | null; onPick: (id: string) => void }) {
  const span = 7 * 24 * 3600 * 1000
  const w = 520
  const h = 54
  type Dot = { id: string; x: number; color: string; st: string; ended: number }
  const dots: Dot[] = rows
    .map((r): Dot | null => {
      const ended = r.status?.lastRun?.endedAt ? Date.parse(r.status.lastRun.endedAt) : NaN
      if (!Number.isFinite(ended)) return null
      const age = now - ended
      const x = 16 + Math.max(0, Math.min(1, 1 - age / span)) * (w - 32)
      const st = (r.status?.lastRun?.status ?? '').toUpperCase()
      const color = st === 'COMPLETED' ? C.accent : st === 'FAILED' || st === 'CANCELLED' ? C.bad : st === 'RUNNING' ? C.blue : C.muted
      return { id: r.id, x, color, st, ended }
    })
    .filter((d) => d !== null)
    .sort((a, b) => a.x - b.x)
  if (dots.length === 0) return <div style={{ fontSize: 12, color: C.muted }}>{ui.timelineEmpty}</div>
  return (
    <svg width="100%" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={ui.timeline} style={{ maxWidth: w }}>
      <line x1={16} y1={30} x2={w - 16} y2={30} stroke={C.border} strokeWidth={1} />
      {[7, 6, 5, 4, 3, 2, 1, 0].map((d) => {
        const x = 16 + (1 - d / 7) * (w - 32)
        return (
          <g key={d}>
            <line x1={x} y1={26} x2={x} y2={34} stroke={C.border} />
            <text x={x} y={48} textAnchor="middle" fill={C.muted} fontFamily={C.mono} fontSize={8}>
              {d === 0 ? ui.now : `-${d}${ui.daysAgo}`}
            </text>
          </g>
        )
      })}
      {dots.map((d, i) => (
        <g key={d.id} style={{ cursor: 'pointer' }} onClick={() => onPick(d.id)}>
          <title>{`${d.id} · ${d.st || ui.unknown} · ${shortDate(new Date(d.ended).toISOString())}`}</title>
          <circle cx={d.x} cy={30 - ((i % 3) - 1) * 7} r={d.id === selectedId ? 5.5 : 4} fill={d.color} stroke={d.id === selectedId ? C.golden : C.bg} strokeWidth={1.5} />
        </g>
      ))}
    </svg>
  )
}

// ---------------------------------------------------------------------------

export default function FunctionExplorer() {
  const { lang } = useI18n()
  const ui: Ui = lang === 'ru' ? UI.ru : UI.en
  const short = lang === 'ru' ? 'ru' : 'en'
  usePageMeta(ui.metaTitle, ui.metaDescription)
  const params = useHashParams()
  const embedded = params.embedded

  const [catalog, setCatalog] = useState<FunctionSpecCatalog | null>(null)
  const [selected, setSelected] = useState<FunctionSpecEntry | null>(null)
  const [err, setErr] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [domain, setDomain] = useState('')
  const [triggerFilter, setTriggerFilter] = useState<'all' | FunctionTrigger>('all')
  const [tagSel, setTagSel] = useState<string[]>([])
  const [copied, setCopied] = useState(false)
  // Layout tier from specs/ui/viewport.t27 (via useViewport); `narrow` trims the
  // header chrome and is not a tier. Phone and tablet lock the document: the
  // panes are the scrollers there.
  const viewport = useViewport()
  const phone = viewport.tier === 'phone'
  const compact = phone || viewport.tier === 'tablet'
  const narrow = viewport.width < HEADER_CHROME_MAX
  useDocumentLock(compact)
  const [pane, setPane] = useState<'list' | 'detail'>('list')
  const [live, setLive] = useState<StatusState>({ kind: 'loading' })
  const [now, setNow] = useState(() => Date.now())

  // Live status: one fetch now, then once a minute while the page is open.
  useEffect(() => {
    let alive = true
    const url = functionsStatusUrl()
    const tick = () => {
      void fetchFunctionsStatus(url).then((s) => {
        if (!alive) return
        setLive(s)
        setNow(Date.now())
      })
    }
    tick()
    const timer = window.setInterval(tick, STATUS_POLL_MS)
    return () => {
      alive = false
      window.clearInterval(timer)
    }
  }, [])

  const pick = useCallback(
    (entry: FunctionSpecEntry) => {
      setSelected(entry)
      params.set(functionExplorerHash(entry.id, { embedded }))
    },
    [embedded, params],
  )

  useEffect(() => {
    let alive = true
    loadFunctionSpecs()
      .then((c) => {
        if (!alive) return
        setCatalog(c)
        const wanted = params.get('function')
        try {
          const target = resolveFunction(c, wanted)
          if (wanted) setPane('detail')
          pick(target)
        } catch (e) {
          setErr(String(e instanceof Error ? e.message : e))
          setPane('detail')
        }
      })
      .catch((e) => {
        if (!alive) return
        setErr(String(e instanceof Error ? e.message : e))
        setPane('detail')
      })
    return () => {
      alive = false
    }
    // Mount only: the deep link is read once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // A deep link that arrives after mount (the back button, a link on this
  // page, a script setting the hash): open that card, on a phone as the card
  // pane. Measured before this at 390x844: `#/functions` then a `?function=` hash
  // kept the list, because the parameters were read once.
  useEffect(() => {
    if (!catalog || params.changes === 0) return
    const wanted = params.get('function')
    if (!wanted) return
    try {
      const target = resolveFunction(catalog, wanted)
      setPane('detail')
      if (target !== selected) pick(target)
    } catch {
      // An unknown id in a later hash: keep the card that is open.
    }
    // Only the hash counter: the catalog and the selection are read, not followed.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params.changes])

  const functions = useMemo(() => catalog?.functions ?? [], [catalog])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return functions.filter((f) => {
      if (domain && f.fields.DOMAIN !== domain) return false
      if (triggerFilter !== 'all' && f.fields.TRIGGER !== triggerFilter) return false
      if (tagSel.length) {
        const tags = tagsOf(f)
        if (!tagSel.every((t) => tags.includes(t))) return false
      }
      if (!q) return true
      const x = f.fields
      return (
        f.id.toLowerCase().includes(q) ||
        `${x.LEGACY_ID} ${x.DOMAIN} ${x.EVENT} ${x.LEGACY_EVENTS.join(' ')} ${x.CRON} ${x.SERVICE} ${x.GUARD}`.toLowerCase().includes(q) ||
        x.STEPS.some((s) => s.toLowerCase().includes(q)) ||
        Object.values(f.summary).join(' ').toLowerCase().includes(q) ||
        Object.values(f.name).join(' ').toLowerCase().includes(q)
      )
    })
  }, [functions, query, domain, triggerFilter, tagSel])

  const tagCounts = useMemo(() => {
    const acc: Record<string, number> = {}
    for (const f of filtered) for (const t of tagsOf(f)) acc[t] = (acc[t] ?? 0) + 1
    return acc
  }, [filtered])

  const items: ExplorerItem[] = useMemo(
    () =>
      filtered.map((f) => ({
        id: f.id,
        title: f.name[short] ?? f.name.en,
        subtitle: f.fields.TRIGGER === 'cron' ? `⟲ ${f.fields.CRON}` : `⚡ ${f.fields.EVENT}`,
        badge: f.code?.deployed === false ? ui.notDeployed : f.differences.length ? '≠' : undefined,
        badgeColor: f.code?.deployed === false ? C.bad : f.differences.length ? C.warn : undefined,
        health: f.health,
        tags: tagsOf(f),
        haystack: `${f.id} ${f.fields.LEGACY_ID} ${f.fields.DOMAIN} ${f.fields.EVENT}`.toLowerCase(),
      })),
    [filtered, short, ui.notDeployed],
  )

  const copy = useCallback(() => {
    if (!selected) return
    navigator.clipboard?.writeText(canonicalFunctionUrl(selected.id)).then(
      () => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1400)
      },
      () => {},
    )
  }, [selected])

  const pickById = useCallback(
    (id: string) => {
      const entry = functions.find((f) => f.id === id)
      if (entry) {
        setPane('detail')
        pick(entry)
      }
    },
    [functions, pick],
  )

  const box = panelBox(embedded)
  const showList = !phone || pane === 'list'
  const showDetail = !phone || pane === 'detail'
  const counts = catalog?.counts
  const nEvent = counts?.byTrigger.event ?? 0
  const nCron = counts?.byTrigger.cron ?? 0

  const ladderSteps: LadderStep[] = useMemo(() => {
    const l = catalog?.ladder
    const embed = embedded ? '?embed=1' : ''
    return [
      { key: 'specs', label: ui.ladderSpecs, count: l?.specs ?? null, href: `#/specs${embed}` },
      { key: 'skills', label: ui.ladderSkills, count: l?.skills ?? null, href: `#/skills${embed}` },
      { key: 'crons', label: ui.ladderCrons, count: l?.crons ?? null, href: `#/crons${embed}` },
      { key: 'agents', label: ui.ladderAgents, count: l?.agents ?? null, href: `#/agents${embed}` },
      { key: 'tools', label: ui.ladderTools, count: l?.tools ?? null, href: `#/tools${embed}` },
      { key: 'functions', label: ui.ladderFunctions, count: l?.functions ?? null, href: `#/functions${embed}`, current: true },
    ]
  }, [catalog, embedded, ui.ladderSpecs, ui.ladderSkills, ui.ladderCrons, ui.ladderAgents, ui.ladderTools, ui.ladderFunctions])

  const triggerSegments: StackSegment[] = useMemo(
    () => [
      { key: 'event', count: nEvent, color: TRIGGER_COLOR.event, label: `${ui.filterEvent} ${nEvent}` },
      { key: 'cron', count: nCron, color: TRIGGER_COLOR.cron, label: `${ui.filterCron} ${nCron}` },
    ],
    [nEvent, nCron, ui.filterEvent, ui.filterCron],
  )
  const sideEffectSegments: StackSegment[] = useMemo(
    () =>
      (Object.entries(counts?.bySideEffect ?? {}) as [FunctionSideEffect, number][])
        .filter(([, n]) => n > 0)
        .map(([k, n]) => ({ key: k, count: n, color: SIDE_EFFECT_COLOR[k] ?? C.muted, label: `${SIDE_EFFECT_LABEL[k]?.[short] ?? k} ${n}` })),
    [counts, short],
  )

  const liveRows = useMemo(() => functions.map((f) => ({ id: f.id, status: live.kind === 'ok' ? live.status.byId.get(f.id) ?? null : null })), [functions, live])
  const liveOffline = live.kind !== 'ok'
  const totals24 = live.kind === 'ok' ? totalRuns(live.status, 'runs24h') : { completed: null, failed: null, running: null }
  const selectedLive: FunctionStatus | null = selected && live.kind === 'ok' ? live.status.byId.get(selected.id) ?? null : null

  const heading = (text: string) => <div style={{ fontSize: 11, color: C.muted, fontFamily: C.mono }}>{text}</div>
  const row = (label: string, value: React.ReactNode) => (
    <div style={{ display: 'flex', gap: 10, alignItems: 'baseline', flexWrap: 'wrap' }}>
      <span style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono, minWidth: 92 }}>{label}</span>
      <span style={{ fontSize: 12.5, color: '#d8d8d8', minWidth: 0, wordBreak: 'break-word' }}>{value}</span>
    </div>
  )
  const liveText = (text: string) => <span data-lang-exempt="live">{text}</span>
  const mono = (text: string, color = '#d8d8d8') => (
    <span style={{ fontFamily: C.mono, fontSize: 11.5, color }} data-lang-exempt="live">
      {text}
    </span>
  )

  // One line in the header on every tier: the chip never wraps, and on a phone
  // (390px shared with the title and the language switch) it is the glyph
  // alone with the words in title/aria-label.
  const liveGlyph = live.kind === 'ok' ? '●' : '○'
  const liveWords = live.kind === 'ok' ? ui.liveOk : live.kind === 'loading' ? ui.liveLoading : ui.liveOffline
  const liveBadge = (
    <span
      title={liveWords}
      aria-label={liveWords}
      style={{
        ...tagChip(false, false),
        cursor: 'default',
        whiteSpace: 'nowrap',
        flexShrink: 0,
        color: live.kind === 'ok' ? C.accent : live.kind === 'loading' ? C.muted : C.warn,
        borderColor: live.kind === 'ok' ? C.accent : live.kind === 'loading' ? C.border : C.warn,
      }}
    >
      {phone ? liveGlyph : `${liveGlyph} ${liveWords}`}
    </span>
  )

  const liveMeta = live.kind === 'loading' ? null : (
    <div style={{ fontFamily: C.mono, fontSize: 10.5, color: C.muted, lineHeight: 1.6, wordBreak: 'break-all' }}>
      {ui.liveAt} <span data-lang-exempt="live">{shortDate(live.fetchedAt)} UTC</span>
      {live.kind === 'ok' && live.status.generatedAt ? (
        <>
          {' · '}
          {ui.liveGenerated} <span data-lang-exempt="live">{shortDate(live.status.generatedAt)}</span>
        </>
      ) : null}
      {live.kind === 'offline' ? (
        <>
          {' · '}
          <span data-lang-exempt="live">{live.reason}</span>
        </>
      ) : null}
      {' · '}
      {ui.liveUrl} <span data-lang-exempt="live">{live.url}</span>
    </div>
  )

  const manifestCommit = catalog?.manifest?.generatedFrom?.commit ?? null

  return (
    <div
      className="spec-x"
      data-tier={viewport.tier}
      data-embedded={embedded ? '1' : undefined}
      style={{
        height: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        background: C.bg,
        color: C.text,
        fontFamily: "'Outfit', system-ui, sans-serif",
        overflow: 'hidden',
      }}
    >
      {!embedded && (
        <ExplorerHeader
          title={ui.title}
          subtitle={ui.subtitle}
          back={ui.back}
          note={ui.note}
          provenance={catalog?.manifest?.repo ? [{ repo: catalog.manifest.repo, shortCommit: (manifestCommit ?? '').slice(0, 7) }] : undefined}
          provenanceLabel={ui.manifestCommit}
          narrow={narrow}
          phone={phone}
          right={liveBadge}
        />
      )}
      <LayerLadder steps={ladderSteps} caption={ui.ladder} />

      <div style={{ flex: 1, display: 'flex', minHeight: 0, minWidth: 0 }}>
        {showList && (
          <ExplorerLibrary
            items={items}
            selectedId={selected?.id ?? null}
            onPick={(item) => pickById(item.id)}
            query={query}
            setQuery={setQuery}
            categories={Object.entries(counts?.byDomain ?? {}).map(([k, n]) => [k, k, n] as [string, string, number])}
            category={domain}
            setCategory={setDomain}
            filters={[
              { key: 'all', label: ui.filterAll, count: functions.length },
              { key: 'event', label: ui.filterEvent, count: nEvent, color: TRIGGER_COLOR.event, glyph: '⚡' },
              { key: 'cron', label: ui.filterCron, count: nCron, color: TRIGGER_COLOR.cron, glyph: '⟲' },
            ]}
            filter={triggerFilter}
            setFilter={(v) => setTriggerFilter(v as 'all' | FunctionTrigger)}
            stack={triggerSegments}
            tagCounts={tagCounts}
            tagFamilies={TAG_FAMILIES}
            tagSel={tagSel}
            toggleTag={(t) => setTagSel((prev) => (prev.includes(t) ? prev.filter((x) => x !== t) : [...prev, t]))}
            clearTags={() => setTagSel([])}
            tier={viewport.tier}
            countLabel={`${filtered.length} ${ui.functions}`}
            titlesAreGenerated
            ui={{
              search: ui.search,
              allCategories: `${ui.allDomains} (${functions.length})`,
              tags: ui.tags,
              clear: ui.clear,
              noResults: ui.noResults,
              noneInGroup: ui.noneInGroup,
              filters: ui.filters,
            }}
          />
        )}

        {showDetail && (
          <main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, minHeight: 0, overflowY: 'auto' }}>
            {err && (
              <div
                className="spec-x-banner"
                style={{
                  margin: '10px 14px 0',
                  padding: '9px 12px',
                  background: 'rgba(248,81,73,0.10)',
                  border: `1px solid ${C.bad}`,
                  borderRadius: 5,
                  fontSize: 12,
                  color: '#d8d8d8',
                }}
              >
                <span style={{ color: C.bad, fontWeight: 700 }}>⚠ {ui.failed}</span> <span data-lang-exempt="live">{err}</span>
              </div>
            )}
            {!selected && !err && <div style={{ padding: 24, color: C.muted, fontSize: 13 }}>{catalog ? ui.pickFunction : ui.loading}</div>}
            {selected && (
              <div data-card={selected.id} style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 12 }}>
                {phone && (
                  <button onClick={() => setPane('list')} className="spec-x-back" style={{ ...pill, alignSelf: 'flex-start' }}>
                    ← {ui.backToLibrary}
                  </button>
                )}
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <span
                    aria-hidden="true"
                    style={{
                      fontFamily: C.mono,
                      fontSize: 22,
                      fontWeight: 700,
                      lineHeight: 1,
                      color: TRIGGER_COLOR[selected.fields.TRIGGER],
                      minWidth: 36,
                      textAlign: 'center',
                      border: `1px solid ${C.borderBright}`,
                      borderRadius: 6,
                      padding: '5px 6px',
                    }}
                  >
                    {selected.fields.TRIGGER === 'cron' ? '⟲' : '⚡'}
                  </span>
                  <span style={{ fontSize: 15, fontWeight: 700 }} data-lang-exempt="live">
                    {selected.name[short] ?? selected.name.en}
                  </span>
                  <span style={{ fontFamily: C.mono, fontSize: 11, color: C.muted }} data-lang-exempt="live">
                    {selected.id} · {selected.fields.DOMAIN}
                  </span>
                  <span
                    style={{
                      ...tagChip(false, false),
                      cursor: 'default',
                      color: selected.code?.deployed === true ? C.accent : selected.code?.deployed === false ? C.bad : C.muted,
                      borderColor: selected.code?.deployed === true ? C.accent : selected.code?.deployed === false ? C.bad : C.border,
                    }}
                  >
                    {selected.code?.deployed === true ? `✓ ${ui.deployed}` : selected.code?.deployed === false ? `✕ ${ui.notDeployed}` : `? ${ui.deployUnknown}`}
                  </span>
                  <button onClick={copy} style={{ ...pill, color: copied ? C.accent : C.muted, marginLeft: 'auto' }}>
                    {copied ? ui.copied : ui.copyLink}
                  </button>
                </div>

                {/* The spec comes first: it is the statement about the function;
                    the boxes below are what the manifest and the live source saw. */}
                <AgentSpecPanel
                  lang={short}
                  kind="function"
                  id={selected.id}
                  entry={selected}
                  embedded={embedded}
                  flat={compact}
                  i18n={catalog?.i18n ?? []}
                  links={selected.cronSpec ? [{ id: selected.cronSpec, ok: true, href: cronExplorerHash(selected.cronSpec, { embedded }) }] : []}
                />

                {/* ---- live status of this function ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8, borderColor: live.kind === 'ok' ? C.border : 'rgba(240,160,32,0.4)' }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.live)}
                    {liveBadge}
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.liveHint}</div>
                  {live.kind === 'offline' && <div style={{ fontSize: 12, color: C.warn, lineHeight: 1.5 }}>{ui.liveOfflineHint}</div>}
                  {live.kind === 'ok' && !selectedLive && <div style={{ fontSize: 12, color: C.warn }}>{ui.liveNotReported}</div>}
                  <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap', alignItems: 'flex-start' }}>
                    <HealthRing
                      completed={selectedLive?.runs24h.completed ?? null}
                      failed={selectedLive?.runs24h.failed ?? null}
                      running={selectedLive?.runs24h.running ?? null}
                      ui={ui}
                      offline={liveOffline || !selectedLive}
                    />
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 6, minWidth: 220, flex: 1 }}>
                      {row(ui.runs7d, mono(selectedLive ? `${ui.completed} ${fmt(selectedLive.runs7d.completed, ui.unknown)} · ${ui.failedRuns} ${fmt(selectedLive.runs7d.failed, ui.unknown)} · ${ui.running} ${fmt(selectedLive.runs7d.running, ui.unknown)}` : ui.unknown))}
                      {row(
                        ui.lastRun,
                        selectedLive?.lastRun
                          ? mono(`${selectedLive.lastRun.status ?? ui.unknown} · ${shortDate(selectedLive.lastRun.endedAt)}${selectedLive.lastRun.id ? ` · ${selectedLive.lastRun.id}` : ''}`)
                          : liveText(selectedLive ? ui.noRunsYet : ui.unknown),
                      )}
                      {row(ui.lastError, selectedLive?.lastError ? mono(selectedLive.lastError, C.bad) : liveText(selectedLive ? '—' : ui.unknown))}
                    </div>
                  </div>
                  {liveMeta}
                </div>

                {/* ---- trigger ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {heading(ui.trigger)}
                  {row(ui.trigger.toLowerCase(), mono(selected.fields.TRIGGER, TRIGGER_COLOR[selected.fields.TRIGGER]))}
                  {selected.fields.TRIGGER === 'event' ? (
                    <>
                      {row(ui.event, mono(selected.fields.EVENT, C.golden))}
                      {row(ui.legacyEvents, selected.fields.LEGACY_EVENTS.length ? mono(selected.fields.LEGACY_EVENTS.join(' · ')) : liveText(ui.noLegacyEvents))}
                    </>
                  ) : (
                    <>
                      {row(ui.cron, mono(selected.fields.CRON, C.golden))}
                      {row(ui.tz, mono(selected.fields.TZ))}
                      {row(
                        ui.cronCard,
                        selected.cronSpec ? (
                          <a className="spec-x-target" href={cronExplorerHash(selected.cronSpec, { embedded })} style={{ ...tagChip(false, false), color: C.accent, borderColor: C.borderBright, textDecoration: 'none' }} data-lang-exempt="live">
                            ⟲ {selected.cronSpec}
                          </a>
                        ) : (
                          <span style={{ color: C.warn }}>{ui.noCronCard}</span>
                        ),
                      )}
                    </>
                  )}
                  {row(ui.legacyId, mono(selected.fields.LEGACY_ID))}
                  {row(ui.retries, mono(String(selected.fields.RETRIES)))}
                  {row(ui.onFailure, mono(selected.fields.ON_FAILURE, selected.fields.ON_FAILURE === 'log' ? C.warn : C.text))}
                  {row(
                    ui.guard,
                    selected.fields.GUARD === 'unknown' ? liveText(ui.guardUnknown) : selected.fields.GUARD && selected.fields.GUARD !== 'none' ? mono(selected.fields.GUARD) : liveText(ui.noGuard),
                  )}
                </div>

                {/* ---- steps ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                    {heading(ui.steps)}
                    <span style={{ fontFamily: C.mono, fontSize: 11.5, color: C.muted }} data-lang-exempt="live">
                      {selected.fields.STEPS.length}
                    </span>
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }} data-lang-exempt="live">
                    {ui.stepsHint}
                  </div>
                  <ol style={{ margin: 0, paddingLeft: 22, display: 'flex', flexDirection: 'column', gap: 2 }} data-lang-exempt="live">
                    {selected.fields.STEPS.map((s, i) => (
                      <li key={i} style={{ fontFamily: C.mono, fontSize: 11.5, color: s === selected.fields.GUARD ? C.golden : '#d8d8d8' }}>
                        {s}
                        {s === selected.fields.GUARD ? <span style={{ color: C.muted }}> ← {ui.guard}</span> : null}
                      </li>
                    ))}
                  </ol>
                </div>

                {/* ---- side effects ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.sideEffects)}
                  <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                    {selected.fields.SIDE_EFFECTS.map((s) => (
                      <span key={s} style={{ ...tagChip(false, false), cursor: 'default', color: SIDE_EFFECT_COLOR[s] ?? C.text, borderColor: SIDE_EFFECT_COLOR[s] ?? C.border }}>
                        ● {SIDE_EFFECT_LABEL[s]?.[short] ?? s}
                      </span>
                    ))}
                  </div>
                </div>

                {/* ---- safe probe ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.probe)}
                    <span
                      style={{
                        ...tagChip(false, false),
                        cursor: 'default',
                        color: selected.fields.PROBE_RESULT === 'COMPLETED' ? C.accent : selected.fields.PROBE_RESULT === 'FAILED-at-guard' ? C.golden : selected.fields.PROBE_RESULT === 'not-deployed' ? C.bad : C.muted,
                      }}
                      data-lang-exempt="live"
                    >
                      {ui.probeResult}: {selected.fields.PROBE_RESULT}
                    </span>
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.probeHint}</div>
                  {selected.fields.SAFE_PROBE && selected.fields.PROBE_RESULT !== 'skipped' && selected.fields.PROBE_RESULT !== 'not-deployed' ? (
                    <pre style={{ margin: 0, fontFamily: C.mono, fontSize: 11, color: '#d8d8d8', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }} data-lang-exempt="live">
                      {selected.fields.SAFE_PROBE}
                    </pre>
                  ) : (
                    <div style={{ fontSize: 12, color: C.muted }}>{ui.noProbe}</div>
                  )}
                </div>

                {/* ---- source & witness ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {heading(ui.source)}
                  {row(
                    ui.file,
                    (() => {
                      const url = functionSourceUrl(selected.fields.REPO, selected.fields.SERVICE, manifestCommit)
                      return url ? (
                        <a href={url} target="_blank" rel="noopener noreferrer" style={{ fontFamily: C.mono, fontSize: 11.5, color: C.accent }} data-lang-exempt="live">
                          {selected.fields.REPO}:{selected.fields.SERVICE} ↗
                        </a>
                      ) : (
                        mono(`${selected.fields.REPO}:${selected.fields.SERVICE}`)
                      )
                    })(),
                  )}
                  {row(ui.witness, mono(selected.witness, selected.witness === 'spec+code' ? C.accent : C.warn))}
                  {manifestCommit ? row(ui.manifestCommit, mono(`${catalog?.manifest?.repo ?? ''} @${manifestCommit}${catalog?.manifest?.probedAt ? ` · ${catalog.manifest.probedAt}` : ''}`)) : null}
                  {selected.differences.length === 0 ? (
                    <div style={{ fontSize: 11.5, color: C.muted }}>{selected.code ? ui.noDifferences : '—'}</div>
                  ) : (
                    <div>
                      <div style={{ fontSize: 11.5, color: C.warn, marginBottom: 4 }}>⚠ {ui.differences}</div>
                      <ul style={{ margin: 0, paddingLeft: 18, fontFamily: C.mono, fontSize: 11, color: '#d8d8d8', lineHeight: 1.6 }} data-lang-exempt="live">
                        {selected.differences.map((d) => (
                          <li key={d.field}>
                            {d.field}: spec {JSON.stringify(d.spec)} · manifest {JSON.stringify(d.code)}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {selected.fields.NOTE ? row(ui.noteLabel, liveText(selected.fields.NOTE)) : null}
                </div>

                {/* ---- fleet infographics: every function, from the specs and the live source ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.healthRing)}
                    <span style={{ fontSize: 11, color: C.muted }}>· {ui.all}</span>
                    {liveBadge}
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.healthRingHint}</div>
                  <HealthRing completed={totals24.completed} failed={totals24.failed} running={totals24.running} ui={ui} offline={liveOffline} />
                </div>

                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.breakdown)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.breakdownHint}</div>
                  <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.byTrigger}</div>
                  <StackBar segments={triggerSegments} />
                  <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.bySideEffect}</div>
                  <StackBar segments={sideEffectSegments} />
                </div>

                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.bars7d)}
                    {liveBadge}
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.bars7dHint}</div>
                  {live.kind === 'offline' && <div style={{ fontSize: 12, color: C.warn }}>{ui.liveOffline} — {ui.liveOfflineHint}</div>}
                  <Bars7d rows={liveRows} ui={ui} selectedId={selected.id} onPick={pickById} />
                </div>

                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
                    {heading(ui.timeline)}
                    {liveBadge}
                  </div>
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.timelineHint}</div>
                  {live.kind === 'offline' ? <div style={{ fontSize: 12, color: C.warn }}>{ui.liveOffline}</div> : <LastRunTimeline rows={liveRows} ui={ui} now={now} selectedId={selected.id} onPick={pickById} />}
                  {liveMeta}
                </div>
              </div>
            )}
          </main>
        )}
      </div>
    </div>
  )
}
