// Provider Explorer -- who sells compute, and what a person could rent out for $TRI.
//
// The seventh step of the site's ladder: Specs → Skills → Crons → Agents → Tools →
// Functions → Providers. A provider card is generated by scripts/agents-from-specs.mjs
// from specs/providers/<network>/<slug>.t27 through the real compiler and checked
// against the schema in specs/providers/catalog.t27. Two families: a model the Gonka
// chain lists (every number copied from a public chain endpoint on the card's CHECKED
// date), and a class of hardware a person could rent out to TRI-NET for $TRI (an
// Artix-7 FPGA measured on three boards, a 24 GB gaming GPU that is a design only).
// specs/providers/tri_gnk_pair.t27 is the study under both: how Gonka pays its hosts,
// the routes a $TRI/GNK pair could take, and where the two networks differ.
//
// Three things this page never does. It never calls a model: every Gonka inference is
// paid and signed (catalog.t27 CALL_RULE), so it shows the request and sends nothing.
// It never asks for a key or a wallet. And it never shows a Gonka host's address: the
// host count is read from the epoch's participants and nothing else of them is kept
// (lib/gonkaLive). The chain is re-read only when the reader asks, from the reader's
// browser, and every distance between a card and the chain is printed, not smoothed.

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useI18n } from '../i18n/context'
import { usePageMeta } from '../hooks/usePageMeta'
import { useHashParams } from '../hooks/useHashParams'
import { useDocumentLock, useViewport } from '../lib/useViewport'
import { HEADER_CHROME_MAX } from '../lib/viewport.generated'
import { ExplorerHeader } from '../components/ExplorerHeader'
import { ExplorerLibrary, type ExplorerItem } from '../components/ExplorerLibrary'
import { AgentSpecPanel } from '../components/AgentSpecPanel'
import { LayerLadder, type LadderStep } from '../components/LayerLadder'
import {
  canonicalSpecEditUrl,
  loadProviderSpecs,
  vendoredSpecUrl,
  type ProviderHostEntry,
  type ProviderModelEntry,
  type ProviderSpecCatalog,
  type ProviderSpecEntry,
  type ProviderStatus,
} from '../lib/agentSpecs'
import { providerExplorerHash, canonicalProviderUrl, resolveProvider } from '../lib/providersCatalog'
import {
  GONKA_MODELS_URL,
  GONKA_PARAMS_URL,
  GONKA_PARTICIPANTS_URL,
  GONKA_PRICING_URL,
  chainDistance,
  parseModelsAll,
  parseParticipants,
  parsePocModels,
  parsePricing,
  type ChainRead,
} from '../lib/gonkaLive'
import { C, panelBox, pill, tagChip } from '../lib/explorerTheme'

const UI = {
  en: {
    title: 'Provider Explorer',
    subtitle: 'Who sells compute, and what a person could rent out for TRI',
    metaTitle: 'Provider Explorer',
    metaDescription:
      'Every model the Gonka network sells, copied from its chain, beside the hardware a person could rent out to TRI-NET for TRI: an Artix-7 FPGA measured on three boards and a 24 GB gaming GPU that is still a design. Each card is a .t27 spec; the page re-reads the Gonka chain on request and prints every difference.',
    note: 'Generated from specs/providers/{gonka,trinet}/*.t27, not typed by hand',
    back: '← Home',
    search: 'Search by model, device or text',
    allNetworks: 'Both networks',
    networkGonka: 'Gonka models',
    networkTrinet: 'TRI-NET hosts',
    tags: 'Tags',
    clear: 'Clear',
    providersCount: 'providers',
    noResults: 'No provider matches',
    noneInGroup: 'None in this network',
    loading: 'loading the catalog…',
    failed: 'Could not load the provider catalog:',
    pickProvider: 'Pick a provider',
    backToLibrary: 'All providers',
    filters: 'Filters',
    filterAll: 'All',
    statusServing: 'serving',
    statusListed: 'listed, no host',
    statusMeasured: 'measured',
    statusPlanned: 'design only',
    ladder: 'ladder',
    ladderSpecs: 'Specs',
    ladderSkills: 'Skills',
    ladderCrons: 'Crons',
    ladderAgents: 'Agents',
    ladderTools: 'Tools',
    ladderFunctions: 'Functions',
    ladderProviders: 'Providers',
    copyLink: 'Copy link',
    copied: 'Copied',
    enabledOff: 'disabled',
    hosts: 'hosts',
    onChain: 'ON THE CHAIN',
    onChainHint: 'Copied from the Gonka chain on the date the card names; the column on the right is what the chain says now, once you ask it.',
    field: 'field',
    card: 'card',
    chainNow: 'chain now',
    notRead: 'not read',
    modelId: 'model',
    hfCommit: 'weights',
    hostsServing: 'hosts serving it',
    hostsOf: 'of {n} active in epoch {e}',
    vram: 'GPU memory per host',
    context: 'context',
    tokens: 'tokens',
    throughput: 'throughput per nonce',
    validation: 'validation threshold',
    pocModel: 'raced by Proof of Compute',
    pocWeight: 'PoC weight scale',
    yes: 'yes',
    no: 'no',
    unitsPerToken: 'units of compute per token',
    price: 'price per token',
    perMillion: 'per million tokens',
    perMillionNote: 'if the unit is ngonka, as the Gonka docs state; the pricing endpoint names none',
    callHeading: 'HOW TO CALL IT',
    callHint: 'Every request is paid and signed by a funded Gonka account, so this page shows the request and never sends it. It never asks for a key.',
    callBody: 'request body',
    serveHeading: 'WHAT A HOST NEEDS TO SERVE IT',
    serveHint: 'The memory is the chain’s v_ram for this model; the card counts are that memory divided by one card, rounded up.',
    consumerCards: '{gb} GB gaming cards',
    datacenterCards: '{gb} GB datacenter cards',
    vllmArgs: 'vLLM arguments the chain sets',
    hostHeading: 'THE HARDWARE',
    device: 'device',
    memory: 'memory',
    memoryNone: 'not what bounds its jobs',
    perGonkaNode: 'per Gonka ML node',
    cannotHostGonka: 'cannot serve any Gonka model',
    unitsOfThis: '{n} of these',
    proof: 'how work is checked',
    reward: 'what it pays',
    stake: 'stake and slash',
    gonkaParallel: 'against Gonka',
    measured: 'MEASURED',
    measuredHint: 'Runs on our own boards, each naming the record a reader can rerun.',
    nothingMeasured: 'Nothing has run: this card is a design, and a design never claims a measurement.',
    gaps: 'WHAT IS MISSING',
    gapsHint: 'Written as plainly as the measurements. Until these close, nobody is paid for this hardware.',
    token: 'token',
    sources: 'SOURCES',
    sourcesHint: 'Where every number on the card was read, as of the date it names.',
    checked: 'checked',
    noteLabel: 'note',
    witness: 'witness',
    marketHeading: 'THE MODELS GONKA SELLS',
    marketHint: 'One row per model the chain lists. A listed model with no host is on the chain and served by nobody.',
    status: 'status',
    liveHeading: 'RE-READ THE CHAIN',
    liveHint: 'Reads the public Gonka node from your browser and compares every model card with it. Nothing is sent but the request; no key, no account.',
    liveRead: 'Re-read the Gonka chain',
    liveHosts: 'Count the hosts (about 0.5 MB)',
    liveHostsHint: 'The epoch’s participant list carries its proofs, so it is read only on request; only each host’s model list is kept, never its address.',
    liveIdle: 'Not compared yet: the numbers above are the cards’ copy of {d}.',
    liveLoading: 'reading…',
    liveOk: 'Read at {t}: {n} differences between the cards and the chain.',
    liveSame: 'Read at {t}: every card matches the chain.',
    liveFailed: 'The chain did not answer: {e}. The numbers above are the cards’ copy of {d}; nothing was compared.',
    liveEpoch: 'The chain is in epoch {e} now; host counts on the cards are of epoch {c}.',
    uncarded: 'The chain lists a model no card states:',
    unlisted: 'A card names a model the chain no longer lists:',
    differences: 'differences',
    studyHeading: 'A $TRI/GNK PAIR',
    studyHint: 'From specs/providers/tri_gnk_pair.t27. Its test blocks check the arithmetic it states.',
    conflict: 'the conflict',
    routes: 'routes',
    pairFacts: 'what exists today',
    triChains: 'TRI is issued on',
    triMainnet: 'TRI on a mainnet',
    triCap: 'TRI cap',
    gonkaPool: 'Gonka DEX pool registered',
    bridge: 'Gonka bridge goes to',
    wgnk: 'WGNK on Ethereum',
    wgnkPool: 'WGNK/USDT Uniswap v3 pool',
    approved: 'approved for trade on Gonka',
    ibc: 'IBC channels',
    paysHeading: 'HOW GONKA PAYS ITS HOSTS',
    paysHint: 'Read from the chain on the study’s CHECKED date; GNK amounts are ngonka divided by 10^9, exactly.',
    epoch: 'epoch',
    activeHosts: 'active hosts',
    height: 'chain height',
    supply: 'supply',
    fees: 'all fees paid',
    subsidies: 'all subsidies issued',
    subsidyPerFee: 'subsidy per unit of fee',
    burned: 'burned',
    initialReward: 'initial epoch reward',
    vesting: 'reward vesting',
    vestingValue: '{n} epochs, about {d} days',
    baseWeight: 'weight needing no collateral',
    slashInvalid: 'slashed for invalid work',
    slashDowntime: 'slashed for downtime',
    allowlist: 'host allowlist',
    allowlistActive: 'active until height {h}',
    allowlistInactive: 'inactive: it ended at height {h}, the chain is at {c}',
    nodeHeading: 'WHAT A GONKA NODE NEEDS',
    nodeHint: 'Gonka admitted consumer cards from a {min} GB minimum and stopped; the models it serves now need this much memory per host.',
    smallestModel: 'smallest model raced',
    mostServedModel: 'most served model',
    largestModel: 'largest model raced',
    cardsOf: '{n} cards of {gb} GB',
    parallels: 'PARALLELS',
    parallelsHint: 'Where TRI-NET would do what Gonka does, and where it would not.',
    openStudy: 'Read the study',
    editSpec: 'Edit in the spec →',
    gnk: 'GNK',
  },
  ru: {
    title: 'Обозреватель провайдеров',
    subtitle: 'Кто продаёт вычисления и что человек мог бы сдать в аренду за TRI',
    metaTitle: 'Обозреватель провайдеров',
    metaDescription:
      'Каждая модель, которую продаёт сеть Gonka, скопированная с её цепи, рядом с железом, которое человек мог бы сдать в аренду TRI-NET за TRI: FPGA Artix-7, измеренная на трёх платах, и игровая GPU на 24 ГБ, которая пока только проект. Каждая карточка — спека .t27; страница по запросу перечитывает цепь Gonka и печатает каждое расхождение.',
    note: 'Сгенерировано из specs/providers/{gonka,trinet}/*.t27, а не набрано вручную',
    back: '← На главную',
    search: 'Поиск по модели, устройству или тексту',
    allNetworks: 'Обе сети',
    networkGonka: 'Модели Gonka',
    networkTrinet: 'Хосты TRI-NET',
    tags: 'Теги',
    clear: 'Сбросить',
    providersCount: 'провайдеров',
    noResults: 'Ни один провайдер не подходит',
    noneInGroup: 'В этой сети нет',
    loading: 'загружаю каталог…',
    failed: 'Не удалось загрузить каталог провайдеров:',
    pickProvider: 'Выберите провайдера',
    backToLibrary: 'Все провайдеры',
    filters: 'Фильтры',
    filterAll: 'Все',
    statusServing: 'обслуживается',
    statusListed: 'в списке, без хоста',
    statusMeasured: 'измерено',
    statusPlanned: 'только проект',
    ladder: 'лестница',
    ladderSpecs: 'Спеки',
    ladderSkills: 'Скиллы',
    ladderCrons: 'Кроны',
    ladderAgents: 'Агенты',
    ladderTools: 'Инструменты',
    ladderFunctions: 'Функции',
    ladderProviders: 'Провайдеры',
    copyLink: 'Скопировать ссылку',
    copied: 'Скопировано',
    enabledOff: 'выключен',
    hosts: 'хостов',
    onChain: 'НА ЦЕПИ',
    onChainHint: 'Скопировано с цепи Gonka в дату, которую называет карточка; правая колонка — то, что цепь говорит сейчас, когда вы её спросите.',
    field: 'поле',
    card: 'карточка',
    chainNow: 'цепь сейчас',
    notRead: 'не прочитано',
    modelId: 'модель',
    hfCommit: 'веса',
    hostsServing: 'хостов обслуживают',
    hostsOf: 'из {n} активных в эпохе {e}',
    vram: 'память GPU на хост',
    context: 'контекст',
    tokens: 'токенов',
    throughput: 'пропускная способность на nonce',
    validation: 'порог валидации',
    pocModel: 'участвует в Proof of Compute',
    pocWeight: 'масштаб веса PoC',
    yes: 'да',
    no: 'нет',
    unitsPerToken: 'единиц вычисления на токен',
    price: 'цена за токен',
    perMillion: 'за миллион токенов',
    perMillionNote: 'если единица — ngonka, как пишет документация Gonka; эндпоинт цен единицу не называет',
    callHeading: 'КАК ЕЁ ВЫЗВАТЬ',
    callHint: 'Каждый запрос оплачивается и подписывается пополненным аккаунтом Gonka, поэтому страница показывает запрос и никогда его не отправляет. Ключ она не просит.',
    callBody: 'тело запроса',
    serveHeading: 'ЧТО НУЖНО ХОСТУ, ЧТОБЫ ЕЁ ОБСЛУЖИВАТЬ',
    serveHint: 'Память — это v_ram цепи для этой модели; число карт — эта память, делённая на одну карту, с округлением вверх.',
    consumerCards: 'игровых карт по {gb} ГБ',
    datacenterCards: 'серверных карт по {gb} ГБ',
    vllmArgs: 'аргументы vLLM, которые задаёт цепь',
    hostHeading: 'ЖЕЛЕЗО',
    device: 'устройство',
    memory: 'память',
    memoryNone: 'не она ограничивает его задания',
    perGonkaNode: 'на один ML-узел Gonka',
    cannotHostGonka: 'не может обслуживать ни одну модель Gonka',
    unitsOfThis: '{n} таких',
    proof: 'как проверяется работа',
    reward: 'что она платит',
    stake: 'залог и штраф',
    gonkaParallel: 'в сравнении с Gonka',
    measured: 'ИЗМЕРЕНО',
    measuredHint: 'Прогоны на наших собственных платах, каждый с записью, которую читатель может повторить.',
    nothingMeasured: 'Ничего не запускалось: эта карточка — проект, а проект никогда не заявляет измерений.',
    gaps: 'ЧЕГО НЕ ХВАТАЕТ',
    gapsHint: 'Написано так же прямо, как измерения. Пока это не закрыто, за это железо никому не платят.',
    token: 'токен',
    sources: 'ИСТОЧНИКИ',
    sourcesHint: 'Где прочитано каждое число карточки, на дату, которую она называет.',
    checked: 'проверено',
    noteLabel: 'примечание',
    witness: 'свидетель',
    marketHeading: 'МОДЕЛИ, КОТОРЫЕ ПРОДАЁТ GONKA',
    marketHint: 'По строке на каждую модель в списке цепи. Модель в списке без хоста есть на цепи, но её никто не обслуживает.',
    status: 'статус',
    liveHeading: 'ПЕРЕЧИТАТЬ ЦЕПЬ',
    liveHint: 'Читает публичный узел Gonka из вашего браузера и сравнивает с ним каждую карточку модели. Отправляется только сам запрос: ни ключа, ни аккаунта.',
    liveRead: 'Перечитать цепь Gonka',
    liveHosts: 'Посчитать хосты (около 0,5 МБ)',
    liveHostsHint: 'Список участников эпохи несёт её доказательства, поэтому читается только по запросу; от каждого хоста сохраняется лишь список моделей, никогда не адрес.',
    liveIdle: 'Ещё не сравнивали: числа выше — копия карточек на {d}.',
    liveLoading: 'читаю…',
    liveOk: 'Прочитано в {t}: расхождений между карточками и цепью — {n}.',
    liveSame: 'Прочитано в {t}: каждая карточка совпадает с цепью.',
    liveFailed: 'Цепь не ответила: {e}. Числа выше — копия карточек на {d}; ничего не сравнивалось.',
    liveEpoch: 'Цепь сейчас в эпохе {e}; число хостов в карточках — для эпохи {c}.',
    uncarded: 'Цепь перечисляет модель, которой нет ни в одной карточке:',
    unlisted: 'Карточка называет модель, которой больше нет в списке цепи:',
    differences: 'расхождения',
    studyHeading: 'ПАРА $TRI/GNK',
    studyHint: 'Из specs/providers/tri_gnk_pair.t27. Её блоки test проверяют арифметику, которую она утверждает.',
    conflict: 'противоречие',
    routes: 'пути',
    pairFacts: 'что есть сегодня',
    triChains: 'TRI выпускается в',
    triMainnet: 'TRI в основной сети',
    triCap: 'потолок TRI',
    gonkaPool: 'пул на DEX Gonka зарегистрирован',
    bridge: 'мост Gonka ведёт в',
    wgnk: 'WGNK в Ethereum',
    wgnkPool: 'пул WGNK/USDT в Uniswap v3',
    approved: 'одобрено для торговли в Gonka',
    ibc: 'каналы IBC',
    paysHeading: 'КАК GONKA ПЛАТИТ СВОИМ ХОСТАМ',
    paysHint: 'Прочитано с цепи в дату CHECKED исследования; суммы в GNK — это ngonka, делённые на 10^9, точно.',
    epoch: 'эпоха',
    activeHosts: 'активных хостов',
    height: 'высота цепи',
    supply: 'эмиссия',
    fees: 'всего уплачено комиссий',
    subsidies: 'всего выдано субсидий',
    subsidyPerFee: 'субсидии на единицу комиссии',
    burned: 'сожжено',
    initialReward: 'начальная награда за эпоху',
    vesting: 'вестинг награды',
    vestingValue: '{n} эпох, около {d} дней',
    baseWeight: 'вес без залога',
    slashInvalid: 'штраф за неверную работу',
    slashDowntime: 'штраф за простой',
    allowlist: 'белый список хостов',
    allowlistActive: 'действует до высоты {h}',
    allowlistInactive: 'не действует: закончился на высоте {h}, цепь на {c}',
    nodeHeading: 'ЧТО НУЖНО УЗЛУ GONKA',
    nodeHint: 'Gonka принимала игровые карты при минимуме {min} ГБ и перестала; моделям, которые она обслуживает сейчас, нужно столько памяти на хост.',
    smallestModel: 'самая маленькая модель в гонке',
    mostServedModel: 'самая обслуживаемая модель',
    largestModel: 'самая большая модель в гонке',
    cardsOf: '{n} карт по {gb} ГБ',
    parallels: 'ПАРАЛЛЕЛИ',
    parallelsHint: 'Где TRI-NET делала бы то же, что Gonka, а где нет.',
    openStudy: 'Читать исследование',
    editSpec: 'Изменить в спеке →',
    gnk: 'GNK',
  },
} as const

type Ui = Record<keyof typeof UI.en, string>

const TAG_FAMILIES = [
  { prefix: 'network/', label: 'network' },
  { prefix: 'family/', label: 'family' },
  { prefix: 'status/', label: 'status' },
  { prefix: 'witness/', label: 'witness' },
]

function tagsOf(p: ProviderSpecEntry): string[] {
  return [`network/${p.network}`, `family/${p.family}`, `status/${p.status}`, `witness/${p.witness}`]
}

const STATUS_COLOR: Record<ProviderStatus, string> = { serving: C.accent, listed: C.warn, measured: C.accent, planned: C.warn }

/** `{name}` placeholders in a dictionary string. */
function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (all, key: string) => (key in vars ? String(vars[key]) : all))
}

/** An exact decimal string divided by 10^decimals, grouped for the locale; `digits` caps the fraction, trailing zeros dropped. */
function formatScaled(raw: string, decimals: number, digits: number, locale: string): string {
  if (!/^[0-9]+$/.test(raw)) return raw
  const n = BigInt(raw)
  const base = 10n ** BigInt(decimals)
  const nf = new Intl.NumberFormat(locale)
  const whole = nf.format(n / base)
  const fraction = (n % base).toString().padStart(decimals, '0').slice(0, digits).replace(/0+$/, '')
  if (!fraction) return whole
  const sep = nf.formatToParts(1.5).find((p) => p.type === 'decimal')?.value ?? '.'
  return `${whole}${sep}${fraction}`
}

const ceilDiv = (a: number, b: number) => (b > 0 ? Math.ceil(a / b) : 0)

/** A SOURCES entry as a link: a URL, or gHashTag/<repo>[@<commit>]:<path> on GitHub; anything else is text. */
function sourceLink(source: string): { href: string | null; text: string } {
  const url = /^(https?:\/\/\S+)/.exec(source)
  if (url) return { href: url[1], text: source }
  const repo = /^([A-Za-z0-9-]+\/[A-Za-z0-9._-]+)(?:@([0-9a-f]{7,40}))?:(\S+)$/.exec(source)
  if (repo) return { href: `https://github.com/${repo[1]}/blob/${repo[2] ?? 'HEAD'}/${repo[3]}`, text: source }
  return { href: null, text: source }
}

/** "name: text" as a bold name and its text; a string without the colon is all text. */
function splitLead(s: string): { lead: string | null; rest: string } {
  const i = s.indexOf(': ')
  return i > 0 && i < 48 ? { lead: s.slice(0, i), rest: s.slice(i + 2) } : { lead: null, rest: s }
}

const isModel = (p: ProviderSpecEntry): p is ProviderModelEntry => p.family === 'model'
const isHost = (p: ProviderSpecEntry): p is ProviderHostEntry => p.family === 'host-class'

type Live =
  | { state: 'idle' }
  | { state: 'loading'; read: ChainRead; at: string | null }
  | { state: 'ok'; read: ChainRead; at: string }
  | { state: 'failed'; read: ChainRead; at: string | null; error: string }

async function getJson(url: string): Promise<unknown> {
  const abort = new AbortController()
  const timer = window.setTimeout(() => abort.abort(), 20000)
  try {
    const r = await fetch(url, { credentials: 'omit', cache: 'no-store', signal: abort.signal })
    if (!r.ok) throw new Error(`HTTP ${r.status} from ${new URL(url).pathname}`)
    return await r.json()
  } finally {
    window.clearTimeout(timer)
  }
}

export default function ProviderExplorer() {
  const { lang } = useI18n()
  const ui: Ui = lang === 'ru' ? UI.ru : UI.en
  const short = lang === 'ru' ? 'ru' : 'en'
  const locale = short === 'ru' ? 'ru-RU' : 'en-US'
  usePageMeta(ui.metaTitle, ui.metaDescription)
  const params = useHashParams()
  const embedded = params.embedded

  const [catalog, setCatalog] = useState<ProviderSpecCatalog | null>(null)
  const [selected, setSelected] = useState<ProviderSpecEntry | null>(null)
  const [err, setErr] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [network, setNetwork] = useState('')
  const [statusFilter, setStatusFilter] = useState<'all' | ProviderStatus>('all')
  const [tagSel, setTagSel] = useState<string[]>([])
  const [copied, setCopied] = useState(false)
  const [live, setLive] = useState<Live>({ state: 'idle' })
  const viewport = useViewport()
  const phone = viewport.tier === 'phone'
  const compact = phone || viewport.tier === 'tablet'
  const narrow = viewport.width < HEADER_CHROME_MAX
  useDocumentLock(compact)
  const [pane, setPane] = useState<'list' | 'detail'>('list')

  const pick = useCallback(
    (entry: ProviderSpecEntry) => {
      // The address first: an id it refuses must not leave a half-applied selection behind it.
      const hash = providerExplorerHash(entry.id, { embedded })
      setSelected(entry)
      params.set(hash)
    },
    [embedded, params],
  )

  useEffect(() => {
    let alive = true
    loadProviderSpecs()
      .then((c) => {
        if (!alive) return
        setCatalog(c)
        const wanted = params.get('provider')
        try {
          const target = resolveProvider(c, wanted)
          if (wanted) setPane('detail')
          pick(target)
        } catch (e) {
          setErr(String(e instanceof Error ? e.message : e))
          setPane('detail')
        }
      })
      .catch((e) => {
        if (!alive) return
        setErr(String(e instanceof Error ? e.message : e))
        setPane('detail')
      })
    return () => {
      alive = false
    }
    // Mount only: the deep link is read once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // A deep link that arrives after mount: open that card, on a phone as the card pane.
  useEffect(() => {
    if (!catalog || params.changes === 0) return
    const wanted = params.get('provider')
    if (!wanted) return
    try {
      const target = resolveProvider(catalog, wanted)
      setPane('detail')
      if (target !== selected) pick(target)
    } catch {
      // An unknown id in a later hash: keep the card that is open.
    }
    // Only the hash counter: the catalog and the selection are read, not followed.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params.changes])

  const providers = useMemo(() => catalog?.providers ?? [], [catalog])
  const models = useMemo(() => providers.filter(isModel), [providers])
  const study = catalog?.study ?? null

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return providers.filter((p) => {
      if (network && p.network !== network) return false
      if (statusFilter !== 'all' && p.status !== statusFilter) return false
      if (tagSel.length) {
        const tags = tagsOf(p)
        if (!tagSel.every((x) => tags.includes(x))) return false
      }
      if (!q) return true
      return p.searchText.includes(q) || (p.summary[short] ?? '').toLowerCase().includes(q)
    })
  }, [providers, query, network, statusFilter, tagSel, short])

  const tagCounts = useMemo(() => {
    const acc: Record<string, number> = {}
    for (const p of filtered) for (const x of tagsOf(p)) acc[x] = (acc[x] ?? 0) + 1
    return acc
  }, [filtered])

  const statusLabel: Record<ProviderStatus, string> = { serving: ui.statusServing, listed: ui.statusListed, measured: ui.statusMeasured, planned: ui.statusPlanned }

  const items: ExplorerItem[] = useMemo(
    () =>
      filtered.map((p) => ({
        id: p.id,
        title: p.name.en,
        subtitle: isModel(p) ? `${p.fields.HOSTS} ${ui.hosts} · ${p.fields.VRAM_GB} GB · ${p.fields.MODEL_ID}` : p.fields.DEVICE.split('.')[0],
        badge: p.fields.ENABLED ? (p.status === 'serving' ? undefined : p.status) : ui.enabledOff,
        badgeColor: STATUS_COLOR[p.status],
        health: p.health,
        tags: tagsOf(p),
        haystack: p.searchText,
      })),
    [filtered, ui.hosts, ui.enabledOff],
  )

  const copy = useCallback(() => {
    if (!selected) return
    navigator.clipboard?.writeText(canonicalProviderUrl(selected.id)).then(
      () => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1400)
      },
      () => {},
    )
  }, [selected])

  // ---- the chain, re-read on request ----
  const readChain = useCallback(async () => {
    setLive((prev) => ({ state: 'loading', read: prev.state === 'idle' ? {} : prev.read, at: prev.state === 'idle' ? null : prev.at }))
    try {
      const [m, p, pr] = await Promise.all([getJson(GONKA_MODELS_URL), getJson(GONKA_PARAMS_URL), getJson(GONKA_PRICING_URL)])
      const fresh: ChainRead = { models: parseModelsAll(m), poc: parsePocModels(p), pricing: parsePricing(pr) }
      setLive((prev) => ({ state: 'ok', read: { ...(prev.state === 'idle' ? {} : prev.read), ...fresh }, at: new Date().toLocaleTimeString(locale) }))
    } catch (e) {
      setLive((prev) => ({ state: 'failed', read: prev.state === 'idle' ? {} : prev.read, at: prev.state === 'idle' ? null : prev.at, error: String(e instanceof Error ? e.message : e) }))
    }
  }, [locale])

  const readHosts = useCallback(async () => {
    setLive((prev) => ({ state: 'loading', read: prev.state === 'idle' ? {} : prev.read, at: prev.state === 'idle' ? null : prev.at }))
    try {
      const participants = parseParticipants(await getJson(GONKA_PARTICIPANTS_URL))
      setLive((prev) => ({ state: 'ok', read: { ...(prev.state === 'idle' ? {} : prev.read), participants }, at: new Date().toLocaleTimeString(locale) }))
    } catch (e) {
      setLive((prev) => ({ state: 'failed', read: prev.state === 'idle' ? {} : prev.read, at: prev.state === 'idle' ? null : prev.at, error: String(e instanceof Error ? e.message : e) }))
    }
  }, [locale])

  const read = live.state === 'idle' ? null : live.read
  const distance = useMemo(() => (read && Object.keys(read).length ? chainDistance(models, read) : null), [models, read])
  const diffsOf = useCallback((id: string) => distance?.differences.filter((d) => d.providerId === id) ?? [], [distance])

  const box = panelBox(embedded)
  const showList = !phone || pane === 'list'
  const showDetail = !phone || pane === 'detail'
  const counts = catalog?.counts

  const ladderSteps: LadderStep[] = useMemo(() => {
    const l = catalog?.ladder
    const embed = embedded ? '?embed=1' : ''
    return [
      { key: 'specs', label: ui.ladderSpecs, count: l?.specs ?? null, href: `#/specs${embed}` },
      { key: 'skills', label: ui.ladderSkills, count: l?.skills ?? null, href: `#/skills${embed}` },
      { key: 'crons', label: ui.ladderCrons, count: l?.crons ?? null, href: `#/crons${embed}` },
      { key: 'agents', label: ui.ladderAgents, count: l?.agents ?? null, href: `#/agents${embed}` },
      { key: 'tools', label: ui.ladderTools, count: l?.tools ?? null, href: `#/tools${embed}` },
      { key: 'functions', label: ui.ladderFunctions, count: l?.functions ?? null, href: `#/functions${embed}` },
      { key: 'providers', label: ui.ladderProviders, count: l?.providers ?? null, href: `#/providers${embed}`, current: true },
    ]
  }, [catalog, embedded, ui.ladderSpecs, ui.ladderSkills, ui.ladderCrons, ui.ladderAgents, ui.ladderTools, ui.ladderFunctions, ui.ladderProviders])

  const heading = (text: string) => <div style={{ fontSize: 11, color: C.muted, fontFamily: C.mono }}>{text}</div>
  const hint = (text: string) => <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{text}</div>
  const row = (label: string, value: React.ReactNode, key?: string) => (
    <div key={key ?? label} style={{ display: 'flex', gap: 10, alignItems: 'baseline', flexWrap: 'wrap' }}>
      <span style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono, minWidth: 150 }}>{label}</span>
      <span style={{ fontSize: 12.5, color: '#d8d8d8', minWidth: 0, flex: 1, wordBreak: 'break-word' }}>{value}</span>
    </div>
  )
  const text = (value: string) => <span data-lang-exempt="live">{value}</span>
  const mono = (value: string, color: string = C.golden) => (
    <span style={{ fontFamily: C.mono, fontSize: 11.5, color }} data-lang-exempt="live">
      {value}
    </span>
  )
  const extLink = (href: string, label: string) => (
    <a href={href} target="_blank" rel="noopener noreferrer" style={{ color: C.accent, fontFamily: C.mono, fontSize: 11.5, wordBreak: 'break-all' }} data-lang-exempt="live">
      {label}
    </a>
  )
  const yesNo = (v: boolean) => <span style={{ color: v ? C.accent : C.warn }}>{v ? ui.yes : ui.no}</span>
  const gnk = (ngonka: string, digits = 2) => mono(`${formatScaled(ngonka, study?.fields.GNK_DECIMALS ?? 9, digits, locale)} ${ui.gnk}`, '#d8d8d8')
  const int = (n: number | string) => (typeof n === 'number' ? new Intl.NumberFormat(locale).format(n) : formatScaled(n, 0, 0, locale))
  const bullets = (list: readonly string[], color = '#d8d8d8') => (
    <ul style={{ margin: 0, paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 5 }} data-lang-exempt="live">
      {list.map((s) => {
        const { lead, rest } = splitLead(s)
        return (
          <li key={s} style={{ fontSize: 12.5, lineHeight: 1.55, color }}>
            {lead && <span style={{ fontFamily: C.mono, color: C.golden }}>{lead}: </span>}
            {rest}
          </li>
        )
      })}
    </ul>
  )
  const cell: React.CSSProperties = { padding: '4px 8px', borderBottom: `1px solid ${C.border}`, verticalAlign: 'top', fontSize: 12, lineHeight: 1.45 }
  const th: React.CSSProperties = { ...cell, fontFamily: C.mono, fontSize: 10.5, color: C.muted, textAlign: 'left', fontWeight: 400 }
  const statusChip = (s: ProviderStatus) => <span style={{ ...tagChip(false, false), cursor: 'default', color: STATUS_COLOR[s], borderColor: STATUS_COLOR[s] }}>{statusLabel[s]}</span>

  // ---- one model card: the chain's numbers beside what the chain says now ----
  const modelDetail = (m: ProviderModelEntry) => {
    const f = m.fields
    const chainModel = read?.models?.find((x) => x.modelId === f.MODEL_ID)
    const chainPoc = read?.poc ? read.poc.find((x) => x.modelId === f.MODEL_ID) ?? null : undefined
    const chainPrice = read?.pricing?.models.find((x) => x.modelId === f.MODEL_ID)
    const hostsNow = read?.participants ? (read.participants.epoch === f.EPOCH ? read.participants.hostsByModel[f.MODEL_ID] ?? 0 : null) : undefined
    const diffs = new Set(diffsOf(m.id).map((d) => d.field))
    const consumerGb = study?.fields.CONSUMER_CARD_GB ?? 24
    const datacenterGb = study?.fields.DATACENTER_CARD_GB ?? 80
    const lines: { key: string; label: string; card: React.ReactNode; now?: string | number | boolean | null; field?: string }[] = [
      { key: 'model', label: ui.modelId, card: mono(f.MODEL_ID) },
      { key: 'hf', label: ui.hfCommit, card: extLink(`https://huggingface.co/${f.MODEL_ID}/tree/${f.HF_COMMIT}`, f.HF_COMMIT.slice(0, 12)), now: chainModel?.hfCommit.slice(0, 12), field: 'HF_COMMIT' },
      {
        key: 'hosts',
        label: ui.hostsServing,
        card: (
          <span>
            {mono(String(f.HOSTS), f.HOSTS > 0 ? C.accent : C.warn)} {study && study.fields.EPOCH === f.EPOCH ? fill(ui.hostsOf, { n: study.fields.ACTIVE_HOSTS, e: f.EPOCH }) : `${ui.epoch} ${f.EPOCH}`}
          </span>
        ),
        now: hostsNow,
        field: 'HOSTS',
      },
      { key: 'vram', label: ui.vram, card: mono(`${f.VRAM_GB} GB`), now: chainModel?.vramGb, field: 'VRAM_GB' },
      { key: 'ctx', label: ui.context, card: mono(`${int(f.CONTEXT_TOKENS)} ${ui.tokens}`), now: chainModel?.contextTokens, field: 'CONTEXT_TOKENS' },
      { key: 'val', label: ui.validation, card: mono((f.VALIDATION_PERMILLE / 1000).toFixed(3)), now: chainModel && chainModel.validationPermille !== null ? (chainModel.validationPermille / 1000).toFixed(3) : chainModel ? null : undefined, field: 'VALIDATION_PERMILLE' },
      { key: 'poc', label: ui.pocModel, card: yesNo(f.POC_MODEL), now: chainPoc === undefined ? undefined : chainPoc !== null, field: 'POC_MODEL' },
      ...(f.POC_MODEL ? [{ key: 'pocw', label: ui.pocWeight, card: mono((f.POC_WEIGHT_SCALE_E4 / 10000).toFixed(4)), now: chainPoc ? (chainPoc.weightScaleE4 === null ? null : (chainPoc.weightScaleE4 / 10000).toFixed(4)) : undefined, field: 'POC_WEIGHT_SCALE_E4' }] : []),
      { key: 'tput', label: ui.throughput, card: mono(int(f.THROUGHPUT_PER_NONCE)), now: chainModel?.throughputPerNonce, field: 'THROUGHPUT_PER_NONCE' },
      { key: 'uoc', label: ui.unitsPerToken, card: mono(int(f.UNITS_OF_COMPUTE_PER_TOKEN)), now: chainModel?.unitsOfComputePerToken, field: 'UNITS_OF_COMPUTE_PER_TOKEN' },
      { key: 'price', label: ui.price, card: <span>{mono(String(f.PRICE_PER_TOKEN))} {text(f.PRICE_UNIT)}</span>, now: read?.pricing ? (chainPrice ? chainPrice.pricePerToken : null) : undefined, field: 'PRICE_PER_TOKEN' },
      {
        key: 'million',
        label: ui.perMillion,
        card: (
          <span>
            {gnk(String(BigInt(f.PRICE_PER_TOKEN) * 1000000n), 9)} <span style={{ color: C.muted, fontSize: 11 }}>({ui.perMillionNote})</span>
          </span>
        ),
      },
    ]
    const nowCell = (now: string | number | boolean | null | undefined, field: string | undefined) => {
      if (!field) return null
      if (now === undefined) return <span style={{ color: C.muted }}>{ui.notRead}</span>
      const bad = diffs.has(field as never)
      const shown = now === null ? '—' : typeof now === 'boolean' ? (now ? ui.yes : ui.no) : typeof now === 'number' ? int(now) : now
      return (
        <span style={{ fontFamily: C.mono, fontSize: 11.5, color: bad ? C.bad : C.accent }} data-lang-exempt="live">
          {bad ? '✕ ' : '✓ '}
          {shown}
        </span>
      )
    }
    return (
      <>
        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          {heading(ui.onChain)}
          {hint(ui.onChainHint)}
          <div style={{ overflowX: 'auto' }}>
            <table style={{ borderCollapse: 'collapse', width: '100%' }}>
              <thead>
                <tr>
                  <th style={th}>{ui.field}</th>
                  <th style={th}>{ui.card}</th>
                  <th style={th}>{ui.chainNow}</th>
                </tr>
              </thead>
              <tbody>
                {lines.map((l) => (
                  <tr key={l.key}>
                    <td style={{ ...cell, fontFamily: C.mono, fontSize: 10.5, color: C.muted, whiteSpace: 'nowrap' }}>{l.label}</td>
                    <td style={cell}>{l.card}</td>
                    <td style={{ ...cell, whiteSpace: 'nowrap' }}>{nowCell(l.now, l.field)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          {heading(ui.callHeading)}
          {hint(ui.callHint)}
          {row('API', text(f.API))}
          {row('CALL', mono(f.CALL, C.warn))}
          <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.callBody}</div>
          <pre style={{ margin: 0, padding: 10, background: C.raised, border: `1px solid ${C.border}`, borderRadius: 5, fontFamily: C.mono, fontSize: 11.5, color: '#d8d8d8', overflowX: 'auto' }} data-lang-exempt="live">
            {`POST /v1/chat/completions\n${JSON.stringify({ model: f.MODEL_ID, messages: [{ role: 'user', content: '…' }] }, null, 2)}`}
          </pre>
        </div>

        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          {heading(ui.serveHeading)}
          {hint(ui.serveHint)}
          {row(ui.vram, mono(`${f.VRAM_GB} GB`))}
          {row(fill(ui.consumerCards, { gb: consumerGb }), mono(String(ceilDiv(f.VRAM_GB, consumerGb))))}
          {row(fill(ui.datacenterCards, { gb: datacenterGb }), mono(String(ceilDiv(f.VRAM_GB, datacenterGb))))}
          {row(ui.vllmArgs, mono(f.VLLM_ARGS.join(' '), '#d8d8d8'))}
        </div>
      </>
    )
  }

  // ---- one host-class card: what the owner would sell, how it is checked, what is missing ----
  const hostDetail = (h: ProviderHostEntry) => {
    const f = h.fields
    const nodeGb = study?.fields.MOST_SERVED_MODEL_GB
    return (
      <>
        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          {heading(ui.hostHeading)}
          {row(ui.device, text(f.DEVICE))}
          {row(ui.memory, f.MEMORY_GB > 0 ? mono(`${f.MEMORY_GB} GB`) : <span style={{ color: C.muted }}>{ui.memoryNone}</span>)}
          {row(
            ui.perGonkaNode,
            f.UNITS_PER_GONKA_NODE === 0 ? (
              <span style={{ color: C.warn }}>{ui.cannotHostGonka}</span>
            ) : (
              <span>
                {mono(fill(ui.unitsOfThis, { n: f.UNITS_PER_GONKA_NODE }))}
                {nodeGb ? <span style={{ color: C.muted, fontSize: 11 }}> ({ui.mostServedModel}: {nodeGb} GB)</span> : null}
              </span>
            ),
          )}
          {row(ui.proof, text(f.PROOF))}
          {row(ui.reward, text(f.REWARD))}
          {row(ui.stake, text(f.STAKE))}
          {row(ui.gonkaParallel, text(f.GONKA_PARALLEL))}
          {row(ui.token, text(f.TOKEN))}
        </div>
        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
          {heading(ui.measured)}
          {f.MEASURED.length ? (
            <>
              {hint(ui.measuredHint)}
              {bullets(f.MEASURED)}
            </>
          ) : (
            hint(ui.nothingMeasured)
          )}
        </div>
        <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8, borderColor: 'rgba(240,160,32,0.4)' }}>
          {heading(ui.gaps)}
          {hint(ui.gapsHint)}
          {bullets(f.GAPS, C.warn)}
        </div>
      </>
    )
  }

  // ---- the market: every model card in one table, with the live verdict per row ----
  const market = (
    <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }} data-section="market">
      {heading(ui.marketHeading)}
      {hint(ui.marketHint)}
      <div style={{ overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%' }}>
          <thead>
            <tr>
              <th style={th}>{ui.modelId}</th>
              <th style={th}>{ui.status}</th>
              <th style={th}>{ui.hostsServing}</th>
              <th style={th}>{ui.vram}</th>
              <th style={th}>{ui.context}</th>
              <th style={th}>{ui.validation}</th>
              <th style={th}>{ui.price}</th>
              <th style={th}>{ui.chainNow}</th>
            </tr>
          </thead>
          <tbody>
            {models.map((m) => {
              const d = diffsOf(m.id)
              return (
                <tr key={m.id} style={m.id === selected?.id ? { background: 'rgba(0,255,136,0.06)' } : undefined}>
                  <td style={{ ...cell, whiteSpace: 'nowrap' }}>
                    <a
                      href={providerExplorerHash(m.id, { embedded })}
                      onClick={(e) => {
                        e.preventDefault()
                        setPane('detail')
                        pick(m)
                      }}
                      style={{ color: C.accent, fontFamily: C.mono, fontSize: 11.5 }}
                      data-lang-exempt="live"
                    >
                      {m.name.en}
                    </a>
                  </td>
                  <td style={cell}>{statusChip(m.status)}</td>
                  <td style={{ ...cell, fontFamily: C.mono, color: m.fields.HOSTS > 0 ? C.accent : C.warn }}>{m.fields.HOSTS}</td>
                  <td style={{ ...cell, fontFamily: C.mono }}>{m.fields.VRAM_GB} GB</td>
                  <td style={{ ...cell, fontFamily: C.mono }}>{int(m.fields.CONTEXT_TOKENS)}</td>
                  <td style={{ ...cell, fontFamily: C.mono }}>{(m.fields.VALIDATION_PERMILLE / 1000).toFixed(3)}</td>
                  <td style={{ ...cell, fontFamily: C.mono }}>{m.fields.PRICE_PER_TOKEN}</td>
                  <td style={{ ...cell, fontFamily: C.mono, whiteSpace: 'nowrap', color: !distance ? C.muted : d.length ? C.bad : C.accent }}>
                    {!distance ? ui.notRead : d.length ? `✕ ${d.length}` : '✓'}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 6, paddingTop: 4 }} data-section="live" data-live-state={live.state}>
        {heading(ui.liveHeading)}
        {hint(ui.liveHint)}
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          <button className="spec-x-target" onClick={() => void readChain()} disabled={live.state === 'loading'} style={{ ...pill, color: C.accent, borderColor: C.borderBright }}>
            {ui.liveRead}
          </button>
          <button className="spec-x-target" onClick={() => void readHosts()} disabled={live.state === 'loading'} style={pill}>
            {ui.liveHosts}
          </button>
          {live.state === 'loading' && <span style={{ fontSize: 11.5, color: C.muted }}>{ui.liveLoading}</span>}
        </div>
        {hint(ui.liveHostsHint)}
        <div style={{ fontSize: 12, lineHeight: 1.5, color: live.state === 'failed' ? C.bad : distance && distance.differences.length ? C.warn : live.state === 'ok' ? C.accent : C.muted }}>
          {live.state === 'idle' && fill(ui.liveIdle, { d: models[0]?.fields.CHECKED ?? '—' })}
          {live.state === 'failed' && fill(ui.liveFailed, { e: live.error, d: models[0]?.fields.CHECKED ?? '—' })}
          {live.state === 'ok' && distance && (distance.differences.length ? fill(ui.liveOk, { t: live.at, n: distance.differences.length }) : fill(ui.liveSame, { t: live.at }))}
        </div>
        {read?.participants && models[0] && read.participants.epoch !== models[0].fields.EPOCH && (
          <div style={{ fontSize: 12, color: C.warn }}>{fill(ui.liveEpoch, { e: read.participants.epoch, c: models[0].fields.EPOCH })}</div>
        )}
        {distance && distance.differences.length > 0 && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
            <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.differences}</div>
            {distance.differences.map((d) => (
              <div key={`${d.providerId}:${d.field}`} style={{ fontFamily: C.mono, fontSize: 11.5, color: C.bad }} data-lang-exempt="live">
                {d.providerId} · {d.field}: {String(d.card)} → {d.chain === null ? '—' : String(d.chain)}
              </div>
            ))}
          </div>
        )}
        {distance && distance.uncarded.length > 0 && (
          <div style={{ fontSize: 12, color: C.bad }}>
            {ui.uncarded} {mono(distance.uncarded.join(', '), C.bad)}
          </div>
        )}
        {distance && distance.unlisted.length > 0 && (
          <div style={{ fontSize: 12, color: C.bad }}>
            {ui.unlisted} {mono(distance.unlisted.join(', '), C.bad)}
          </div>
        )}
      </div>
    </div>
  )

  // ---- the study: the pair, how Gonka pays, what a node needs, the parallels ----
  const studyBlock = study && (
    <>
      <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }} data-section="pair">
        <div style={{ display: 'flex', gap: 8, alignItems: 'baseline', flexWrap: 'wrap' }}>
          {heading(ui.studyHeading)}
          <span style={{ fontFamily: C.mono, fontSize: 11, color: C.accent }} data-lang-exempt="live">
            {study.specPath}
          </span>
          <a className="spec-x-target" href={vendoredSpecUrl(study.specPath)} target="_blank" rel="noopener noreferrer" style={{ ...pill, marginLeft: 'auto' }}>
            {ui.openStudy}
          </a>
          <a className="spec-x-target" href={canonicalSpecEditUrl(study.specPath)} target="_blank" rel="noopener noreferrer" style={pill}>
            {ui.editSpec}
          </a>
        </div>
        {hint(ui.studyHint)}
        <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.conflict}</div>
        <div style={{ fontSize: 12.5, lineHeight: 1.55, color: C.warn, borderLeft: `2px solid ${C.warn}`, paddingLeft: 10 }} data-lang-exempt="live">
          {study.fields.CONFLICT}
        </div>
        <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.routes}</div>
        {bullets(study.fields.ROUTES)}
        <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.pairFacts}</div>
        {row(ui.triChains, mono(study.fields.TRI_CHAINS.join(', ')))}
        {row(ui.triMainnet, yesNo(study.fields.TRI_MAINNET))}
        {row(ui.triCap, mono(`${int(study.fields.TRI_CAP)} TRI (3^21)`))}
        {row(ui.gonkaPool, yesNo(study.fields.GONKA_POOL_REGISTERED))}
        {row(ui.bridge, mono(study.fields.BRIDGE_CHAINS.join(', ')))}
        {row(ui.wgnk, extLink(`https://etherscan.io/token/${study.fields.WGNK_ETHEREUM}`, study.fields.WGNK_ETHEREUM))}
        {row(ui.wgnkPool, extLink(`https://etherscan.io/address/${study.fields.WGNK_USDT_UNISWAP_V3_POOL}`, study.fields.WGNK_USDT_UNISWAP_V3_POOL))}
        {row(ui.approved, bullets(study.fields.GONKA_APPROVED_FOR_TRADE))}
        {row(ui.ibc, bullets(study.fields.IBC_CHANNELS))}
      </div>

      <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }} data-section="pays">
        {heading(ui.paysHeading)}
        {hint(ui.paysHint)}
        {row(ui.epoch, mono(String(study.fields.EPOCH)))}
        {row(ui.activeHosts, mono(String(study.fields.ACTIVE_HOSTS)))}
        {row(ui.height, mono(int(study.fields.CHAIN_HEIGHT)))}
        {row(ui.supply, gnk(study.fields.SUPPLY_NGONKA))}
        {row(ui.fees, gnk(study.fields.TOTAL_FEES_NGONKA))}
        {row(ui.subsidies, gnk(study.fields.TOTAL_SUBSIDIES_NGONKA))}
        {row(ui.subsidyPerFee, mono(`× ${int(study.derived.subsidyPerFee)}`, C.warn))}
        {row(ui.burned, gnk(study.fields.TOTAL_BURNED_NGONKA))}
        {row(ui.initialReward, gnk(study.fields.INITIAL_EPOCH_REWARD_NGONKA))}
        {row(ui.vesting, mono(fill(ui.vestingValue, { n: study.fields.VESTING_EPOCHS, d: study.derived.vestingDays })))}
        {row(ui.baseWeight, mono(`${study.fields.BASE_WEIGHT_PERMILLE / 10}%`))}
        {row(ui.slashInvalid, mono(`${study.fields.SLASH_INVALID_PERMILLE / 10}%`))}
        {row(ui.slashDowntime, mono(`${study.fields.SLASH_DOWNTIME_PERMILLE / 10}%`))}
        {row(
          ui.allowlist,
          study.derived.allowlistActive ? (
            <span style={{ color: C.warn }}>{fill(ui.allowlistActive, { h: int(study.fields.ALLOWLIST_UNTIL_HEIGHT) })}</span>
          ) : (
            <span style={{ color: C.accent }}>{fill(ui.allowlistInactive, { h: int(study.fields.ALLOWLIST_UNTIL_HEIGHT), c: int(study.fields.CHAIN_HEIGHT) })}</span>
          ),
        )}
      </div>

      <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }} data-section="node">
        {heading(ui.nodeHeading)}
        {hint(fill(ui.nodeHint, { min: study.fields.CONSUMER_ERA_MIN_GB }))}
        {row(ui.smallestModel, mono(`${study.fields.SMALLEST_POC_MODEL_GB} GB · ${fill(ui.cardsOf, { n: study.derived.consumerCardsPerNode.smallest, gb: study.fields.CONSUMER_CARD_GB })}`))}
        {row(ui.mostServedModel, mono(`${study.fields.MOST_SERVED_MODEL_GB} GB · ${fill(ui.cardsOf, { n: study.derived.consumerCardsPerNode.mostServed, gb: study.fields.CONSUMER_CARD_GB })}`))}
        {row(ui.largestModel, mono(`${study.fields.LARGEST_POC_MODEL_GB} GB · ${fill(ui.cardsOf, { n: study.derived.consumerCardsPerNode.largest, gb: study.fields.CONSUMER_CARD_GB })}`))}
      </div>

      <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }} data-section="parallels">
        {heading(ui.parallels)}
        {hint(ui.parallelsHint)}
        {bullets(study.fields.PARALLELS)}
      </div>
    </>
  )

  return (
    <div
      className="spec-x"
      data-tier={viewport.tier}
      data-embedded={embedded ? '1' : undefined}
      style={{
        height: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        background: C.bg,
        color: C.text,
        fontFamily: "'Outfit', system-ui, sans-serif",
        overflow: 'hidden',
      }}
    >
      {!embedded && <ExplorerHeader title={ui.title} subtitle={ui.subtitle} back={ui.back} note={ui.note} narrow={narrow} phone={phone} />}
      {/* One ladder per screen -- see components/LayerLadder. */}
      {!embedded && <LayerLadder steps={ladderSteps} caption={ui.ladder} />}

      <div style={{ flex: 1, display: 'flex', minHeight: 0, minWidth: 0 }}>
        {showList && (
          <ExplorerLibrary
            items={items}
            selectedId={selected?.id ?? null}
            onPick={(item) => {
              const entry = providers.find((p) => p.id === item.id)
              if (entry) {
                setPane('detail')
                pick(entry)
              }
            }}
            query={query}
            setQuery={setQuery}
            categories={[
              ['gonka', ui.networkGonka, counts?.byNetwork.gonka ?? 0],
              ['trinet', ui.networkTrinet, counts?.byNetwork.trinet ?? 0],
            ]}
            category={network}
            setCategory={setNetwork}
            filters={[
              { key: 'all', label: ui.filterAll, count: providers.length },
              { key: 'serving', label: ui.statusServing, count: counts?.byStatus.serving ?? 0, color: STATUS_COLOR.serving, glyph: '●' },
              { key: 'listed', label: ui.statusListed, count: counts?.byStatus.listed ?? 0, color: STATUS_COLOR.listed, glyph: '○' },
              { key: 'measured', label: ui.statusMeasured, count: counts?.byStatus.measured ?? 0, color: STATUS_COLOR.measured, glyph: '◆' },
              { key: 'planned', label: ui.statusPlanned, count: counts?.byStatus.planned ?? 0, color: STATUS_COLOR.planned, glyph: '◇' },
            ]}
            filter={statusFilter}
            setFilter={(v) => setStatusFilter(v as 'all' | ProviderStatus)}
            stack={[
              { key: 'serving', count: counts?.byStatus.serving ?? 0, color: STATUS_COLOR.serving, label: ui.statusServing },
              { key: 'measured', count: counts?.byStatus.measured ?? 0, color: C.golden, label: ui.statusMeasured },
              { key: 'listed', count: counts?.byStatus.listed ?? 0, color: STATUS_COLOR.listed, label: ui.statusListed },
              { key: 'planned', count: counts?.byStatus.planned ?? 0, color: C.muted, label: ui.statusPlanned },
            ]}
            tagCounts={tagCounts}
            tagFamilies={TAG_FAMILIES}
            tagSel={tagSel}
            toggleTag={(x) => setTagSel((prev) => (prev.includes(x) ? prev.filter((y) => y !== x) : [...prev, x]))}
            clearTags={() => setTagSel([])}
            tier={viewport.tier}
            countLabel={`${filtered.length} ${ui.providersCount}`}
            titlesAreGenerated
            ui={{
              search: ui.search,
              allCategories: `${ui.allNetworks} (${providers.length})`,
              tags: ui.tags,
              clear: ui.clear,
              noResults: ui.noResults,
              noneInGroup: ui.noneInGroup,
              filters: ui.filters,
            }}
          />
        )}

        {showDetail && (
          <main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, minHeight: 0, overflowY: 'auto' }}>
            {err && (
              <div
                className="spec-x-banner"
                style={{
                  margin: '10px 14px 0',
                  padding: '9px 12px',
                  background: 'rgba(248,81,73,0.10)',
                  border: `1px solid ${C.bad}`,
                  borderRadius: 5,
                  fontSize: 12,
                  color: '#d8d8d8',
                }}
              >
                <span style={{ color: C.bad, fontWeight: 700 }}>⚠ {ui.failed}</span> <span data-lang-exempt="live">{err}</span>
              </div>
            )}
            {!selected && !err && <div style={{ padding: 24, color: C.muted, fontSize: 13 }}>{catalog ? ui.pickProvider : ui.loading}</div>}
            {selected && (
              <div data-card={selected.id} style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 12 }}>
                {phone && (
                  <button onClick={() => setPane('list')} className="spec-x-back" style={{ ...pill, alignSelf: 'flex-start' }}>
                    ← {ui.backToLibrary}
                  </button>
                )}
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <span
                    aria-hidden="true"
                    style={{
                      fontFamily: C.mono,
                      fontSize: 22,
                      fontWeight: 700,
                      lineHeight: 1,
                      color: C.golden,
                      minWidth: 36,
                      textAlign: 'center',
                      border: `1px solid ${C.borderBright}`,
                      borderRadius: 6,
                      padding: '6px 6px',
                    }}
                  >
                    {selected.family === 'model' ? '⌬' : selected.id === 'trinet/fpga-xc7a200t' ? '▦' : '▣'}
                  </span>
                  <span style={{ fontSize: 15, fontWeight: 700, fontFamily: C.mono }} data-lang-exempt="live">
                    {selected.name.en}
                  </span>
                  <span style={{ fontFamily: C.mono, fontSize: 11, color: C.muted }} data-lang-exempt="live">
                    {selected.id}
                  </span>
                  {statusChip(selected.status)}
                  <button onClick={copy} style={{ ...pill, color: copied ? C.accent : C.muted, marginLeft: 'auto' }}>
                    {copied ? ui.copied : ui.copyLink}
                  </button>
                </div>
                <div style={{ fontSize: 13, lineHeight: 1.55, color: '#d8d8d8' }} data-lang-exempt="live">
                  {selected.summary[short] ?? selected.summary.en}
                </div>

                {isModel(selected) ? modelDetail(selected) : isHost(selected) ? hostDetail(selected) : null}

                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {heading(ui.sources)}
                  {hint(ui.sourcesHint)}
                  {selected.fields.SOURCES.map((s) => {
                    const l = sourceLink(s)
                    return <div key={s}>{l.href ? extLink(l.href, l.text) : mono(l.text, '#d8d8d8')}</div>
                  })}
                  {row(ui.checked, mono(selected.fields.CHECKED))}
                  {row(ui.witness, mono(selected.witness))}
                  {selected.fields.NOTE ? row(ui.noteLabel, text(selected.fields.NOTE)) : null}
                </div>

                {/* The spec is the statement; the boxes above are what it states, read as a card. */}
                <AgentSpecPanel
                  lang={short}
                  kind="provider"
                  id={selected.id}
                  entry={selected}
                  embedded={embedded}
                  flat={compact}
                  i18n={catalog?.i18n ?? []}
                  links={providers.filter((p) => p.family !== selected.family).map((p) => ({ id: p.id, ok: true, href: providerExplorerHash(p.id, { embedded }) }))}
                />

                {market}
                {studyBlock}
              </div>
            )}
          </main>
        )}
      </div>
    </div>
  )
}
