// Tool Explorer -- the tri CLI and the MCP servers, each read from its spec.
//
// The fifth step of the site's ladder: Specs → Skills → Crons → Agents → Tools →
// Functions (t27 specs/tools/README.md says "Layer 5"; so does specs/functions). A tool is
// a clap variant of gHashTag/t27 `tri` or an MCP server registered in either
// repository; its card is generated by scripts/agents-from-specs.mjs from
// specs/tools/{tri,mcp}/<name>.t27 through the real compiler. The text on a
// card came from the program it describes (clap `///` doc comments, MCP
// manifests and tool descriptions) and the card names how: `source-parse` when
// read from the source, `help-output` when diffed against `tri --help`. Nothing
// here is typed twice: the commands, their actions, the servers' tools, the
// letters that own them and the counts in the ladder all come from the
// generated catalog, and a tool nobody owns says so.

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useI18n } from '../i18n/context'
import { usePageMeta } from '../hooks/usePageMeta'
import { useHashParams } from '../hooks/useHashParams'
import { useDocumentLock, useViewport } from '../lib/useViewport'
import { HEADER_CHROME_MAX } from '../lib/viewport.generated'
import { ExplorerHeader } from '../components/ExplorerHeader'
import { ExplorerLibrary, type ExplorerItem } from '../components/ExplorerLibrary'
import { AgentSpecPanel } from '../components/AgentSpecPanel'
import { LayerLadder, type LadderStep } from '../components/LayerLadder'
import { loadToolSpecs, type ToolFamily, type ToolSpecCatalog, type ToolSpecEntry } from '../lib/agentSpecs'
import { skillExplorerHash } from '../lib/skillsCatalog'
import { agentExplorerHash } from '../lib/agentsCatalog'
import { toolExplorerHash, canonicalToolUrl, resolveTool } from '../lib/toolsCatalog'
import { C, panelBox, pill, tagChip } from '../lib/explorerTheme'

const UI = {
  en: {
    title: 'Tool Explorer',
    subtitle: 'The tri CLI and the MCP servers, each read from its spec',
    metaTitle: 'Tool Explorer',
    metaDescription:
      'The tools every Trinity agent should know: the commands of the t27 tri CLI and the MCP servers of both repositories, each generated from a .t27 spec with its source, its actions or tools, and the agents that own it.',
    note: 'Generated from specs/tools/{tri,mcp}/*.t27, not typed by hand',
    back: '← Home',
    search: 'Search by command, tool or about text',
    allFamilies: 'Both families',
    tags: 'Tags',
    clear: 'Clear',
    toolsCount: 'tools',
    noResults: 'No tool matches',
    noneInGroup: 'None in this family',
    loading: 'loading the catalog…',
    failed: 'Could not load the tool catalog:',
    pickTool: 'Pick a tool',
    backToLibrary: 'All tools',
    filters: 'Filters',
    filterAll: 'All',
    filterOwned: 'owned by an agent',
    filterUnowned: 'no owner yet',
    ladder: 'ladder',
    ladderSpecs: 'Specs',
    ladderSkills: 'Skills',
    ladderCrons: 'Crons',
    ladderAgents: 'Agents',
    ladderTools: 'Tools',
    ladderFunctions: 'Functions',
    familyTri: 'tri CLI',
    familyMcp: 'MCP servers',
    synopsis: 'SYNOPSIS',
    command: 'command',
    variant: 'clap variant',
    actions: 'actions',
    actionsCount: 'actions',
    noActions: 'no nested actions',
    args: 'arguments',
    whenToUse: 'WHEN TO USE',
    whenToUseHint: 'From the command’s own about text; the catalog adds no advice of its own.',
    owners: 'WHO OWNS IT',
    ownersHint: 'Letters whose spec names this tool and whose binding a source states; both directions are checked by the generator.',
    noOwners: 'no agent bound yet',
    skills: 'SKILLS',
    skillsHint: 'Skills whose own spec text (COMMAND or SUMMARY_EN) names this command.',
    noSkills: 'no skill names this command',
    via: 'via',
    source: 'SOURCE',
    sourceHint: 'The file the card was read from, linked at the pinned commit; the witness says how.',
    aboutFrom: 'about text from',
    witness: 'witness',
    pinnedAt: 'pinned at',
    server: 'SERVER',
    launch: 'launch',
    transport: 'transport',
    env: 'environment',
    config: 'config',
    noConfig: 'not registered in any .mcp.json',
    version: 'version',
    external: 'external package — the tool list is not in the repository',
    mcpTools: 'TOOLS',
    mcpToolsCount: 'tools',
    toolName: 'name',
    toolAbout: 'description',
    toolInputs: 'input schema keys',
    noInputs: '—',
    resources: 'resources',
    noResources: 'none',
    editSpec: 'Edit in the spec →',
    openSource: 'Open source',
    openConfig: 'Open config',
    copyLink: 'Copy link',
    copied: 'Copied',
    enabledOff: 'disabled',
    groupUnbound: 'unbound',
  },
  ru: {
    title: 'Обозреватель инструментов',
    subtitle: 'tri CLI и MCP-серверы, каждый прочитан из своей спеки',
    metaTitle: 'Обозреватель инструментов',
    metaDescription:
      'Инструменты, о которых должен знать каждый агент Trinity: команды t27 tri CLI и MCP-серверы обоих репозиториев, каждый сгенерирован из спеки .t27 с исходником, действиями или инструментами и агентами-владельцами.',
    note: 'Сгенерировано из specs/tools/{tri,mcp}/*.t27, а не набрано руками',
    back: '← На главную',
    search: 'Поиск по команде, инструменту или описанию',
    allFamilies: 'Оба семейства',
    tags: 'Теги',
    clear: 'Сбросить',
    toolsCount: 'инструментов',
    noResults: 'Ни один инструмент не подходит',
    noneInGroup: 'В этом семействе ничего',
    loading: 'загружаем каталог…',
    failed: 'Не удалось загрузить каталог инструментов:',
    pickTool: 'Выберите инструмент',
    backToLibrary: 'Все инструменты',
    filters: 'Фильтры',
    filterAll: 'Все',
    filterOwned: 'с владельцем',
    filterUnowned: 'без владельца',
    ladder: 'лестница',
    ladderSpecs: 'Спеки',
    ladderSkills: 'Скиллы',
    ladderCrons: 'Кроны',
    ladderAgents: 'Агенты',
    ladderTools: 'Инструменты',
    ladderFunctions: 'Функции',
    familyTri: 'Команды tri',
    familyMcp: 'MCP-серверы',
    synopsis: 'СИНОПСИС',
    command: 'команда',
    variant: 'вариант clap',
    actions: 'действия',
    actionsCount: 'действ.',
    noActions: 'вложенных действий нет',
    args: 'аргументы',
    whenToUse: 'КОГДА ИСПОЛЬЗОВАТЬ',
    whenToUseHint: 'Из собственного описания команды; каталог не добавляет советов от себя.',
    owners: 'КТО ВЛАДЕЕТ',
    ownersHint: 'Буквы, чья спека называет этот инструмент и чью привязку называет источник; генератор проверяет оба направления.',
    noOwners: 'агент пока не привязан',
    skills: 'СКИЛЛЫ',
    skillsHint: 'Скиллы, чей собственный текст спеки (COMMAND или SUMMARY_EN) называет эту команду.',
    noSkills: 'ни один скилл не называет эту команду',
    via: 'через',
    source: 'ИСТОЧНИК',
    sourceHint: 'Файл, из которого прочитана карточка, со ссылкой на закреплённый коммит; свидетель говорит, как именно.',
    aboutFrom: 'описание взято из',
    witness: 'свидетель',
    pinnedAt: 'закреплено на',
    server: 'СЕРВЕР',
    launch: 'запуск',
    transport: 'транспорт',
    env: 'окружение',
    config: 'конфиг',
    noConfig: 'не зарегистрирован ни в одном .mcp.json',
    version: 'версия',
    external: 'внешний пакет — список инструментов не лежит в репозитории',
    mcpTools: 'ИНСТРУМЕНТЫ',
    mcpToolsCount: 'инструментов',
    toolName: 'имя',
    toolAbout: 'описание',
    toolInputs: 'ключи входной схемы',
    noInputs: '—',
    resources: 'ресурсы',
    noResources: 'нет',
    editSpec: 'Изменить в спеке →',
    openSource: 'Открыть исходник',
    openConfig: 'Открыть конфиг',
    copyLink: 'Скопировать ссылку',
    copied: 'Скопировано',
    enabledOff: 'выключен',
    groupUnbound: 'без привязки',
  },
} as const

type Ui = Record<keyof typeof UI.en, string>

const TAG_FAMILIES = [
  { prefix: 'family/', label: 'family' },
  { prefix: 'repo/', label: 'repo' },
  { prefix: 'owner/', label: 'owner' },
  { prefix: 'witness/', label: 'witness' },
  { prefix: 'external/', label: 'external' },
]

function tagsOf(t: ToolSpecEntry): string[] {
  const tags = [`family/${t.family}`, `repo/${t.repo.replace('gHashTag/', '')}`, `witness/${t.witness}`]
  if (t.agents.length) for (const a of t.agents) tags.push(`owner/${a.letter}`)
  else tags.push('owner/none')
  if (t.family === 'mcp') tags.push(`external/${t.external ? 'yes' : 'no'}`)
  return tags
}

export default function ToolExplorer() {
  const { lang } = useI18n()
  const ui: Ui = lang === 'ru' ? UI.ru : UI.en
  const short = lang === 'ru' ? 'ru' : 'en'
  usePageMeta(ui.metaTitle, ui.metaDescription)
  const params = useHashParams()
  const embedded = params.embedded

  const [catalog, setCatalog] = useState<ToolSpecCatalog | null>(null)
  const [selected, setSelected] = useState<ToolSpecEntry | null>(null)
  const [err, setErr] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [family, setFamily] = useState('')
  const [ownerFilter, setOwnerFilter] = useState<'all' | 'owned' | 'unowned'>('all')
  const [tagSel, setTagSel] = useState<string[]>([])
  const [copied, setCopied] = useState(false)
  // Layout tier from specs/ui/viewport.t27 (via useViewport); `narrow` trims the
  // header chrome and is not a tier. Phone and tablet lock the document: the
  // panes are the scrollers there.
  const viewport = useViewport()
  const phone = viewport.tier === 'phone'
  const compact = phone || viewport.tier === 'tablet'
  const narrow = viewport.width < HEADER_CHROME_MAX
  useDocumentLock(compact)
  const [pane, setPane] = useState<'list' | 'detail'>('list')

  const pick = useCallback(
    (entry: ToolSpecEntry) => {
      setSelected(entry)
      params.set(toolExplorerHash(entry.id, { embedded }))
    },
    [embedded, params],
  )

  useEffect(() => {
    let alive = true
    loadToolSpecs()
      .then((c) => {
        if (!alive) return
        setCatalog(c)
        const wanted = params.get('tool')
        try {
          const target = resolveTool(c, wanted)
          if (wanted) setPane('detail')
          pick(target)
        } catch (e) {
          setErr(String(e instanceof Error ? e.message : e))
          setPane('detail')
        }
      })
      .catch((e) => {
        if (!alive) return
        setErr(String(e instanceof Error ? e.message : e))
        setPane('detail')
      })
    return () => {
      alive = false
    }
    // Mount only: the deep link is read once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // A deep link that arrives after mount (the back button, a link on this
  // page, a script setting the hash): open that card, on a phone as the card
  // pane. Measured before this at 390x844: `#/tools` then a `?tool=` hash
  // kept the list, because the parameters were read once.
  useEffect(() => {
    if (!catalog || params.changes === 0) return
    const wanted = params.get('tool')
    if (!wanted) return
    try {
      const target = resolveTool(catalog, wanted)
      setPane('detail')
      if (target !== selected) pick(target)
    } catch {
      // An unknown id in a later hash: keep the card that is open.
    }
    // Only the hash counter: the catalog and the selection are read, not followed.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params.changes])

  const tools = useMemo(() => catalog?.tools ?? [], [catalog])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    return tools.filter((t) => {
      if (family && t.family !== family) return false
      if (ownerFilter === 'owned' && t.agents.length === 0) return false
      if (ownerFilter === 'unowned' && t.agents.length > 0) return false
      if (tagSel.length) {
        const tags = tagsOf(t)
        if (!tagSel.every((x) => tags.includes(x))) return false
      }
      if (!q) return true
      // The generated full-text index (id, command/server, about, actions, tools, letters) plus the loaded locale's summary.
      return t.searchText.includes(q) || (t.summary[short] ?? '').toLowerCase().includes(q)
    })
  }, [tools, query, family, ownerFilter, tagSel, short])

  const tagCounts = useMemo(() => {
    const acc: Record<string, number> = {}
    for (const t of filtered) for (const x of tagsOf(t)) acc[x] = (acc[x] ?? 0) + 1
    return acc
  }, [filtered])

  const familyLabel: Record<ToolFamily, string> = { 'tri-cli': ui.familyTri, mcp: ui.familyMcp }

  const items: ExplorerItem[] = useMemo(
    () =>
      filtered.map((t) => ({
        id: t.id,
        title: t.name.en,
        subtitle: t.family === 'tri-cli' ? `${t.actions.length ? `${t.actions.length} ${ui.actionsCount} · ` : ''}${t.source}` : `${t.external ? ui.external : `${t.tools.length} ${ui.mcpToolsCount}`} · ${t.repo.replace('gHashTag/', '')}`,
        badge: t.agents.length > 0 ? t.agents.map((a) => a.letter).join(' ') : t.fields.ENABLED ? undefined : ui.enabledOff,
        badgeColor: t.agents.some((a) => !a.ok) ? C.bad : C.golden,
        health: t.health,
        tags: tagsOf(t),
        haystack: t.searchText,
      })),
    [filtered, ui.actionsCount, ui.external, ui.mcpToolsCount, ui.enabledOff],
  )

  const copy = useCallback(() => {
    if (!selected) return
    navigator.clipboard?.writeText(canonicalToolUrl(selected.id)).then(
      () => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1400)
      },
      () => {},
    )
  }, [selected])

  const box = panelBox(embedded)
  const showList = !phone || pane === 'list'
  const showDetail = !phone || pane === 'detail'
  const counts = catalog?.counts
  const owned = counts?.withAgents ?? 0
  const unowned = counts ? counts.specs - counts.withAgents : 0

  const ladderSteps: LadderStep[] = useMemo(() => {
    const l = catalog?.ladder
    const embed = embedded ? '?embed=1' : ''
    return [
      { key: 'specs', label: ui.ladderSpecs, count: l?.specs ?? null, href: `#/specs${embed}` },
      { key: 'skills', label: ui.ladderSkills, count: l?.skills ?? null, href: `#/skills${embed}` },
      { key: 'crons', label: ui.ladderCrons, count: l?.crons ?? null, href: `#/crons${embed}` },
      { key: 'agents', label: ui.ladderAgents, count: l?.agents ?? null, href: `#/agents${embed}` },
      { key: 'tools', label: ui.ladderTools, count: l?.tools ?? null, href: `#/tools${embed}`, current: true },
      { key: 'functions', label: ui.ladderFunctions, count: l?.functions ?? null, href: `#/functions${embed}` },
    ]
  }, [catalog, embedded, ui.ladderSpecs, ui.ladderSkills, ui.ladderCrons, ui.ladderAgents, ui.ladderTools, ui.ladderFunctions])

  const heading = (text: string) => <div style={{ fontSize: 11, color: C.muted, fontFamily: C.mono }}>{text}</div>
  const row = (label: string, value: React.ReactNode) => (
    <div style={{ display: 'flex', gap: 10, alignItems: 'baseline', flexWrap: 'wrap' }}>
      <span style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono, minWidth: 92 }}>{label}</span>
      <span style={{ fontSize: 12.5, color: '#d8d8d8', minWidth: 0, wordBreak: 'break-word' }}>{value}</span>
    </div>
  )
  const live = (text: string) => <span data-lang-exempt="live">{text}</span>
  const mono = (text: string) => (
    <span style={{ fontFamily: C.mono, fontSize: 11.5, color: C.golden }} data-lang-exempt="live">
      {text}
    </span>
  )
  const chipLink = (href: string, text: string, glyph: string, ok = true) =>
    ok ? (
      <a className="spec-x-target" key={text} href={href} style={{ ...tagChip(false, false), color: C.accent, borderColor: C.borderBright, textDecoration: 'none' }} data-lang-exempt="live">
        {glyph} {text}
      </a>
    ) : (
      <span key={text} style={{ ...tagChip(false, false), color: C.bad, borderColor: C.bad }} data-lang-exempt="live">
        ✕ {text}
      </span>
    )
  const cell: React.CSSProperties = { padding: '4px 8px', borderBottom: `1px solid ${C.border}`, verticalAlign: 'top', fontSize: 12, lineHeight: 1.45 }
  const th: React.CSSProperties = { ...cell, fontFamily: C.mono, fontSize: 10.5, color: C.muted, textAlign: 'left', fontWeight: 400 }

  return (
    <div
      className="spec-x"
      data-tier={viewport.tier}
      data-embedded={embedded ? '1' : undefined}
      style={{
        height: '100dvh',
        display: 'flex',
        flexDirection: 'column',
        background: C.bg,
        color: C.text,
        fontFamily: "'Outfit', system-ui, sans-serif",
        overflow: 'hidden',
      }}
    >
      {!embedded && (
        <ExplorerHeader
          title={ui.title}
          subtitle={ui.subtitle}
          back={ui.back}
          note={ui.note}
          provenance={catalog ? [{ repo: 'gHashTag/t27', shortCommit: catalog.pin.ref.slice(0, 7) }] : undefined}
          provenanceLabel={ui.pinnedAt}
          narrow={narrow}
          phone={phone}
        />
      )}
      <LayerLadder steps={ladderSteps} caption={ui.ladder} />

      <div style={{ flex: 1, display: 'flex', minHeight: 0, minWidth: 0 }}>
        {showList && (
          <ExplorerLibrary
            items={items}
            selectedId={selected?.id ?? null}
            onPick={(item) => {
              const entry = tools.find((t) => t.id === item.id)
              if (entry) {
                setPane('detail')
                pick(entry)
              }
            }}
            query={query}
            setQuery={setQuery}
            categories={[
              ['tri-cli', ui.familyTri, counts?.tri ?? 0],
              ['mcp', ui.familyMcp, counts?.mcp ?? 0],
            ]}
            category={family}
            setCategory={setFamily}
            filters={[
              { key: 'all', label: ui.filterAll, count: tools.length },
              { key: 'owned', label: ui.filterOwned, count: owned, color: C.accent, glyph: 'Ω' },
              { key: 'unowned', label: ui.filterUnowned, count: unowned, color: C.warn, glyph: '○' },
            ]}
            filter={ownerFilter}
            setFilter={(v) => setOwnerFilter(v as 'all' | 'owned' | 'unowned')}
            stack={[
              { key: 'owned', count: owned, color: C.accent, label: ui.filterOwned },
              { key: 'unowned', count: unowned, color: C.warn, label: ui.filterUnowned },
            ]}
            tagCounts={tagCounts}
            tagFamilies={TAG_FAMILIES}
            tagSel={tagSel}
            toggleTag={(x) => setTagSel((prev) => (prev.includes(x) ? prev.filter((y) => y !== x) : [...prev, x]))}
            clearTags={() => setTagSel([])}
            tier={viewport.tier}
            countLabel={`${filtered.length} ${ui.toolsCount}`}
            titlesAreGenerated
            ui={{
              search: ui.search,
              allCategories: `${ui.allFamilies} (${tools.length})`,
              tags: ui.tags,
              clear: ui.clear,
              noResults: ui.noResults,
              noneInGroup: ui.noneInGroup,
              filters: ui.filters,
            }}
          />
        )}

        {showDetail && (
          <main style={{ flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, minHeight: 0, overflowY: 'auto' }}>
            {err && (
              <div
                className="spec-x-banner"
                style={{
                  margin: '10px 14px 0',
                  padding: '9px 12px',
                  background: 'rgba(248,81,73,0.10)',
                  border: `1px solid ${C.bad}`,
                  borderRadius: 5,
                  fontSize: 12,
                  color: '#d8d8d8',
                }}
              >
                <span style={{ color: C.bad, fontWeight: 700 }}>⚠ {ui.failed}</span> <span data-lang-exempt="live">{err}</span>
              </div>
            )}
            {!selected && !err && <div style={{ padding: 24, color: C.muted, fontSize: 13 }}>{catalog ? ui.pickTool : ui.loading}</div>}
            {selected && (
              <div data-card={selected.id} style={{ padding: 14, display: 'flex', flexDirection: 'column', gap: 12 }}>
                {phone && (
                  <button onClick={() => setPane('list')} className="spec-x-back" style={{ ...pill, alignSelf: 'flex-start' }}>
                    ← {ui.backToLibrary}
                  </button>
                )}
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
                  <span
                    aria-hidden="true"
                    style={{
                      fontFamily: C.mono,
                      fontSize: 22,
                      fontWeight: 700,
                      lineHeight: 1,
                      color: C.golden,
                      minWidth: 36,
                      textAlign: 'center',
                      border: `1px solid ${C.borderBright}`,
                      borderRadius: 6,
                      padding: '6px 6px',
                    }}
                  >
                    {selected.family === 'tri-cli' ? '>_' : '⇄'}
                  </span>
                  <span style={{ fontSize: 15, fontWeight: 700, fontFamily: C.mono }} data-lang-exempt="live">
                    {selected.name.en}
                  </span>
                  <span style={{ fontFamily: C.mono, fontSize: 11, color: C.muted }} data-lang-exempt="live">
                    {selected.id}
                  </span>
                  <span style={{ ...tagChip(false, false), cursor: 'default' }}>{familyLabel[selected.family]}</span>
                  <button onClick={copy} style={{ ...pill, color: copied ? C.accent : C.muted, marginLeft: 'auto' }}>
                    {copied ? ui.copied : ui.copyLink}
                  </button>
                </div>

                {/* The spec comes first: it is the statement about the tool;
                    the boxes below are what the source and the catalogs saw. */}
                <AgentSpecPanel
                  lang={short}
                  kind="tool"
                  id={selected.id}
                  entry={selected}
                  embedded={embedded}
                  flat={compact}
                  i18n={catalog?.i18n ?? []}
                  links={selected.agents.map((a) => ({ id: a.letter, ok: a.ok, href: a.ok ? agentExplorerHash(a.letter, { embedded }) : '#' }))}
                  extraControls={
                    <>
                      <a className="spec-x-target" href={selected.links.source} target="_blank" rel="noopener noreferrer" style={pill}>
                        {ui.openSource}
                      </a>
                      {selected.links.config && (
                        <a className="spec-x-target" href={selected.links.config} target="_blank" rel="noopener noreferrer" style={pill}>
                          {ui.openConfig}
                        </a>
                      )}
                    </>
                  }
                />

                {/* ---- synopsis (tri) / server (mcp) ---- */}
                {selected.family === 'tri-cli' ? (
                  <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {heading(ui.synopsis)}
                    {row(ui.command, mono(selected.command))}
                    {row(ui.variant, mono(selected.variant))}
                    {selected.args.length > 0 &&
                      row(
                        ui.args,
                        <span data-lang-exempt="live" style={{ fontFamily: C.mono, fontSize: 11.5 }}>
                          {selected.args.map((a) => (a.about ? `${a.name} — ${a.about}` : a.name)).join(' · ')}
                        </span>,
                      )}
                    <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.actions}</div>
                    {selected.actions.length === 0 ? (
                      <div style={{ fontSize: 12, color: C.muted }}>{ui.noActions}</div>
                    ) : (
                      <table style={{ borderCollapse: 'collapse', width: '100%' }} data-lang-exempt="live">
                        <tbody>
                          {selected.actions.map((a) => (
                            <tr key={a.name}>
                              <td style={{ ...cell, fontFamily: C.mono, color: C.golden, whiteSpace: 'nowrap' }}>
                                {selected.command} {a.name}
                              </td>
                              <td style={{ ...cell, color: a.about ? '#d8d8d8' : C.muted }}>{a.about || '—'}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    )}
                  </div>
                ) : (
                  <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {heading(ui.server)}
                    {row(ui.launch, mono(selected.launch))}
                    {row(ui.transport, live(selected.transport))}
                    {selected.serverVersion && row(ui.version, live(selected.serverVersion))}
                    {selected.env.length > 0 && row(ui.env, mono(selected.env.join(' · ')))}
                    {row(ui.config, selected.config ? mono(selected.config) : <span style={{ color: C.muted }}>{ui.noConfig}</span>)}
                    {selected.external && <div style={{ fontSize: 12, color: C.warn }}>{ui.external}</div>}
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                      <div style={{ fontSize: 10.5, color: C.muted, fontFamily: C.mono }}>{ui.mcpTools}</div>
                      <span style={{ fontFamily: C.mono, fontSize: 11.5, color: selected.tools.length ? C.accent : C.muted }} data-lang-exempt="live">
                        {selected.tools.length}
                      </span>
                    </div>
                    {selected.tools.length === 0 ? (
                      <div style={{ fontSize: 12, color: C.muted }} data-lang-exempt="live">
                        {selected.toolsNote}
                      </div>
                    ) : (
                      <div style={{ border: `1px solid ${C.border}`, borderRadius: 5, ...(compact ? null : { maxHeight: 420, overflow: 'auto' }) }}>
                        <table style={{ borderCollapse: 'collapse', width: '100%' }}>
                          <thead>
                            <tr>
                              <th style={th}>{ui.toolName}</th>
                              <th style={th}>{ui.toolAbout}</th>
                              <th style={th}>{ui.toolInputs}</th>
                            </tr>
                          </thead>
                          <tbody data-lang-exempt="live">
                            {selected.tools.map((x) => (
                              <tr key={x.name}>
                                <td style={{ ...cell, fontFamily: C.mono, color: C.golden, whiteSpace: 'nowrap' }}>{x.name}</td>
                                <td style={{ ...cell, color: x.about ? '#d8d8d8' : C.muted }}>{x.about || '—'}</td>
                                <td style={{ ...cell, fontFamily: C.mono, fontSize: 11, color: C.muted }}>{x.inputs.length ? x.inputs.join(', ') : ui.noInputs}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                    {row(
                      ui.resources,
                      selected.resources.length === 0 ? (
                        ui.noResources
                      ) : (
                        <span data-lang-exempt="live" style={{ fontFamily: C.mono, fontSize: 11.5 }}>
                          {selected.resources.map((r) => (r.about ? `${r.path} — ${r.about}` : r.path)).join(' · ')}
                        </span>
                      ),
                    )}
                    {selected.toolsNote && selected.tools.length > 0 && (
                      <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }} data-lang-exempt="live">
                        {selected.toolsNote}
                      </div>
                    )}
                  </div>
                )}

                {/* ---- when to use (tri) ---- */}
                {selected.family === 'tri-cli' && (
                  <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {heading(ui.whenToUse)}
                    <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.whenToUseHint}</div>
                    <div style={{ fontSize: 12.5, lineHeight: 1.55, color: '#d8d8d8' }} data-lang-exempt="live">
                      {selected.whenToUse}
                    </div>
                  </div>
                )}

                {/* ---- who owns it ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.owners)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.ownersHint}</div>
                  {selected.agents.length === 0 ? (
                    <div style={{ fontSize: 12, color: C.muted }}>
                      {ui.noOwners}
                      {selected.fields.AGENTS_NOTE ? <span data-lang-exempt="live"> — {selected.fields.AGENTS_NOTE}</span> : null}
                    </div>
                  ) : (
                    <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                      {selected.agents.map((a) => chipLink(a.ok ? agentExplorerHash(a.letter, { embedded }) : '#', a.letter, 'Ω', a.ok))}
                    </div>
                  )}
                </div>

                {/* ---- skills that name it ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {heading(ui.skills)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.skillsHint}</div>
                  {selected.skills.length === 0 ? (
                    <div style={{ fontSize: 12, color: C.muted }}>{ui.noSkills}</div>
                  ) : (
                    <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', alignItems: 'center' }}>
                      {selected.skills.map((s) => (
                        <span key={s.id} style={{ display: 'inline-flex', gap: 4, alignItems: 'center' }}>
                          {chipLink(skillExplorerHash(s.id, { embedded }), s.id, '◷')}
                          <span style={{ fontFamily: C.mono, fontSize: 10.5, color: C.muted }}>
                            {ui.via} <span data-lang-exempt="live">{s.via.join(', ')}</span>
                          </span>
                        </span>
                      ))}
                    </div>
                  )}
                </div>

                {/* ---- source ---- */}
                <div style={{ ...box, padding: 12, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  {heading(ui.source)}
                  <div style={{ fontSize: 11.5, color: C.muted, lineHeight: 1.5 }}>{ui.sourceHint}</div>
                  {row(
                    ui.source.toLowerCase(),
                    <a href={selected.links.source} target="_blank" rel="noopener noreferrer" style={{ color: C.accent, fontFamily: C.mono, fontSize: 11.5 }} data-lang-exempt="live">
                      {selected.repo}/{selected.source}@{selected.links.pinnedAt.slice(0, 7)}
                    </a>,
                  )}
                  {row(ui.aboutFrom, live(selected.aboutSource))}
                  {row(ui.witness, live(selected.witness))}
                  {row(ui.pinnedAt, live(selected.links.pinnedAt))}
                </div>
              </div>
            )}
          </main>
        )}
      </div>
    </div>
  )
}
