// ═══════════════════════════════════════════════════════════════════════════════
// counter v1.0.0 - FPGA Verilog from .tri specification
// ═══════════════════════════════════════════════════════════════════════════════
//
// Golden Identity: φ² + 1/φ² = 3
//
// DO NOT EDIT - This file is auto-generated by VIBEE
//
// Target:   xilinx (50 MHz)
// ═══════════════════════════════════════════════════════════════════════════════

`timescale 1ns / 1ps

module counter (
input  wire clk,
output  wire led0,
output  wire led1
);

endmodule
