#!/usr/bin/env python3
"""
Zenodo Bundle Completeness Checker v2

Checks if all bundle descriptions have required sections for scientific publication.
"""

import re
from pathlib import Path
from typing import Dict, List

# Required sections with actual patterns found in existing files
REQUIRED_SECTIONS = {
    "Abstract": r"^## Abstract",
    "Architecture": r"^## .*Architecture",
    "Algorithms": r"^## .*Algorithm",
    "Experimental Protocol": r"^## .*Experimental",
    "Statistical Analysis": r"^## .*Statistical",
    "Limitations": r"^## .*Limitations",
}

# Missing sections that need to be added
MISSING_SECTIONS = [
    "Broader Impact",
    "Ethics Statement", 
    "Reproducibility Card",
    "Data Availability",
    "Code Availability",
    "Acknowledgments"
]

# Optional indicators
OPTIONAL_PATTERNS = {
    "Theorems": r"(?i)theorem|proof",
    "Tables": r"^\|.*\|",
    "Math": r"\$\$[^$]+\$",
    "Code": r"```",
    "DOI": r"10\.\d+\/zenodo\.",
}

def check_file(filepath: Path) -> Dict:
    """Check a single file for required sections."""
    with open(filepath, 'r') as f:
        content = f.read()
        lines = content.split('\n')
    
    results = {
        "found_sections": [],
        "missing_sections": [],
        "optional_found": [],
        "line_count": len(lines),
        "char_count": len(content),
    }
    
    # Check required sections
    for section, pattern in REQUIRED_SECTIONS.items():
        if re.search(pattern, content, re.MULTILINE | re.IGNORECASE):
            results["found_sections"].append(section)
        else:
            results["missing_sections"].append(section)
    
    # Check for missing sections
    for section in MISSING_SECTIONS:
        pattern = f"## {section}"
        if pattern not in content:
            results["missing_sections"].append(section)
        else:
            results["found_sections"].append(section)
    
    # Check optional patterns
    for name, pattern in OPTIONAL_PATTERNS.items():
        if re.search(pattern, content, re.MULTILINE | re.IGNORECASE):
            results["optional_found"].append(name)
    
    results["total_sections"] = len(REQUIRED_SECTIONS) + len(MISSING_SECTIONS)
    results["found_count"] = len(results["found_sections"])
    results["completeness"] = results["found_count"] / results["total_sections"]
    
    return results

def print_results(bundle: str, results: Dict) -> None:
    """Print results for a single bundle."""
    found = results["found_count"]
    total = results["total_sections"]
    completeness = results["completeness"]
    lines = results["line_count"]
    chars = results["char_count"]
    
    status = "✅" if completeness >= 0.9 else "⚠️ " if completeness >= 0.7 else "❌"
    print(f"{status} {bundle}: {found}/{total} sections ({completeness:.0%}) — {lines:,} LOC")
    
    # Show missing sections
    missing = [s for s in results["missing_sections"] if s in results["missing_sections"]]
    if missing:
        print(f"   Missing: {', '.join(missing)}")
    
    # Show optional
    if results["optional_found"]:
        print(f"   Has: {', '.join(results['optional_found'])}")

def generate_improvement_report(research_dir: Path) -> str:
    """Generate a report of what needs to be added."""
    report = ["# Bundle Improvement Report", ""]
    report.append("Generated by check_bundle_completeness.py")
    report.append("Date: 2026-03-26")
    report.append("")
    
    # Get all bundles
    bundle_files = sorted(research_dir.glob("zenodo_B*_enhanced_v5.2.md"))
    
    for filepath in bundle_files:
        bundle = filepath.stem.replace("zenodo_", "").replace("_enhanced_v5.2", "").upper()
        results = check_file(filepath)
        
        if results["completeness"] < 1.0:
            report.append(f"\n## {bundle}")
            report.append(f"Completeness: {results['completeness']:.0%}")
            
            missing = [s for s in results["missing_sections"] 
                      if s in results["missing_sections"]]
            if missing:
                report.append("\n**Sections to Add:**")
                for section in missing:
                    report.append(f"- [ ] {section}")
    
    report.append("\n---")
    report.append("\n## Improvement Priority")
    report.append("\n1. **High Priority** (All bundles)")
    report.append("   - [ ] Broader Impact section")
    report.append("   - [ ] Ethics Statement section")
    report.append("   - [ ] Reproducibility Card")
    report.append("")
    report.append("2. **Medium Priority** (B001, B002, B004)")
    report.append("   - [ ] Data Availability statement")
    report.append("   - [ ] Acknowledgments section")
    report.append("")
    report.append("3. **Low Priority**")
    report.append("   - [ ] More detailed Results section")
    report.append("   - [ ] Discussion section")
    
    return "\n".join(report)

def main():
    research_dir = Path(__file__).parent
    bundle_files = list(research_dir.glob("zenodo_B*_enhanced_v5.2.md"))
    
    if not bundle_files:
        print("❌ No enhanced bundle files found")
        return
    
    print(f"📋 Found {len(bundle_files)} bundle descriptions")
    print("="*60)
    
    total_completeness = 0
    for filepath in bundle_files:
        bundle = filepath.stem.replace("zenodo_", "").replace("_enhanced_v5.2", "").upper()
        results = check_file(filepath)
        print_results(bundle, results)
        total_completeness += results["completeness"]
    
    avg_completeness = total_completeness / len(bundle_files)
    
    print("="*60)
    print(f"📊 Average completeness: {avg_completeness:.1%}")
    
    # Generate improvement report
    report = generate_improvement_report(research_dir)
    report_path = research_dir / "BUNDLE_IMPROVEMENT_REPORT.md"
    
    with open(report_path, 'w') as f:
        f.write(report)
    
    print(f"\n📝 Improvement report saved to: {report_path.name}")
    print(f"   Total lines: {len(report.split(chr(10)))}")
    
    if avg_completeness >= 0.9:
        print("✅ All bundles are well-documented!")
    elif avg_completeness >= 0.7:
        print("⚠️  Some bundles need improvement")
        print("   See BUNDLE_IMPROVEMENT_REPORT.md for details")
    else:
        print("❌ Significant improvements needed")

if __name__ == "__main__":
    main()
