import type { Block } from '../types'

export const body: Block[] = [
  {
    "kind": "h",
    "text": "The check was right twelve times in a row"
  },
  {
    "kind": "p",
    "text": "The apex, t27.ai, is served by a repository that is not the one the website is developed in. A scheduled publisher checks out the sources from gHashTag/trinity, builds them, copies the result over the apex tree, runs the same verification a human publish would run, and commits only if that verification passes. Between 16:03 UTC on 13 August and 06:00 UTC on 14 August it ran twelve times and failed twelve times, always on the same line."
  },
  {
    "kind": "code",
    "text": "blog drift: the app ships [a-repair-reaches-only-the-copy-it-lands-in\n  a-suite-that-runs-nothing-exits-zero each-half-imported-the-other\n  eleven-verdicts-were-windows-not-checkpoints green-ci-does-not-mean-usable\n  open-gigabit-ethernet-artix7 scale-field-width-already-published]\nbut blog/ holds [same list minus eleven-verdicts] — rerun build-blog.py\n- **FAIL** verify-site.sh rejected the built tree — nothing pushed"
  },
  {
    "kind": "p",
    "text": "Every word of that is accurate. The application really did list seven posts and the static tree really did hold six, and a post the application lists but the tree lacks is an HTTP 404 for every reader who does not execute JavaScript. The gate found a real defect and refused to publish a tree containing it. That is what it is for."
  },
  {
    "kind": "h",
    "text": "The remedy was a human, so the failure was total"
  },
  {
    "kind": "p",
    "text": "The static pages under blog/ are generated by build-blog.py from a file called blog-posts.json, and blog-posts.json was a snapshot somebody refreshed by hand. The publisher never invoked either. So the chain from a merged post to a readable page had one link that only a person could close, and the gate sat downstream of that link."
  },
  {
    "kind": "p",
    "text": "The consequence is the part worth keeping. The publisher is a single sequence: verify, then commit, then push. A red verification does not skip the blog and publish the rest; it publishes nothing. So a missing static page for one blog post held back every merge that came after it, none of which had anything to do with the blog."
  },
  {
    "kind": "table",
    "head": [
      "Merged into trinity",
      "What it changed",
      "Reached a reader"
    ],
    "rows": [
      [
        "#742, 15:12 UTC",
        "the blog post that tripped the gate",
        "after 16 hours"
      ],
      [
        "#743, 15:17 UTC",
        "dead translation keys and disabled sections removed",
        "after 16 hours"
      ],
      [
        "#745, 16:12 UTC",
        "a table of contents for the long verification page",
        "after 15 hours"
      ],
      [
        "#747, 17:31 UTC",
        "vertical rhythm aligned across the sub-pages",
        "after 14 hours"
      ],
      [
        "#748, 18:15 UTC",
        "the author page translated for de, es, zh",
        "after 13 hours"
      ],
      [
        "#749, 20:08 UTC",
        "the format-selection matrix at /#/select",
        "after 11 hours"
      ]
    ]
  },
  {
    "kind": "p",
    "text": "For sixteen hours the answer to \"is it merged\" was yes and the answer to \"can anyone see it\" was no, and only one of those questions had an instrument pointed at it. The dashboard of green merges was not lying; it was answering a different question than the one that matters."
  },
  {
    "kind": "h",
    "text": "The fix moves the remedy into the pipeline"
  },
  {
    "kind": "p",
    "text": "One script now owns the whole chain and the publisher calls it on every run: transpile the real posts module from the sources it just built, write blog-posts.json, regenerate blog/ and ru/blog/ and both feeds, draw a card for any post that does not have one, then regenerate the sitemap from what is on disk. The drift gate stays exactly as it was. It is still the thing that would catch a broken generator; it is no longer the thing that waits for a person."
  },
  {
    "kind": "p",
    "text": "Two details in that script are there because of how they fail rather than how they work. The exported publishedPosts is a function, not an array: stringifying the binding itself yields undefined and writes a syntactically valid, entirely empty data file without raising anything, which would delete the blog rather than fail to update it. And the cards were hand-written SVG rasterised by qlmanage, a macOS utility no runner has, so an unattended publish could never have produced the image the gate demands — the generator draws the card directly instead, in the only font family on the runner that covers Cyrillic."
  },
  {
    "kind": "p",
    "text": "The reverse direction is wired too. A post withdrawn upstream now loses its static directory, because the same gate fails the other way round when the tree holds more than the application ships, and a fix that only handles the direction that happened is half a fix."
  },
  {
    "kind": "h",
    "text": "What the green run proves and what it does not"
  },
  {
    "kind": "p",
    "text": "The first run after the change published the current sources and the apex now serves the seventh post at its own URL in both languages, with the card on disk. That is a measured fact about one run. It is not evidence that the pipeline has no other manual link in it — three more generators in the same repository are still invoked by hand, and the only reason they have not caused an outage is that no gate currently depends on them."
  },
  {
    "kind": "quote",
    "text": "A gate is only as useful as its remedy is automatic. Correct and unattendable is a worse combination than approximate and self-healing, because the correct one stops everything and tells you it was right."
  }
]

export const ruBody: Block[] = [
  {
    "kind": "h",
    "text": "Проверка была права двенадцать раз подряд"
  },
  {
    "kind": "p",
    "text": "Домен t27.ai отдаёт не тот репозиторий, в котором сайт разрабатывается. Расписанный публикатор выкачивает исходники из gHashTag/trinity, собирает их, копирует результат поверх дерева apex-репозитория, прогоняет ту же проверку, что прогнал бы человек при ручной публикации, и коммитит только если проверка прошла. С 16:03 UTC 13 августа по 06:00 UTC 14 августа он запустился двенадцать раз и упал двенадцать раз — всегда на одной строке."
  },
  {
    "kind": "code",
    "text": "blog drift: the app ships [a-repair-reaches-only-the-copy-it-lands-in\n  a-suite-that-runs-nothing-exits-zero each-half-imported-the-other\n  eleven-verdicts-were-windows-not-checkpoints green-ci-does-not-mean-usable\n  open-gigabit-ethernet-artix7 scale-field-width-already-published]\nbut blog/ holds [тот же список без eleven-verdicts] — rerun build-blog.py\n- **FAIL** verify-site.sh rejected the built tree — nothing pushed"
  },
  {
    "kind": "p",
    "text": "Здесь верно каждое слово. Приложение действительно перечисляло семь постов, а статическое дерево действительно держало шесть, и пост, который приложение перечисляет, а дерево не содержит, — это HTTP 404 для любого читателя, который не исполняет JavaScript. Гейт нашёл настоящий дефект и отказался публиковать дерево с ним. Он для этого и стоит."
  },
  {
    "kind": "h",
    "text": "Лечением был человек — поэтому отказ оказался полным"
  },
  {
    "kind": "p",
    "text": "Статические страницы в blog/ генерирует build-blog.py из файла blog-posts.json, а blog-posts.json был снимком, который кто-то обновлял руками. Публикатор не вызывал ни того, ни другого. То есть в цепочке от смерженного поста до читаемой страницы было одно звено, которое мог закрыть только человек, и гейт стоял ниже этого звена по потоку."
  },
  {
    "kind": "p",
    "text": "Важно то, что из этого следует. Публикатор — одна последовательность: проверить, потом закоммитить, потом запушить. Красная проверка не пропускает блог и не публикует остальное; она не публикует ничего. Отсутствующая статическая страница одного поста задержала все мержи, которые случились после, — и ни один из них к блогу отношения не имел."
  },
  {
    "kind": "table",
    "head": [
      "Смержено в trinity",
      "Что менял",
      "Дошёл до читателя"
    ],
    "rows": [
      [
        "#742, 15:12 UTC",
        "тот самый пост блога, который уронил гейт",
        "через 16 часов"
      ],
      [
        "#743, 15:17 UTC",
        "убраны мёртвые ключи перевода и отключённые секции",
        "через 16 часов"
      ],
      [
        "#745, 16:12 UTC",
        "оглавление длинной страницы verification",
        "через 15 часов"
      ],
      [
        "#747, 17:31 UTC",
        "выровнен вертикальный ритм подстраниц",
        "через 14 часов"
      ],
      [
        "#748, 18:15 UTC",
        "страница автора переведена на de, es, zh",
        "через 13 часов"
      ],
      [
        "#749, 20:08 UTC",
        "матрица выбора формата на /#/select",
        "через 11 часов"
      ]
    ]
  },
  {
    "kind": "p",
    "text": "Шестнадцать часов ответ на вопрос «смержено?» был «да», а ответ на вопрос «это кто-нибудь видит?» — «нет», и прибор был наведён только на первый из них. Панель зелёных мержей не врала — она отвечала на другой вопрос, не на тот, который имеет значение."
  },
  {
    "kind": "h",
    "text": "Починка переносит лечение внутрь конвейера"
  },
  {
    "kind": "p",
    "text": "Теперь всей цепочкой владеет один скрипт, и публикатор вызывает его на каждом прогоне: транспилировать настоящий модуль постов из тех исходников, которые он только что собрал, записать blog-posts.json, пересобрать blog/ и ru/blog/ и оба фида, нарисовать карточку тому посту, у которого её нет, затем пересобрать карту сайта по тому, что лежит на диске. Гейт сравнения остался в точности каким был. Он по-прежнему — то, что поймает сломанный генератор; он больше не то, что ждёт человека."
  },
  {
    "kind": "p",
    "text": "Две детали в этом скрипте стоят там из-за того, как они ломаются, а не из-за того, как они работают. Экспортируемый publishedPosts — функция, а не массив: если сериализовать саму привязку, получится undefined, и на диск ляжет синтаксически корректный, полностью пустой файл данных без единой ошибки — то есть блог будет удалён, а не «не обновлён». И карточки были рукописным SVG, растрированным через qlmanage — утилиту macOS, которой нет ни на одном раннере, — так что беспилотная публикация никогда не смогла бы получить картинку, которую требует гейт; генератор рисует карточку напрямую, в единственном семействе шрифтов на раннере, которое покрывает кириллицу."
  },
  {
    "kind": "p",
    "text": "Обратное направление тоже подключено. Пост, отозванный в исходниках, теперь теряет и свой статический каталог, потому что тот же гейт падает и в другую сторону — когда дерево держит больше, чем отдаёт приложение, — а починка, закрывающая только случившееся направление, это половина починки."
  },
  {
    "kind": "h",
    "text": "Что зелёный прогон доказывает, а что нет"
  },
  {
    "kind": "p",
    "text": "Первый прогон после правки опубликовал текущие исходники, и apex теперь отдаёт седьмой пост по его собственному адресу на двух языках, с карточкой на диске. Это измеренный факт про один прогон. Это не доказательство, что в конвейере не осталось других ручных звеньев: в том же репозитории ещё три генератора запускаются руками, и единственная причина, по которой они не устроили простоя, — что сейчас от них не зависит ни один гейт."
  },
  {
    "kind": "quote",
    "text": "Гейт полезен ровно настолько, насколько автоматично его лечение. «Верный и неавтоматизируемый» — комбинация хуже, чем «приблизительный и самовосстанавливающийся», потому что верный останавливает всё и сообщает вам, что он был прав."
  }
]
